const RAW_COLONIAL_NEUTRAL_ITEMS = new Set([
    "R-12 - “Salus” Ambulance",
    "R-12b - “Salva” Flame Truck",
    "T3 “Xiphos”",
    "T5 “Percutio”",
    "T8 “Gemini”",
    "BMS - Aquatipper",
    "R-15 - “Chariot”",
    "BMS - Universal Assembly Rig",
    "BMS - Fabricator",
    "BMS - Class 2 Mobile Auto-Crane",
    "GA6 “Cestus”",
    "R-1 Hauler",
    "R-5 “Atlas” Hauler",
    "R-5b “Sisyphus” Hauler",
    "R-9 “Speartip” Escort",
    "R-17 “Retiarius” Skirmisher",
    "UV-05a “Argonaut”",
    "UV-5c “Odyssey”",
    "UV-24 “Icarus”",
    "T12 “Actaeon” Tankette",
    "T14 “Vesta” Tankette",
    "T20 “Ixion” Tankette",
    "T13 “Deioneus” Rocket Battery",
    "HH-a “Javelin”",
    "HH-b “Hoplite”",
    "HH-d “Peltast”",
    "AB-8 “Acheron”",
    "AB-11 “Doru”",
    "H-5 \"Hatchet\"",
    "H-8 “Kranesca”",
    "H-10 “Pelekys”",
    "H-19 “Vulcan”",
    "HC-2 “Scorpion”",
    "HC-7 \"Ballista\"",
    "85K-b “Falchion”",
    "85K-a “Spatha”",
    "85V-g \"Talos\"",
    "86K-a “Bardiche”",
    "86K-c “Ranseur”",
    "G40 “Sagittarii”",
    "G40 “Sagittarii” (Crate)",
    "Bellweather by VAC",
    "Bellweather by VAC (Crate)",
    "AA-2 \"Battering Ram\"",
    "120-68 “Koronides” Field Gun",
    "Type C - “Charon”",
    "BMS - Packmule Flatbed",
    "BMS - Scrap Hauler",
    "BMS - Ironship",
    "Shipping Container",
    "Resource Container",
    "Liquid Container",
    "“Dusk” ce.III (Crate)",
    "7.92mm (Crate)",
    "Green Ash Grenade (Crate)",
    "Bomastone Grenade (Crate)",
    "PT-815 Smoke Grenade (Crate)",
    "Volta r.I Repeater (Crate)",
    "Catara mo.II (Crate)",
    "KRR2-790 Omen (Crate)",
    "KRN886-127 Gast Machine Gun (Crate)",
    "12.7mm (Crate)",
    "Ferro 879 (Crate)",
    "8mm (Crate)",
    "Cometa T2-9 (Crate)",
    ".44 Mag (Crate)",
    "Argenti r.II Rifle (Crate)",
    "Catena rt.IV Auto-Rifle (Crate)",
    "Fuscina pi.I (Crate)",
    "7.62mm (Crate)",
    "KRF1-750 Dragonfly (Crate)",
    "Buckshot (Crate)",
    "KRR3-792 Auger (Crate)",
    "“Lionclaw” mc.VIII (Crate)",
    "“The Pitch Gun” mc.V (Crate)",
    "9mm (Crate)",
    "Anti-Tank Sticky Bomb (Crate)",
    "B2 Varsi Anti-Tank Grenade (Crate)",
    "“Dawn” Ve.II (Crate)",
    "14.5mm (Crate)",
    "Bane 45 (Crate)",
    "Ignifist 30 (Crate)",
    "Venom c.II 35 (Crate)",
    "AP/RPG (Crate)",
    "ARC/RPG (Crate)",
    "“Molten Wind” v.II Flame Torch (Crate)",
    "Mammon 91-b (Crate)",
    "Tremola Grenade GPb-1 (Crate)",
    "KLG901-2 Lunaire F (Crate)",
    "30mm (Crate)",
    "Cremari Mortar (Crate)",
    "Flare Mortar Shell (Crate)",
    "Incendiary Mortar Shell (Crate)",
    "Mortar Shell (Crate)",
    "Shrapnel Mortar Shell (Crate)",
    "“Typhon” ra.XII (Crate)",
    "Mounted Fissura gd.I (Crate)",
    "Daucus isg.III (Crate)",
    "Lamentum mm.IV (Crate)",
    "RPG (Crate)",
    "“Quickhatch” Rt.I (Crate)",
    "20mm (Crate)",
    "950-70b Anti-Aircraft Shell (Crate)",
    "Absol Anti-Aircraft Rounds (Crate)",
    "68mm (Crate)",
    "Mark II Raidbreaker (Crate)",
    "Naval Buoy (Crate)",
    "40mm (Crate)",
    "Shatter Missile (Crate)",
    "Model-7 “Evie” (Crate)",
    "912 Shrike Rounds (Crate)",
    "3C-High Explosive Rocket (Crate)",
    "150mm (Crate)",
    "4C-Fire Rocket (Crate)",
    "94.5mm (Crate)",
    "75mm (Crate)",
    "120mm (Crate)",
    "Flame Ammo (Crate)",
    "E681-B Hullbreaker Mine (Crate)",
    "250mm \"Fury\" Shell (Crate)",
    "300mm (Crate)",
    "Quillback Torpedo (Crate)",
    "Paratrooper’s Ruck (Crate)",
    "Buckhorn CCQ-18 (Crate)",
    "Abisme AT-99 Mine (Crate)",
    "Alligator Charge (Crate)",
    "Crow’s Foot Mine (Crate)",
    "Havoc Charge (Crate)",
    "Hydra’s Whisper (Crate)",
    "Binoculars (Crate)",
    "Flight Mask (Crate)",
    "Gas Mask (Crate)",
    "Gas Mask Filter (Crate)",
    "Radio (Crate)",
    "Radio Backpack (Crate)",
    "Hammer (Crate)",
    "Shovel (Crate)",
    "Sledge Hammer (Crate)",
    "Water Bucket (Crate)",
    "Wrench (Crate)",
    "“Molten Wind” v.II Ammo (Crate)",
    "Willow's Bane Ammo (Crate)",
    "The Ospreay (Crate)",
    "Barbed Wire (Crate)",
    "Metal Beam (Crate)",
    "Sandbag (Crate)",
    "Material Pallet",
    "Material Pallet (Crate)",
    "Eleos Infantry Dagger (Crate)",
    "Falias Raiding Club (Crate)",
    "Air Raid Siren (Crate)",
    "Legion Vexillum (Crate)",
    "Listening Kit (Crate)",
    "War Ensign (Crate)",
    "Wind Sock (Crate)",
    "Havoc Charge Detonator (Crate)",
    "E680-S Rudder Lock (Crate)",
    "Tripod (Crate)",
    "Bandages (Crate)",
    "Blood Plasma (Crate)",
    "First Aid Kit (Crate)",
    "Trauma Kit (Crate)",
    "Soldier Supplies (Crate)",
    "Assembly Materials I (Crate)",
    "Assembly Materials II (Crate)",
    "Assembly Materials III (Crate)",
    "Assembly Materials IV (Crate)",
    "Assembly Materials V (Crate)",
    "Pipe (Crate)",
    "Processed Construction Materials (Crate)",
    "Rare Alloys (Crate)",
    "Steel Construction Materials (Crate)",
    "Thermal Shielding (Crate)",
    "Unstable Substances (Crate)",
    "Rare Materials (Crate)",
    "Oil (Crate)",
    "Water (Crate)",
    "Rare Metal (Crate)",
    "Diesel (Crate)",
    "Enriched Oil (Crate)",
    "Heavy Oil (Crate)",
    "Petrol (Crate)",
    "Basic Materials (Crate)",
    "Construction Materials (Crate)",
    "Explosive Powder (Crate)",
    "Gravel (Crate)",
    "Heavy Explosive Powder (Crate)",
    "Refined Materials (Crate)",
    "Relic Materials (Crate)",
    "Aluminum Alloy (Crate)",
    "Copper Alloy (Crate)",
    "Iron Alloy (Crate)",
    "Maintenance Supplies (Crate)",
    "Velian Flak Vest (Crate)",
    "Fabri Rucksack (Crate)",
    "Grenadier’s Baldric (Crate)",
    "Medic Fatigues (Crate)",
    "Remex Garb (Crate)",
    "Officialis’ Attire (Crate)",
    "Auster’s Harness (Crate)",
    "Lodesman’s Lorica (Crate)",
    "Legionary’s Oilcoat (Crate)",
    "Recon Camo (Crate)",
    "Heavy Topcoat (Crate)",
    "Legionary Fatigues (Crate)",
    "Tankman’s Coveralls (Crate)",
    "Colonial Aircraft Engine (Small) (Crate)",
    "Colonial Aircraft Mechanical Parts (Small) (Crate)",
    "Damaged Colonial Aircraft Engine (Small) (Crate)",
    "Damaged Colonial Aircraft Mechanical Parts (Small) (Crate)",
]);

export const COLONIAL_NEUTRAL_ITEMS = RAW_COLONIAL_NEUTRAL_ITEMS;
