export const COLONIAL_NEUTRAL_ITEMS = new Set([
    "“Dusk” ce.III (Crate)",
    "7.92mm (Crate)",
    "Catara mo.II (Crate)",
    "KRN886-127 Gast Machine Gun (Crate)",
    "Bomastone Grenade (Crate)",
    "Ferro 879 (Crate)",
    "8mm (Crate)",
    "Cometa T2-9 (Crate)",
    ".44 Mag (Crate)",
    "Catena rt.IV Auto-Rifle (Crate)",
    "Argenti r.II Rifle (Crate)",
    "Volta r.I Repeater (Crate)",
    "Fuscina pi.I (Crate)",
    "KRR2-790 Omen (Crate)",
    "KRR3-792 Auger (Crate)",
    "7.62mm (Crate)",
    "KRF1-750 Dragonfly (Crate)",
    "Buckshot (Crate)",
    "“The Pitch Gun” mc.V (Crate)",
    "“Lionclaw” mc.VIII (Crate)",
    "9mm (Crate)",
    "“Dawn” Ve.II (Crate)",
    "“Quickhatch” Rt.I (Crate)",
    "“Typhon” ra.XII (Crate)",
    "14.5mm (Crate)",
    "Venom c.II 35 (Crate)",
    "Bane 45 (Crate)",
    "AP/RPG (Crate)",
    "ARC/RPG (Crate)",
    "“Molten Wind” v.II Flame Torch (Crate)",
    "KLG901-2 Lunaire F (Crate)",
    "Mounted Fissura gd.I (Crate)",
    "Tremola Grenade GPb-1 (Crate)",
    "PT-815 Smoke Grenade (Crate)",
    "Green Ash Grenade (Crate)",
    "Lamentum mm.IV (Crate)",
    "12.7mm (Crate)",
    "Daucus isg.III (Crate)",
    "30mm (Crate)",
    "Cremari Mortar (Crate)",
    "Incendiary Mortar Shell (Crate)",
    "Flare Mortar Shell (Crate)",
    "Shrapnel Mortar Shell (Crate)",
    "Mortar Shell (Crate)",
    "B2 Varsi Anti-Tank Grenade (Crate)",
    "Ignifist 30 (Crate)",
    "Mammon 91-b (Crate)",
    "Anti-Tank Sticky Bomb (Crate)",
    "RPG (Crate)",
    "950-70b Anti-Aircraft Shell (Crate)",
    "20mm (Crate)",
    "94.5mm (Crate)",
    "75mm (Crate)",
    "Mark II Raidbreaker (Crate)",
    "912 Shrike Rounds (Crate)",
    "4C-Fire Rocket (Crate)",
    "Flame Ammo (Crate)",
    "150mm (Crate)",
    "120mm (Crate)",
    "300mm (Crate)",
    "Quillback Torpedo (Crate)",
    "250mm \"Fury\" Shell (Crate)",
    "E681-B Hullbreaker Mine (Crate)",
    "68mm (Crate)",
    "40mm (Crate)",
    "Legion Vexillum (Crate)",
    "Barbed Wire (Crate)",
    "Buckhorn CCQ-18 (Crate)",
    "Binoculars (Crate)",
    "Hydra’s Whisper (Crate)",
    "Havoc Charge (Crate)",
    "“Molten Wind” v.II Ammo (Crate)",
    "Crow’s Foot Mine (Crate)",
    "Listening Kit (Crate)",
    "Metal Beam (Crate)",
    "Paratrooper’s Ruck (Crate)",
    "Radio Backpack (Crate)",
    "Sandbag (Crate)",
    "Havoc Charge Detonator (Crate)",
    "Alligator Charge (Crate)",
    "Shovel (Crate)",
    "Sledge Hammer (Crate)",
    "Eleos Infantry Dagger (Crate)",
    "Tripod (Crate)",
    "Wind Sock (Crate)",
    "Hammer (Crate)",
    "Wrench (Crate)",
    "Water Bucket (Crate)",
    "Water (Crate)",
    "Gas Mask (Crate)",
    "Gas Mask Filter (Crate)",
    "Radio (Crate)",
    "Liaison Transmitter (Crate)",
    "Bandages (Crate)",
    "First Aid Kit (Crate)",
    "Trauma Kit (Crate)",
    "Blood Plasma (Crate)",
    "Soldier Supplies (Crate)",
    "Diesel (Crate)",
    "Unstable Substances (Crate)",
    "Thermal Shielding (Crate)",
    "Processed Construction Materials (Crate)",
    "Steel Construction Materials (Crate)",
    "Assembly Materials I (Crate)",
    "Assembly Materials II (Crate)",
    "Assembly Materials III (Crate)",
    "Assembly Materials IV (Crate)",
    "Assembly Materials V (Crate)",
    "Rare Alloys (Crate)",
    "Heavy Oil (Crate)",
    "Enriched Oil (Crate)",
    "Oil (Crate)",
    "Petrol (Crate)",
    "Pipe (Crate)",
    "Aluminum Alloy (Crate)",
    "Basic Materials (Crate)",
    "Copper Alloy (Crate)",
    "Explosive Powder (Crate)",
    "Construction Materials (Crate)",
    "Rare Materials (Crate)",
    "Gravel (Crate)",
    "Heavy Explosive Powder (Crate)",
    "Iron Alloy (Crate)",
    "Maintenance Supplies (Crate)",
    "Relic Materials (Crate)",
    "Refined Materials (Crate)",
    "Velian Flak Vest (Crate)",
    "Fabri Rucksack (Crate)",
    "Grenadier’s Baldric (Crate)",
    "Medic Fatigues (Crate)",
    "Remex Garb (Crate)",
    "Officialis’ Attire (Crate)",
    "Auster’s Harness (Crate)",
    "Cloudrunner’s Vesture (Crate)",
    "Lodesman’s Lorica (Crate)",
    "Legionary’s Oilcoat (Crate)",
    "Recon Camo (Crate)",
    "Legionary Fatigues (Crate)",
    "Tankman’s Coveralls (Crate)",
    "Colonial Aircraft Engine (Small) (Crate)",
    "Damaged Colonial Aircraft Engine (Small) (Crate)",
    "Colonial Aircraft Mechanical Parts (Small) (Crate)",
    "Damaged Colonial Aircraft Mechanical Parts (Small) (Crate)",
    "R-12 - “Salus” Ambulance",
    "R-12b - “Salva” Flame Truck",
    "T3 “Xiphos”",
    "T5 “Percutio”",
    "T8 “Gemini”",
    "BMS - Aquatipper",
    "R-15 - “Chariot”",
    "BMS - Universal Assembly Rig",
    "BMS - Fabricator",
    "BMS - Class 2 Mobile Auto-Crane",
    "GA6 “Cestus”",
    "AA-2 \"Battering Ram\"",
    "Collins Cannon 68mm",
    "40-45 “Smelter”",
    "G40 “Sagittarii”",
    "30-250 “Tisiphone” Field Cannon",
    "BMS - Packmule Flatbed",
    "BMS - Ironship",
    "Das Krokodil by VAC",
    "Type B - “Lucian”",
    "Type C - “Charon”",
    "HH-d “Peltast”",
    "HH-a “Javelin”",
    "HH-b “Hoplite”",
    "BMS - Scrap Hauler",
    "AB-8 “Acheron”",
    "AB-11 “Doru”",
    "945g “Stygian Bolt”",
    "120-68 “Koronides” Field Gun",
    "40-250 “Alekto” Heavy Cannon",
    "K-81e “Sombre”",
    "HC-2 “Scorpion”",
    "H-5 \"Hatchet\"",
    "H-19 “Vulcan”",
    "H-8 “Kranesca”",
    "H-10 “Pelekys”",
    "86K-a “Bardiche”",
    "86K-c “Ranseur”",
    "90T-v “Nemesis”",
    "85K-b “Falchion”",
    "85V-g \"Talos\"",
    "85K-a “Spatha”",
    "HC-7 \"Ballista\"",
    "00MS “Stinger”",
    "UV-05a “Argonaut”",
    "UV-24 “Icarus”",
    "UV-5c “Odyssey”",
    "T12 “Actaeon” Tankette",
    "T14 “Vesta” Tankette",
    "T13 “Deioneus” Rocket Battery",
    "T20 “Ixion” Tankette",
    "Rooster - Lamploader",
    "Rooster - Tumblebox",
    "Rooster - Junkwagon",
    "R-1 Hauler",
    "RR-3 “Stolon” Tanker",
    "R-5b “Sisyphus” Hauler",
    "R-17 “Retiarius” Skirmisher",
    "R-9 “Speartip” Escort",
    "R-5 “Atlas” Hauler",
    "V-1 Tzykalia (Crate)",
    "Mergo-4 “Myrmidon” (Crate)",
    "Toxot-902 “Blind Silver” (Crate)",
    "V-5b Pegasus (Crate)",
    "A59 Venti “Perdix” (Crate)",
    "A51 Venti “Daedalus” (Crate)",
    "R-12 - “Salus” Ambulance (Crate)",
    "T3 “Xiphos” (Crate)",
    "BMS - Aquatipper (Crate)",
    "R-15 - “Chariot” (Crate)",
    "BMS - Universal Assembly Rig (Crate)",
    "BMS - Class 2 Mobile Auto-Crane (Crate)",
    "AA-2 \"Battering Ram\" (Crate)",
    "Collins Cannon 68mm (Crate)",
    "G40 “Sagittarii” (Crate)",
    "30-250 “Tisiphone” Field Cannon (Crate)",
    "BMS - Packmule Flatbed (Crate)",
    "BMS - Ironship (Crate)",
    "Das Krokodil by VAC (Crate)",
    "Type B - “Lucian” (Crate)",
    "Type C - “Charon” (Crate)",
    "HH-a “Javelin” (Crate)",
    "AB-8 “Acheron” (Crate)",
    "120-68 “Koronides” Field Gun (Crate)",
    "K-81e “Sombre” (Crate)",
    "HC-2 “Scorpion” (Crate)",
    "H-5 \"Hatchet\" (Crate)",
    "86K-a “Bardiche” (Crate)",
    "90T-v “Nemesis” (Crate)",
    "85K-b “Falchion” (Crate)",
    "UV-05a “Argonaut” (Crate)",
    "T12 “Actaeon” Tankette (Crate)",
    "Rooster - Lamploader (Crate)",
    "Rooster - Tumblebox (Crate)",
    "Rooster - Junkwagon (Crate)",
    "R-1 Hauler (Crate)",
    "RR-3 “Stolon” Tanker (Crate)",
    "R-5 “Atlas” Hauler (Crate)",
    "Concrete Mixer",
    "Construction Equipment",
    "DAE 5b “Zeal”",
    "DAE 2a-1 “Ruptura”",
    "50-500 “Thunderbolt” Cannon",
    "DAE 1o-3 “Polybolos”",
    "DAE 1b-2 “Serra”",
    "DAE 3b-2 “Hades’ Net”",
    "Construction Parts",
    "Underground Fortress Parts",
    "Intelligence Center Parts",
    "Aircraft Radar Parts",
    "Storm Cannon Parts",
    "Structure Parts",
    "Weather Station Parts",
    "Liquid Container",
    "Material Pallet",
    "Resource Container",
    "A0E-9 Rocket Booster",
    "A0E-9 Rocket Body",
    "A0E-9 Rocket Warhead",
    "Naval Hull Segments",
    "Naval Shell Plating",
    "Naval Turbine Components",
    "Shipping Container",
    "Concrete Mixer (Crate)",
    "Construction Equipment (Crate)",
    "DAE 5b “Zeal” (Crate)",
    "50-500 “Thunderbolt” Cannon (Crate)",
    "DAE 1o-3 “Polybolos” (Crate)",
    "DAE 1b-2 “Serra” (Crate)",
    "Liquid Container (Crate)",
    "Material Pallet (Crate)",
    "Resource Container (Crate)",
    "Shipping Container (Crate)"
]);
