export type OfficialCategory =
    | 'small_arms'
    | 'heavy_arms'
    | 'heavy_ammunition'
    | 'utility'
    | 'medical'
    | 'materials'
    | 'uniforms'
    | 'aircraft_parts'
    | 'vehicles'
    | 'shippables'
    | 'vehicle_crates'
    | 'shippable_crates';

export const ITEM_CATEGORY_MAP: Record<string, OfficialCategory> = {
    // New items category mappings
    "G40 “Sagittarii”": "vehicles",
    "G40 “Sagittarii” (Crate)": "vehicle_crates",
    "Bellweather by VAC": "vehicles",
    "Bellweather by VAC (Crate)": "vehicle_crates",
    "Material Pallet": "shippables",
    "Material Pallet (Crate)": "shippable_crates",
    "R-1 Hauler": "vehicles",
    "R-5 “Atlas” Hauler": "vehicles",
    "R-5b “Sisyphus” Hauler": "vehicles",
    "R-9 “Speartip” Escort": "vehicles",
    "R-17 “Retiarius” Skirmisher": "vehicles",
    "UV-05a “Argonaut”": "vehicles",
    "UV-5c “Odyssey”": "vehicles",
    "UV-24 “Icarus”": "vehicles",
    "T12 “Actaeon” Tankette": "vehicles",
    "T14 “Vesta” Tankette": "vehicles",
    "T20 “Ixion” Tankette": "vehicles",
    "T13 “Deioneus” Rocket Battery": "vehicles",
    "HH-a “Javelin”": "vehicles",
    "HH-b “Hoplite”": "vehicles",
    "HH-d “Peltast”": "vehicles",
    "AB-8 “Acheron”": "vehicles",
    "AB-11 “Doru”": "vehicles",
    "H-5 \"Hatchet\"": "vehicles",
    "H-8 “Kranesca”": "vehicles",
    "H-10 “Pelekys”": "vehicles",
    "H-19 “Vulcan”": "vehicles",
    "HC-2 “Scorpion”": "vehicles",
    "HC-7 \"Ballista\"": "vehicles",
    "85K-b “Falchion”": "vehicles",
    "85K-a “Spatha”": "vehicles",
    "85V-g \"Talos\"": "vehicles",
    "86K-a “Bardiche”": "vehicles",
    "86K-c “Ranseur”": "vehicles",
    "120-68 “Koronides” Field Gun": "vehicles",
    "BMS - Packmule Flatbed": "vehicles",
    "BMS - Scrap Hauler": "vehicles",
    "BMS - Ironship": "vehicles",
    "Shipping Container": "shippables",
    "Resource Container": "shippables",
    "250mm \"Fury\" Shell (Crate)": "heavy_ammunition",

    "“Dusk” ce.III (Crate)": "small_arms",
    "Booker Storm Rifle Model 838 (Crate)": "small_arms",
    "Aalto Storm Rifle 24 (Crate)": "small_arms",
    "7.92mm (Crate)": "small_arms",
    "Catara mo.II (Crate)": "small_arms",
    "KRN886-127 Gast Machine Gun (Crate)": "small_arms",
    "Malone MK.2 (Crate)": "small_arms",
    "Bomastone Grenade (Crate)": "small_arms",
    "A3 Harpa Fragmentation Grenade (Crate)": "small_arms",
    "Ferro 879 (Crate)": "small_arms",
    "Cascadier 873 (Crate)": "small_arms",
    "Ahti Model 2 (Crate)": "small_arms",
    "8mm (Crate)": "small_arms",
    "Cometa T2-9 (Crate)": "small_arms",
    "The Hangman 757 (Crate)": "small_arms",
    ".44 Mag (Crate)": "small_arms",
    "Catena rt.IV Auto-Rifle (Crate)": "small_arms",
    "Sampo Auto-Rifle 77 (Crate)": "small_arms",
    "Argenti r.II Rifle (Crate)": "small_arms",
    "Volta r.I Repeater (Crate)": "small_arms",
    "Fuscina pi.I (Crate)": "small_arms",
    "Blakerow 871 (Crate)": "small_arms",
    "KRR2-790 Omen (Crate)": "small_arms",
    "Clancy Cinder M3 (Crate)": "small_arms",
    "No.2B Hawthorne (Crate)": "small_arms",
    "No.2 Loughcaster (Crate)": "small_arms",
    "KRR3-792 Auger (Crate)": "small_arms",
    "Clancy-Raca M4 (Crate)": "small_arms",
    "7.62mm (Crate)": "small_arms",
    "KRF1-750 Dragonfly (Crate)": "small_arms",
    "No.4 The Pillory Scattergun (Crate)": "small_arms",
    "Buckshot (Crate)": "small_arms",
    "“The Pitch Gun” mc.V (Crate)": "small_arms",
    "“Lionclaw” mc.VIII (Crate)": "small_arms",
    "No.1 “The Liar” Submachinegun (Crate)": "small_arms",
    "Fiddler Submachine Gun Model 868 (Crate)": "small_arms",
    "9mm (Crate)": "small_arms",
    "228 Satterley Heavy Storm Rifle (Crate)": "heavy_arms",
    "Booker Greyhound Model 910 (Crate)": "heavy_arms",
    "“Dawn” Ve.II (Crate)": "heavy_arms",
    "“Quickhatch” Rt.I (Crate)": "heavy_arms",
    "“Typhon” ra.XII (Crate)": "heavy_arms",
    "Neville Anti-Tank Rifle (Crate)": "heavy_arms",
    "14.5mm (Crate)": "heavy_arms",
    "Venom c.II 35 (Crate)": "heavy_arms",
    "Bane 45 (Crate)": "heavy_arms",
    "Carnyx Anti-Tank Rocket Launcher (Crate)": "heavy_arms",
    "AP/RPG (Crate)": "heavy_arms",
    "Mounted Bonesaw MK.3 (Crate)": "heavy_arms",
    "Bonesaw MK.3 (Crate)": "heavy_arms",
    "ARC/RPG (Crate)": "heavy_arms",
    "“Molten Wind” v.II Flame Torch (Crate)": "heavy_arms",
    "Willow’s Bane Model 845 (Crate)": "heavy_arms",
    "KLG901-2 Lunaire F (Crate)": "heavy_arms",
    "Mounted Fissura gd.I (Crate)": "heavy_arms",
    "Tremola Grenade GPb-1 (Crate)": "heavy_arms",
    "PT-815 Smoke Grenade (Crate)": "small_arms",
    "Green Ash Grenade (Crate)": "small_arms",
    "Lamentum mm.IV (Crate)": "heavy_arms",
    "Malone Ratcatcher MK.1 (Crate)": "heavy_arms",
    "12.7mm (Crate)": "small_arms",
    "Daucus isg.III (Crate)": "heavy_arms",
    "30mm (Crate)": "heavy_arms",
    "Cremari Mortar (Crate)": "heavy_arms",
    "Incendiary Mortar Shell (Crate)": "heavy_arms",
    "Flare Mortar Shell (Crate)": "heavy_arms",
    "Shrapnel Mortar Shell (Crate)": "heavy_arms",
    "Mortar Shell (Crate)": "heavy_arms",
    "BF5 White Ash Flask Grenade (Crate)": "heavy_arms",
    "B2 Varsi Anti-Tank Grenade (Crate)": "heavy_arms",
    "Ignifist 30 (Crate)": "heavy_arms",
    "Mammon 91-b (Crate)": "heavy_arms",
    "Anti-Tank Sticky Bomb (Crate)": "heavy_arms",
    "Cutler Foebreaker (Crate)": "heavy_arms",
    "Cutler Launcher 4 (Crate)": "heavy_arms",
    "RPG (Crate)": "heavy_arms",
    "950-70b Anti-Aircraft Shell (Crate)": "heavy_ammunition",
    "20mm (Crate)": "heavy_ammunition",
    "94.5mm (Crate)": "heavy_ammunition",
    "75mm (Crate)": "heavy_ammunition",
    "Mark II Raidbreaker (Crate)": "heavy_ammunition",
    "Shatter Missile (Crate)": "heavy_ammunition",
    "Model-7 “Evie” (Crate)": "heavy_ammunition",
    "912 Shrike Rounds (Crate)": "heavy_ammunition",
    "4C-Fire Rocket (Crate)": "heavy_ammunition",
    "Flame Ammo (Crate)": "heavy_ammunition",
    "150mm (Crate)": "heavy_ammunition",
    "3C-High Explosive Rocket (Crate)": "heavy_ammunition",
    "Absol Anti-Aircraft Rounds (Crate)": "heavy_ammunition",
    "120mm (Crate)": "heavy_ammunition",
    "300mm (Crate)": "heavy_ammunition",
    "Quillback Torpedo (Crate)": "heavy_ammunition",
    " Shell (Crate)": "heavy_ammunition",
    "E681-B Hullbreaker Mine (Crate)": "heavy_ammunition",
    "Naval Buoy (Crate)": "heavy_ammunition",
    "68mm (Crate)": "heavy_ammunition",
    "40mm (Crate)": "heavy_ammunition",
    "Air Raid Siren (Crate)": "utility",
    "Legion Vexillum (Crate)": "utility",
    "War Ensign (Crate)": "utility",
    "Barbed Wire (Crate)": "utility",
    "Buckhorn CCQ-18 (Crate)": "utility",
    "Binoculars (Crate)": "utility",
    "Hydra’s Whisper (Crate)": "utility",
    "Havoc Charge (Crate)": "utility",
    "“Molten Wind” v.II Ammo (Crate)": "utility",
    "Willow's Bane Ammo (Crate)": "utility",
    "Crow’s Foot Mine (Crate)": "utility",
    "Listening Kit (Crate)": "utility",
    "Falias Raiding Club (Crate)": "utility",
    "Metal Beam (Crate)": "utility",
    "Paratrooper’s Ruck (Crate)": "utility",
    "Radio Backpack (Crate)": "utility",
    "Sandbag (Crate)": "utility",
    "Havoc Charge Detonator (Crate)": "utility",
    "Alligator Charge (Crate)": "utility",
    "Shovel (Crate)": "utility",
    "Sledge Hammer (Crate)": "utility",
    "Eleos Infantry Dagger (Crate)": "utility",
    "Abisme AT-99 Mine (Crate)": "utility",
    "Tripod (Crate)": "utility",
    "E680-S Rudder Lock (Crate)": "utility",
    "Wind Sock (Crate)": "utility",
    "Hammer (Crate)": "utility",
    "Wrench (Crate)": "utility",
    "Water Bucket (Crate)": "utility",
    "Water (Crate)": "materials",
    "Gas Mask (Crate)": "utility",
    "Gas Mask Filter (Crate)": "utility",
    "The Ospreay (Crate)": "utility",
    "Radio (Crate)": "utility",
    "Flight Mask (Crate)": "utility",
    "Bandages (Crate)": "medical",
    "First Aid Kit (Crate)": "medical",
    "Trauma Kit (Crate)": "medical",
    "Blood Plasma (Crate)": "medical",
    "Soldier Supplies (Crate)": "medical",
    "Diesel (Crate)": "materials",
    "Unstable Substances (Crate)": "materials",
    "Thermal Shielding (Crate)": "materials",
    "Processed Construction Materials (Crate)": "materials",
    "Steel Construction Materials (Crate)": "materials",
    "Assembly Materials I (Crate)": "materials",
    "Assembly Materials II (Crate)": "materials",
    "Assembly Materials III (Crate)": "materials",
    "Assembly Materials IV (Crate)": "materials",
    "Assembly Materials V (Crate)": "materials",
    "Rare Alloys (Crate)": "materials",
    "Heavy Oil (Crate)": "materials",
    "Enriched Oil (Crate)": "materials",
    "Oil (Crate)": "materials",
    "Petrol (Crate)": "materials",
    "Pipe (Crate)": "materials",
    "Aluminum Alloy (Crate)": "materials",
    "Basic Materials (Crate)": "materials",
    "Copper Alloy (Crate)": "materials",
    "Explosive Powder (Crate)": "materials",
    "Construction Materials (Crate)": "materials",
    "Rare Materials (Crate)": "materials",
    "Gravel (Crate)": "materials",
    "Heavy Explosive Powder (Crate)": "materials",
    "Iron Alloy (Crate)": "materials",
    "Maintenance Supplies (Crate)": "materials",
    "Rare Metal (Crate)": "materials",
    "Relic Materials (Crate)": "materials",
    "Refined Materials (Crate)": "materials",
    "Specialist’s Overcoat (Crate)": "uniforms",
    "Velian Flak Vest (Crate)": "uniforms",
    "Gunner’s Breastplate (Crate)": "uniforms",
    "Fabri Rucksack (Crate)": "uniforms",
    "Sapper Gear (Crate)": "uniforms",
    "Grenadier’s Baldric (Crate)": "uniforms",
    "Medic Fatigues (Crate)": "uniforms",
    "Physician’s Jacket (Crate)": "uniforms",
    "Remex Garb (Crate)": "uniforms",
    "Gentleman’s Peacoat (Crate)": "uniforms",
    "Officialis’ Attire (Crate)": "uniforms",
    "Officer’s Regalia (Crate)": "uniforms",
    "Auster’s Harness (Crate)": "uniforms",
    "Cloudrunner’s Vesture (Crate)": "uniforms",
    "Lodesman’s Lorica (Crate)": "uniforms",
    "Aviator’s Raiment (Crate)": "uniforms",
    "Legionary’s Oilcoat (Crate)": "uniforms",
    "Recon Camo (Crate)": "uniforms",
    "Outrider’s Mantle (Crate)": "uniforms",
    "Heavy Topcoat (Crate)": "uniforms",
    "Caoivish Parka (Crate)": "uniforms",
    "Legionary Fatigues (Crate)": "uniforms",
    "Infantry Battledress (Crate)": "uniforms",
    "Tankman’s Coveralls (Crate)": "uniforms",
    "Padded Boiler Suit (Crate)": "uniforms",
    "Colonial Aircraft Engine (Small) (Crate)": "aircraft_parts",
    "Warden Aircraft Engine (Small) (Crate)": "aircraft_parts",
    "Damaged Colonial Aircraft Engine (Small) (Crate)": "aircraft_parts",
    "Damaged Warden Aircraft Engine (Small) (Crate)": "aircraft_parts",
    "Colonial Aircraft Mechanical Parts (Small) (Crate)": "aircraft_parts",
    "Warden Aircraft Mechanical Parts (Small) (Crate)": "aircraft_parts",
    "Damaged Colonial Aircraft Mechanical Parts (Small) (Crate)": "aircraft_parts",
    "Damaged Warden Aircraft Mechanical Parts (Small) (Crate)": "aircraft_parts",
    "R-12 - “Salus” Ambulance": "vehicles",
    "R-12b - “Salva” Flame Truck": "vehicles",
    "Dunne Dousing Engine 3r": "vehicles",
    "Dunne Responder 3e": "vehicles",
    "O’Brien V.101 Freeman": "vehicles",
    "O’Brien v.200 Squire": "vehicles",
    "O’Brien V.190 Knave": "vehicles",
    "O’Brien V.113 Gravekeeper": "vehicles",
    "T3 “Xiphos”": "vehicles",
    "O’Brien V.130 Wild Jack": "vehicles",
    "O’Brien V.121 Highlander": "vehicles",
    "T5 “Percutio”": "vehicles",
    "T8 “Gemini”": "vehicles",
    "O’Brien V.110": "vehicles",
    "BMS - Aquatipper": "vehicles",
    "R-15 - “Chariot”": "vehicles",
    "Dunne Caravaner 2f": "vehicles",
    "BMS - Universal Assembly Rig": "shippables",
    "Liquid Container": "shippables",
    "BMS - Fabricator": "vehicles",
    "BMS - Class 2 Mobile Auto-Crane": "vehicles",
    "Noble Firebrand Mk. XVII": "vehicles",
    "Noble Widow MK. XIV": "vehicles",
    "GA6 “Cestus”": "vehicles",
    "Duncan’s Coin 14.5mm": "vehicles",
    "AA-2 \"Battering Ram\"": "vehicles",
    "Type C - “Charon”": "vehicles",
    "“Dusk” ce.III": "small_arms",
    "Aalto Storm Rifle 24": "small_arms",
    "Booker Storm Rifle Model 838": "small_arms",
    "7.92mm": "small_arms",
    "Green Ash Grenade": "small_arms",
    "A3 Harpa Fragmentation Grenade": "small_arms",
    "Bomastone Grenade": "small_arms",
    "PT-815 Smoke Grenade": "small_arms",
    "The Hangman 757": "small_arms",
    "Volta r.I Repeater": "small_arms",
    "Catara mo.II": "small_arms",
    "Clancy Cinder M3": "small_arms",
    "KRR2-790 Omen": "small_arms",
    "KRN886-127 Gast Machine Gun": "small_arms",
    "Malone MK.2": "small_arms",
    "12.7mm": "small_arms",
    "Ahti Model 2": "small_arms",
    "Cascadier 873": "small_arms",
    "Ferro 879": "small_arms",
    "8mm": "small_arms",
    "Cometa T2-9": "small_arms",
    ".44 Mag": "small_arms",
    "Argenti r.II Rifle": "small_arms",
    "Blakerow 871": "small_arms",
    "Catena rt.IV Auto-Rifle": "small_arms",
    "Fuscina pi.I": "small_arms",
    "No.2 Loughcaster": "small_arms",
    "No.2B Hawthorne": "small_arms",
    "Sampo Auto-Rifle 77": "small_arms",
    "7.62mm": "small_arms",
    "KRF1-750 Dragonfly": "small_arms",
    "No.4 The Pillory Scattergun": "small_arms",
    "Buckshot": "small_arms",
    "Clancy-Raca M4": "small_arms",
    "KRR3-792 Auger": "small_arms",
    "“Lionclaw” mc.VIII": "small_arms",
    "“The Pitch Gun” mc.V": "small_arms",
    "Fiddler Submachine Gun Model 868": "small_arms",
    "No.1 “The Liar” Submachine Gun": "small_arms",
    "No.1 “The Liar” Submachine Gun (Crate)": "small_arms",
    "9mm": "small_arms",
    "Anti-Tank Sticky Bomb": "heavy_arms",
    "B2 Varsi Anti-Tank Grenade": "heavy_arms",
    "BF5 White Ash Flask Grenade": "heavy_arms",
    "“Dawn” Ve.II": "heavy_arms",
    "Booker Greyhound Model 910": "heavy_arms",
    "Neville Anti-Tank Rifle": "heavy_arms",
    "14.5mm": "heavy_arms",
    "Bane 45": "heavy_arms",
    "Bonesaw MK.3": "heavy_arms",
    "Carnyx Anti-Tank Rocket Launcher": "heavy_arms",
    "Ignifist 30": "heavy_arms",
    "Venom c.II 35": "heavy_arms",
    "AP/RPG": "heavy_arms",
    "ARC/RPG": "heavy_arms",
    "228 Satterley Heavy Storm Rifle": "heavy_arms",
    "“Molten Wind” v.II Flame Torch": "heavy_arms",
    "Willow's Bane Model 845": "heavy_arms",
    "Willow's Bane Model 845 (Crate)": "heavy_arms",
    "Mammon 91-b": "heavy_arms",
    "Tremola Grenade GPb-1": "heavy_arms",
    "KLG901-2 Lunaire F": "heavy_arms",
    "30mm": "heavy_arms",
    "Cremari Mortar": "heavy_arms",
    "Flare Mortar Shell": "heavy_arms",
    "Incendiary Mortar Shell": "heavy_arms",
    "Mortar Shell": "heavy_arms",
    "Shrapnel Mortar Shell": "heavy_arms",
    "“Typhon” ra.XII": "heavy_arms",
    "Mounted Bonesaw MK.3": "heavy_arms",
    "Mounted Fissura gd.I": "heavy_arms",
    "Daucus isg.III": "heavy_arms",
    "Lamentum mm.IV": "heavy_arms",
    "Malone Ratcatcher MK.1": "heavy_arms",
    "Cutler Foebreaker": "heavy_arms",
    "RPG": "heavy_arms",
    "Cutler Launcher 4": "heavy_arms",
    "“Quickhatch” Rt.I": "heavy_arms",
    "20mm": "heavy_ammunition",
    "Absol Anti-Aircraft Rounds": "heavy_ammunition",
    "950-70b Anti-Aircraft Shell": "heavy_ammunition",
    "68mm": "heavy_ammunition",
    "Mark II Raidbreaker": "heavy_ammunition",
    "Naval Buoy": "heavy_ammunition",
    "40mm": "heavy_ammunition",
    "Shatter Missile": "heavy_ammunition",
    "Model-7 “Evie”": "heavy_ammunition",
    "912 Shrike Rounds": "heavy_ammunition",
    "3C-High Explosive Rocket": "heavy_ammunition",
    "150mm": "heavy_ammunition",
    "4C-Fire Rocket": "heavy_ammunition",
    "94.5mm": "heavy_ammunition",
    "75mm": "heavy_ammunition",
    "120mm": "heavy_ammunition",
    "Flame Ammo": "heavy_ammunition",
    "E681-B Hullbreaker Mine": "heavy_ammunition",
    "250mm “Fury” Shell": "heavy_ammunition",
    "250mm “Fury” Shell (Crate)": "heavy_ammunition",
    "250mm “Purity” Shell": "heavy_ammunition",
    "250mm “Purity” Shell (Crate)": "heavy_ammunition",
    "300mm": "heavy_ammunition",
    "Moray Torpedo": "heavy_ammunition",
    "Moray Torpedo (Crate)": "heavy_ammunition",
    "Quillback Torpedo": "heavy_ammunition",
    "Tenta Torpedo": "heavy_ammunition",
    "Tenta Torpedo (Crate)": "heavy_ammunition",
    "Paratrooper's Ruck": "utility",
    "Paratrooper's Ruck (Crate)": "utility",
    "Buckhorn CCQ-18": "utility",
    "Abisme AT-99": "utility",
    "Abisme AT-99 (Crate)": "utility",
    "Alligator Charge": "utility",
    "Crow's Foot Mine": "utility",
    "Crow's Foot Mine (Crate)": "utility",
    "Havoc Charge": "utility",
    "Hydra's Whisper": "utility",
    "Hydra's Whisper (Crate)": "utility",
    "Binoculars": "utility",
    "Flight Mask": "utility",
    "Gas Mask": "utility",
    "Gas Mask Filter": "utility",
    "Liaison Transmitter": "utility",
    "Liaison Transmitter (Crate)": "utility",
    "Radio": "utility",
    "Radio Backpack": "utility",
    "Hammer": "utility",
    "Shovel": "utility",
    "Sledge Hammer": "utility",
    "Water Bucket": "utility",
    "Wrench": "utility",
    "“Molten Wind” v.II Ammo": "utility",
    "Willow's Bane Ammo": "utility",
    "The Ospreay": "utility",
    "Barbed Wire": "utility",
    "Metal Beam": "utility",
    "Sandbag": "utility",
    "Eleos Infantry Dagger": "utility",
    "Falias Raiding Club": "utility",
    "Air Raid Siren": "utility",
    "Legion Vexillum": "utility",
    "Listening Kit": "utility",
    "War Ensign": "utility",
    "Wind Sock": "utility",
    "Havoc Charge Detonator": "utility",
    "Reserve Power": "utility",
    "Reserve Power (Crate)": "utility",
    "E680-S Rudder Lock": "utility",
    "Tripod": "utility",
    "Critically Wounded Soldier": "medical",
    "Critically Wounded Soldier (Crate)": "medical",
    "Bandages": "medical",
    "Blood Plasma": "medical",
    "First Aid Kit": "medical",
    "Trauma Kit": "medical",
    "Soldier Supplies": "medical",
    "Wounded Player": "medical",
    "Wounded Player (Crate)": "medical",
    "Assembly Materials I": "materials",
    "Assembly Materials II": "materials",
    "Assembly Materials III": "materials",
    "Assembly Materials IV": "materials",
    "Assembly Materials V": "materials",
    "Concrete Materials": "materials",
    "Concrete Materials (Crate)": "materials",
    "Pipe": "materials",
    "Processed Construction Materials": "materials",
    "Rare Alloys": "materials",
    "Steel Construction Materials": "materials",
    "Thermal Shielding": "materials",
    "Unstable Substances": "materials",
    "Rare Materials": "materials",
    "Oil": "materials",
    "Water": "materials",
    "Aluminum": "materials",
    "Aluminum (Crate)": "materials",
    "Coal": "materials",
    "Coal (Crate)": "materials",
    "Components": "materials",
    "Components (Crate)": "materials",
    "Copper": "materials",
    "Copper (Crate)": "materials",
    "Damaged Components": "materials",
    "Damaged Components (Crate)": "materials",
    "Iron": "materials",
    "Iron (Crate)": "materials",
    "Rare Metal": "materials",
    "Salvage": "materials",
    "Salvage (Crate)": "materials",
    "Sulfur": "materials",
    "Sulfur (Crate)": "materials",
    "Diesel": "materials",
    "Enriched Oil": "materials",
    "Heavy Oil": "materials",
    "Petrol": "materials",
    "Basic Materials": "materials",
    "Coke": "materials",
    "Coke (Crate)": "materials",
    "Construction Materials": "materials",
    "Explosive Powder": "materials",
    "Gravel": "materials",
    "Heavy Explosive Powder": "materials",
    "Refined Materials": "materials",
    "Relic Materials": "materials",
    "Aluminum Alloy": "materials",
    "Copper Alloy": "materials",
    "Iron Alloy": "materials",
    "Maintenance Supplies": "materials",
    "Wreckage": "materials",
    "Wreckage (Crate)": "materials",
    "Velian Flak Vest": "uniforms",
    "Fabri Rucksack": "uniforms",
    "Grenadier's Baldric": "uniforms",
    "Grenadier's Baldric (Crate)": "uniforms",
    "Medic Fatigues": "uniforms",
    "Remex Garb": "uniforms",
    "Officialis' Attire": "uniforms",
    "Officialis' Attire (Crate)": "uniforms",
    "Auster's Harness": "uniforms",
    "Auster's Harness (Crate)": "uniforms",
    "Lodesman's Lorica": "uniforms",
    "Lodesman's Lorica (Crate)": "uniforms",
    "Legionary's Oilcoat": "uniforms",
    "Legionary's Oilcoat (Crate)": "uniforms",
    "Recon Camo": "uniforms",
    "Heavy Topcoat": "uniforms",
    "Legionary Fatigues": "uniforms",
    "Tankman's Coveralls": "uniforms",
    "Tankman's Coveralls (Crate)": "uniforms",
    "Gunner's Breastplate": "uniforms",
    "Gunner's Breastplate (Crate)": "uniforms",
    "Sapper Gear": "uniforms",
    "Specialist's Overcoat": "uniforms",
    "Specialist's Overcoat (Crate)": "uniforms",
    "Physician's Jacket": "uniforms",
    "Physician's Jacket (Crate)": "uniforms",
    "Gentleman's Peacoat": "uniforms",
    "Gentleman's Peacoat (Crate)": "uniforms",
    "Officer's Regalia": "uniforms",
    "Officer's Regalia (Crate)": "uniforms",
    "Cloudrunner's Vesture": "uniforms",
    "Cloudrunner's Vesture (Crate)": "uniforms",
    "Aviator's Raiment": "uniforms",
    "Aviator's Raiment (Crate)": "uniforms",
    "Outrider's Mantle": "uniforms",
    "Outrider's Mantle (Crate)": "uniforms",
    "Caoivish Parka": "uniforms",
    "Infantry Battledress": "uniforms",
    "Padded Boiler Suit": "uniforms",
    "Colonial Aircraft Engine (Large)": "aircraft_parts",
    "Colonial Aircraft Engine (Large) (Crate)": "aircraft_parts",
    "Colonial Aircraft Engine (Small)": "aircraft_parts",
    "Colonial Aircraft Mechanical Parts (Large)": "aircraft_parts",
    "Colonial Aircraft Mechanical Parts (Large) (Crate)": "aircraft_parts",
    "Colonial Aircraft Mechanical Parts (Small)": "aircraft_parts",
    "Warden Aircraft Engine (Large)": "aircraft_parts",
    "Warden Aircraft Engine (Large) (Crate)": "aircraft_parts",
    "Warden Aircraft Engine (Small)": "aircraft_parts",
    "Warden Aircraft Mechanical Parts (Large)": "aircraft_parts",
    "Warden Aircraft Mechanical Parts (Large) (Crate)": "aircraft_parts",
    "Warden Aircraft Mechanical Parts (Small)": "aircraft_parts",
    "Damaged Colonial Aircraft Engine (Large)": "aircraft_parts",
    "Damaged Colonial Aircraft Engine (Large) (Crate)": "aircraft_parts",
    "Damaged Colonial Aircraft Engine (Small)": "aircraft_parts",
    "Damaged Colonial Aircraft Mechanical Parts (Large)": "aircraft_parts",
    "Damaged Colonial Aircraft Mechanical Parts (Large) (Crate)": "aircraft_parts",
    "Damaged Colonial Aircraft Mechanical Parts (Small)": "aircraft_parts",
    "Damaged Warden Aircraft Engine (Large)": "aircraft_parts",
    "Damaged Warden Aircraft Engine (Large) (Crate)": "aircraft_parts",
    "Damaged Warden Aircraft Engine (Small)": "aircraft_parts",
    "Damaged Warden Aircraft Mechanical Parts (Large)": "aircraft_parts",
    "Damaged Warden Aircraft Mechanical Parts (Large) (Crate)": "aircraft_parts",
    "Damaged Warden Aircraft Mechanical Parts (Small)": "aircraft_parts",
};

// Pre-normalize the category map for robust lookup
const NORMALIZED_CATEGORY_MAP: Record<string, OfficialCategory> = {};
Object.entries(ITEM_CATEGORY_MAP).forEach(([key, val]) => {
    const normalizedKey = key.replace(/[“”]/g, '"').toLowerCase().trim();
    NORMALIZED_CATEGORY_MAP[normalizedKey] = val;
});

export function getItemOfficialCategory(itemName: string): OfficialCategory {
    const query = itemName.replace(/[“”]/g, '"').toLowerCase().trim();
    
    let rawCat: OfficialCategory | undefined = NORMALIZED_CATEGORY_MAP[query];
    
    if (!rawCat && query.endsWith(' (crate)')) {
        const base = query.substring(0, query.length - 8);
        rawCat = NORMALIZED_CATEGORY_MAP[base];
    }
    
    // If not found in map, use keyword pattern rules
    if (!rawCat) {
        if (query.includes('material') || query.includes('alloy') || query.includes('powder') || query.includes('supplies') || query.includes('gravel') || query.includes('sandbag') || query.includes('barbed') || query.includes('pipe') || query.includes('metal beam')) {
            rawCat = 'materials';
        } else if (query.includes('plasma') || query.includes('bandage') || query.includes('first aid') || query.includes('trauma') || query.includes('shirt')) {
            rawCat = 'medical';
        } else if (query.includes('uniform') || query.includes('coat') || query.includes('parka') || query.includes('regalia') || query.includes('attire') || query.includes('harness') || query.includes('lorica') || query.includes('raiment') || query.includes('jacket') || query.includes('vesture') || query.includes('overcoat') || query.includes('suit') || query.includes('fatigues') || query.includes('battledress')) {
            rawCat = 'uniforms';
        } else if (query.includes('engine') || query.includes('aircraft')) {
            rawCat = 'aircraft_parts';
        } else {
            const vehicleKeywords = [
                'ambulance', 'truck', 'engine', 'freeman', 'squire', 'knave', 'gravekeeper', 
                'xiphos', 'wild jack', 'highlander', 'percutio', 'gemini', 'chariot', 'caravaner', 
                'assembly rig', 'flatbed', 'ironship', 'krokodil', 'blackguard', 'gunship', 'peltast', 
                'javelin', 'hoplite', 'skycaller', 'blinder', 'scar twin', 'scrap hauler', 'rigger', 
                'cliffwrest', 'acheron', 'doru', 'lpc', 'field gun', 'scorp', 'sagaris', 'birdeater', 
                'hatchet', 'ironhide', 'vulcan', 'kranesca', 'pelekys', 'strider', 'bardiche', 'thornfall', 
                'highwayman', 'outlaw', 'ranseur', 'brigand', 'nemesis', 'lordscar', 'falchion', 'talos', 
                'spatha', 'chieftain', 'ballista', 'caster', 'stinger', 'wheel', 'jester', 'gallant', 
                'spire', 'argonaut', 'icarus', 'spitfire', 'odyssey', 'loscann', 'tankette', 'battery', 
                'lamploader', 'tumblebox', 'junkwagon', 'hauler', 'leatherback', 'tanker', 'fuelrunner', 
                'sisyphus', 'landrunner', 'skirmisher', 'escort', 'loadlugger', 'transport'
            ];
            
            const structureKeywords = [
                'mixer', 'equipment', 'bolas', 'starbreaker', 'shellbore', 'ruptura', 'thunderbolt', 
                'exalt', 'polybolos', 'serra', 'snare trap', 'lariat', 'hades', 'fortress', 'radar', 
                'cannon', 'weather station', 'container', 'pallet', 'booster', 'rocket body', 'warhead', 
                'hull segment', 'shell plating', 'turbine'
            ];

            const smallArmsKeywords = [
                'pistol', 'rifle', 'smg', 'carbine', 'revolver', 'shotgun', 'bayonet', 'rounds', 'ammo',
                '7.92mm', '7.62mm', '9mm', '8mm', '12.7mm', 'buckshot', 'dusk', 'catara', 'gast', 
                'malone', 'cinder', 'cometa', 'hawthorne', 'blakerow', 'loughcaster', 'omen', 
                'lionclaw', 'fiddler', 'liar', 'grayhound', 'grenade'
            ];

            const heavyArmsKeywords = [
                'bonesaw', 'cutler', 'ignifist', 'foebreaker', 'launcher', 'lunaire', 'fissura', 
                'typhon', 'neville', 'bane', 'venom', 'mounted'
            ];

            const heavyAmmoKeywords = [
                'mortar', '20mm', '30mm', '40mm', '68mm', '75mm', '94.5mm', '120mm', '150mm', 
                '250mm', '300mm', 'rocket', 'missile', 'torpedo', 'shell'
            ];

            if (vehicleKeywords.some(kw => query.includes(kw))) {
                rawCat = 'vehicles';
            } else if (structureKeywords.some(kw => query.includes(kw))) {
                rawCat = 'shippables';
            } else if (smallArmsKeywords.some(kw => query.includes(kw))) {
                rawCat = 'small_arms';
            } else if (heavyArmsKeywords.some(kw => query.includes(kw))) {
                rawCat = 'heavy_arms';
            } else if (heavyAmmoKeywords.some(kw => query.includes(kw))) {
                rawCat = 'heavy_ammunition';
            } else {
                rawCat = 'utility';
            }
        }
    }

    if (rawCat === 'vehicles' || rawCat === 'vehicle_crates') {
        if (query.endsWith('(crate)')) {
            return 'vehicle_crates';
        }
        return 'vehicles';
    }
    
    if (rawCat === 'shippables' || rawCat === 'shippable_crates') {
        if (query.endsWith('(crate)')) {
            return 'shippable_crates';
        }
        return 'shippables';
    }

    return rawCat;
}
