export type Language = 'en' | 'tr' | 'pt-BR' | 'ru' | 'de';

export const translations = {
    en: {
        // App / Header
        logistics_intelligence: "Logistics Intelligence",
        officer_access: "Officer Authority",
        member_access: "Normal Authority",
        disconnect: "Log Out",
        tactical_logistics_dashboard: "made by docka",

        // CSV Input Panel
        csv_input: "CSV Input",
        csv_input_desc_officer: "Paste the CSV inventory copy of the Seaport or Storage Depot.",
        csv_input_desc_member: "Paste function restricted to Logistics Officers.",
        csv_input_placeholder_officer: "Paste CSV data here...",
        csv_input_placeholder_member: "Logistics Officer credentials required to paste and import scan data.",
        import_stock: "Import Stock",
        load_sample: "Load Sample",

        // Depot Database Panel
        depot_database: "DEPOT DATABASE",
        depot_database_desc: "Access and browse regional depots and ports registered in the tactical database.",
        browse_depots: "Browse Depots",
        detailed_analysis: "Detailed Analysis",
        clear_all_data: "Clear All Data",
        select_active_depot: "Active Depot Selector",
        no_depots_imported: "No depots imported yet.",

        // Main Display
        no_active_depot: "No depot active. Please import a CSV to begin.",
        location: "Location",
        last_updated: "Last Updated",
        edit_settings: "Edit Settings",
        delete_depot: "Delete Depot",
        supply_request_board: "PRODUCTION ORDER BOARD",
        supply_request_board_desc: "Coordinate and track production orders across the active regional facilities.",

        // Tabs
        tab_inventory: "Inventory",
        tab_cross_search: "Cross-Search",
        tab_supply_requests: "Production Orders",

        // Confirm Modal
        confirm_title: "CONFIRM ACTION",
        confirm_cancel: "Cancel",
        confirm_yes: "Yes, Confirm",

        // Depot Settings Modal
        depot_settings: "DEPOT SETTINGS",
        depot_settings_desc: "Customize depot identification name.",
        custom_identifier_name: "Custom Identifier Name",
        save_changes: "Save Changes",
        close: "Close",

        // Discord Gate
        tactical_intel_gateway: "Logistics Tracking System",
        auth_required: "Logistics tracking requires authorization. Please select your role.",
        role_officer: "Officer Authority",
        role_member: "Normal Authority",
        role_developer: "Developer",
        auth_pending_title: "APPROVAL PENDING",
        auth_pending_desc: "Your account was successfully created. Access to the system requires Logistics Developer approval. Please contact a manager.",
        auth_rejected_title: "APPLICATION REJECTED",
        auth_rejected_desc: "Your request to join has been rejected by administrators. Unauthorized access blocked. Please contact a logistics manager.",
        auth_approved_title: "APPLICATION APPROVED",
        auth_approved_desc: "Your account has been approved by logistics administrators! You can now log in to the system.",
        auth_btn_go_back: "Log Out / Go Back",
        auth_btn_enter_system: "Log In to System",
        secure_access: "Secure Access",

        // Inventory Tab
        filter_stock_category: "FILTER STOCK CATEGORY",
        all_items: "All Items",
        crates_only: "Crates Only",
        individual_only: "Loose Only",
        vehicles: "Vehicles",
        structures: "Structures",
        search_item_placeholder: "Search item by name...",
        search_user_placeholder: "Search user by username...",
        select_depot: "Select Depot",
        total_items: "Total Items",
        increased_stock: "Increased Stock",
        decreased_stock: "Decreased Stock",
        new_items: "New Items",
        unchanged: "Unchanged",
        currently_in_stock: "Currently in stock",
        items_higher_qty: "Items with higher quantities",
        items_lower_qty: "Items with lower quantities",
        newly_added: "Newly added to depot",
        item_name: "Item Name",
        category: "Category",
        previous_qty: "Previous Qty",
        current_qty: "Current Qty",
        difference: "Difference",
        no_items_match: "No items match the active filters.",
        showing: "Showing",
        to: "to",
        of: "of",
        entries: "entries",
        previous: "Previous",
        next: "Next",
        search_logs_placeholder: "Search logs...",

        // Cross Search Tab
        global_search: "GLOBAL SEARCH",
        global_search_desc: "Search for a material across all registered depots.",
        search_item_name: "Search item name...",
        depot_location: "Depot Location",
        quantity: "Quantity",
        status: "Status",
        matches_found_in: "Matches found in",
        depots_label: "depots.",
        no_matching_supplies: "No matching supplies found in any depot.",
        search_across_all_depots: "Search Across All Depots",
        access_code: "Access Code",
        access_code_placeholder: "6-digit numeric access code",
        share_code_with_members: "Share access code with members?",
        code_locked_for_members: "Restricted",
        click_to_reveal: "Click to reveal access code",
        validation_6_digits: "Access code must be exactly 6 digits.",
        remove_code_help: "Leave blank to remove password",

        // Supply Requests Tab
        active_requests: "Active Requests",
        completed: "Completed",
        request_item: "Request Item",
        progress: "Progress",
        actions: "Actions",
        deliver_cargo: "Deliver Cargo",
        mark_completed: "Mark as Completed",
        undo_completion: "Undo Completion",
        no_active_supply_requests: "No active production orders.",
        open_request: "Create Order",

        // Create Request Modal
        open_supply_request: "CREATE PRODUCTION ORDER",
        target_depot_port: "Target Depot / Port",
        add_items_request: "Add Items to Order",
        item_name_csv_match: "Item Name",
        type_search_stock: "Type to search all game items...",
        enter_item_name: "Enter item name...",
        required: "Required",
        add: "Add",
        added_items_count: "Added Items",
        no_items_added: "No items added yet. Search and add items above.",
        cancel: "Cancel",
        cat_item: "Item",
        cat_crate: "Crate",
        cat_vehicle: "Vehicle",
        cat_structure: "Structure",
        enter_target_depot_name: "Enter target depot name...",

        // Toast Messages & Dialog confirmation
        role_officer_required_csv: "Logistics Officer role required to import inventory scans.",
        paste_csv_first: "Please paste CSV data first.",
        invalid_csv_format: "Error: Invalid CSV format.",
        csv_missing_items: "Error: Imported CSV is missing some standard items.",
        csv_extra_items: "Error: Imported CSV contains item names outside the standard list.",
        csv_malformed_line: "Error: CSV contains malformed or unreadable lines.",
        invalid_depot_name: "Error: Invalid depot location name in CSV.",
        invalid_username_format: "Invalid username. Only English letters, numbers, and underscores are allowed (No Turkish or special characters).",
        import_success: "Successfully imported {location} inventory!",
        import_updated: "Successfully updated {location} inventory!",
        authorized_access: "Authorized access as {role}.",
        session_terminated: "Session terminated.",
        role_officer_required_sample: "Logistics Officer role required to load sample datasets.",
        sample_loaded: "30 simulated depots loaded across 10 regions!",
        clear_db_confirm_title: "CLEAR DATABASE",
        clear_db_confirm_msg: "Are you sure you want to permanently delete all tracked depots and clear local storage history? This action cannot be undone.",
        clear_db_success: "Cleared all tracked depots from database.",
        clear_logs_confirm_title: "CLEAR AUDIT LOGS",
        clear_logs_confirm_msg: "Are you sure you want to permanently delete all audit log history? This action cannot be undone.",
        clear_logs_success: "Cleared audit log history.",
        clear: "Clear",
        delete_depot_confirm_title: "DELETE DEPOT",
        delete_depot_confirm_msg: "Are you sure you want to delete the depot \"{displayName}\" and all its historical scan data?",
        delete_depot_success: "Deleted depot {displayName} database entry.",
        role_officer_required_delete: "Logistics Officer role required to delete depots.",
        role_officer_required_settings: "Logistics Officer role required to modify settings.",
        settings_updated: "Depot settings updated successfully.",
        role_officer_required_create_req: "Logistics Officer role required to create requests.",
        role_officer_required_reopen: "Logistics Officer role required to reopen requests.",
        request_created: "Production order with {count} items created successfully.",
        cargo_delivered: "Cargo delivery registered.",
        item_status_toggled: "Item status toggled.",
        request_status_updated: "Production order status updated.",
        request_removed: "Production order removed.",
        delete_request_confirm_title: "DELETE ORDER",
        delete_request_confirm_msg: "Are you sure you want to permanently delete this production order?",
        back_to_dashboard: "Back to Dashboard",
        request_not_found: "Request not found.",
        item_must_match: "Item name must be a valid game item (present in the game database).",
        item_already_added: "This item has already been added to the order.",









        qty_must_greater_zero: "Quantity must be greater than zero.",
        no_items_positive_qty: "Error: No items with positive quantity found. Depot not imported.",

        // Analytics Modal
        tactical_stock_analysis: "TACTICAL STOCK ANALYSIS",
        analytics_desc: "Aggregated database inventory shifts and logistics intelligence metrics.",
        analytics_maintenance_title: "WORK IN PROGRESS",
        analytics_maintenance_desc: "The tactical stock analytics engine is currently under development. Access will be restored shortly.",
        analytics_wip_warning: "This section is still under development and may not function fully. Please report any issues you encounter via the Feedback tab.",
        select_depot_scope: "Select Depot Scope",
        all_depots_ports_aggregated: "All Depots / Ports (Aggregated)",
        active_depots: "Active Depots",
        tactical_storage_nodes: "Tactical storage nodes",
        total_supplies_stock: "Total supplies in stock",
        net_change: "Net Change",
        overall_qty_shift: "Overall quantity shift",
        shift_dist_item_count: "Shift Distribution (Item Count)",
        no_changes_detected_dist: "No changes detected to compute distribution.",
        shifts_label: "SHIFTS",
        new_entries: "New Entries",
        top_5_items_change_qty: "Top 5 Items by Change Quantity",
        no_changes_detected_logs: "No changes detected in inventory logs.",
        top_depots_shift_volume: "Top Depots by Shift Volume",
        no_depot_data_found: "No depot data found.",
        loading_war_status: "Retrieving Conquest intelligence...",
        shifts_lowercase: "shifts",
        chart_tab_depleting: "Item Consumption (X-Y Bar)",
        chart_tab_trends: "Regional Stocks (X-Y Line)",
        search_item_analytics: "Search item by name...",
        chart_title_depleting: "ITEM CONSUMPTION DISTRIBUTION (X-Y BAR)",
        chart_desc_depleting: "Shows stock depletion (loss) and remaining quantity of the selected item across depots.",
        no_data_for_item: "No depletion or stock data found for \"{item}\" in the active scope.",
        depletion_logs_desc: "Chronological list of stock decreases, highlighting the volume of items consumed/withdrawn.",
        regional_breakdown_desc: "Aggregated inventory status categorized by geographic region and item classes.",

        // Supply Requests Tab additional
        percent_full: "{percent}% Full",
        created_at: "Created: {time}",
        request_order_num: "Production Order #{id}",
        reopen_order: "Reopen Order",
        complete_order: "Complete Order",
        reopen_item: "Reopen Item",
        mark_item_complete: "Mark Item Complete",
        delete_request_order: "Delete Production Order",
        status_open: "Open",
        status_all: "All",
        all_depots: "All Depots",
        active_depot_only: "Active Depot Only",
        no_matching_requests: "No active production orders found matching your filters.",
        
        // Crypto & Login
        enter_password: "Enter Access Password",
        login_btn: "Login",
        invalid_password: "Authentication Failed: Decryption failed. Incorrect password.",
        setup_title: "SECURITY INITIALIZATION",
        setup_desc: "Configure secure encryption passwords for this browser. Data is encrypted locally using AES-256.",
        officer_pwd_label: "Set Officer Password (Full Read/Write Access)",
        member_pwd_label: "Set Member Password (Read-Only Access)",
        confirm_pwd_label: "Confirm Password",
        pwd_mismatch: "Passwords do not match.",
        setup_btn: "Initialize Secure Database",
        setup_success: "Security setup successful. Database is now encrypted.",
        reset_data_btn: "Reset Password & Data",
        reset_data_confirm: "WARNING: This will permanently delete all local encrypted data (depots and requests) on this device. Do you want to proceed?",
        developer_access: "Developer Authority",
        notifications: "NOTIFICATIONS",
        no_notifications: "No notifications.",
        announcements: "Announcements",
        audit_logs: "AUDIT LOGS",
        audit_logs_desc: "Chronological record of logistics operations and database state changes.",
        developer_portal: "DEVELOPER PORTAL",
        developer_portal_desc: "Approve new registrations and manage user authorities.",
        approve_as_member: "Approve as Member",
        approve_as_officer: "Approve as Officer",
        post_announcement: "Post Announcement",
        announcement_content: "Announcement Content",
        announcement_placeholder: "Type global announcement message here...",
        publish: "Publish",
        critical_stock_warning: "CRITICAL STOCK ALERT: {itemName} count is {count} units in {depotName} (< 50).",
        critical_stock_badge: "CRITICAL",
        critical_stock_alerts: "Critical Stock Alerts",
        claim_delivery: "Claim Delivery",
        claim_for_self: "Claim for Yourself",
        release_claim: "Release Claim",
        claimed_by: "Claimed by: {name}",
        claimed_by_you: "Claimed by: You",
        unclaimed: "Unclaimed",
        select_delivery_operator: "Select Delivery Operator",
        select_mock_operator_placeholder: "Select an operator or enter custom name...",
        custom_operator_name: "Custom Operator Name",
        claim_action: "Claim",
        action: "Action",
        role: "Role",
        username: "Username",
        approvals: "Approvals",
        users: "Users",
        approve: "Approve",
        reject: "Reject",
        promote_to_officer: "Promote to Officer",
        demote_to_member: "Demote to Member",
        timestamp: "Timestamp",
        no_audit_logs: "No audit logs available.",
        announcement_title: "Announcement Title",
        announcement_title_placeholder: "Enter announcement title...",
        severity: "Severity",
        severity_normal: "Normal",
        severity_high: "High",
        severity_critical: "Critical",
        seen_by: "Seen by",
        seen_by_tooltip: "Seen by: {users}",
        nobody_seen: "No one has seen this yet",
        control_deck: "CONTROL DECK",
        discord_intel_hub: "Logistics Guilds",
        system_security: "Security & Role",
        security_role: "Access Role",
        db_encryption: "DB Protection",
        theme: "Appearance",
        language: "Language",
        theme_dark: "Dark",
        theme_light: "Light",
        auth_panel_title: "AUTHORIZED ACCESS PANEL",
        auth_panel_desc: "Log in to the system or create a new authorization request.",
        auth_login_tab: "Log In",
        auth_register_tab: "Register",
        auth_username_label: "Username",
        auth_password_label: "Password",
        auth_username_placeholder: "logislave",
        auth_connecting: "Connecting...",
        auth_send_request: "Send Request",
        auth_decrypting: "Decrypting password...",
        feedback_bug_report: "Bug Report",
        feedback_feature_idea: "New Feature / Idea",
        feedback_category_label: "Category",
        feedback_status_label: "Status",
        feedback_status_pending: "Pending",
        feedback_status_in_progress: "In Progress",
        feedback_status_completed: "Completed",
        feedback_delete_confirm: "Are you sure you want to delete this feedback?",
        feedback_action_progress: "Start Work",
        feedback_action_complete: "Complete",
        feedback_page_label: "Page",
        crate_vehicles: "Crate Vehicles",
        cat_crate_vehicle: "Crate Vehicle",
        csv_capturer: "CSV Capturer",
        click_to_view_content: "Click to view content"
    },
    tr: {
        // App / Header
        logistics_intelligence: "Lojistik İstihbarat",
        officer_access: "Subay Yetkisi",
        member_access: "Normal Yetki",
        disconnect: "Çıkış Yap",
        tactical_logistics_dashboard: "made by docka",

        // CSV Input Panel
        csv_input: "CSV Veri Girişi",
        csv_input_desc_officer: "Liman veya Depolama Deposunun kopyalanmış CSV envanter verisini yapıştırın.",
        csv_input_desc_member: "Yapıştırma fonksiyonu Lojistik Subayları ile sınırlandırılmıştır.",
        csv_input_placeholder_officer: "CSV verisini buraya yapıştırın...",
        csv_input_placeholder_member: "Envanter verisi aktarmak için Lojistik Subayı kimlik doğrulaması gereklidir.",
        import_stock: "Stok Aktar",
        load_sample: "Örnek Yükle",

        // Depot Database Panel
        depot_database: "DEPO VERİTABANI",
        depot_database_desc: "Taktik veritabanında kayıtlı olan bölgesel depoları ve limanları listeleyin.",
        browse_depots: "Depoları Listele",
        detailed_analysis: "Detaylı Analiz",
        clear_all_data: "Tüm Verileri Temizle",
        select_active_depot: "Aktif Depo Seçimi",
        no_depots_imported: "Henüz veri aktarılmış depo yok.",

        // Main Display
        no_active_depot: "Aktif depo seçilmedi. Başlamak için lütfen CSV verisi aktarın.",
        location: "Konum",
        last_updated: "Son Güncelleme",
        edit_settings: "Ayarları Düzenle",
        delete_depot: "Depoyu Sil",
        supply_request_board: "ÜRETİM SİPARİŞ PANOSU",
        supply_request_board_desc: "Aktif tesisler ve bölgeler arasındaki üretim siparişlerini koordine edin.",

        // Tabs
        tab_inventory: "Envanter",
        tab_cross_search: "Çapraz Arama",
        tab_supply_requests: "Üretim Siparişleri",

        // Confirm Modal
        confirm_title: "İŞLEMİ ONAYLA",
        confirm_cancel: "İptal",
        confirm_yes: "Evet, Onayla",

        // Depot Settings Modal
        depot_settings: "DEPO AYARLARI",
        depot_settings_desc: "Depo tanımlama adını özelleştirin.",
        custom_identifier_name: "Özel Tanımlayıcı Adı",
        save_changes: "Değişiklikleri Kaydet",
        close: "Kapat",

        // Discord Gate
        tactical_intel_gateway: "Lojistik Takip Sistemi",
        auth_required: "Lojistik takibi yetkilendirme gerektirir. Lütfen rolünüzü seçin.",
        role_officer: "Subay Yetkisi",
        role_member: "Normal Yetki",
        role_developer: "Geliştirici",
        auth_pending_title: "BAŞVURU ONAY BEKLENİYOR",
        auth_pending_desc: "Hesabınız başarıyla oluşturuldu. Sisteme erişmek için Lojistik Geliştirici (Developer) onayı beklenmektedir. Lütfen yöneticinizle iletişime geçin.",
        auth_rejected_title: "BAŞVURUNUZ REDDEDİLDİ",
        auth_rejected_desc: "Sisteme giriş talebiniz yöneticiler tarafından reddedilmiştir. Yetkisiz erişim engellendi. Lütfen bir lojistik müdürü ile iletişime geçin.",
        auth_approved_title: "BAŞVURUNUZ ONAYLANDI",
        auth_approved_desc: "Hesabınız lojistik yöneticileri tarafından onaylanmıştır. Artık sisteme giriş yapabilirsiniz.",
        auth_btn_go_back: "Çıkış Yap / Geri Dön",
        auth_btn_enter_system: "Sisteme Giriş Yap",
        secure_access: "Güvenli Erişim",

        // Inventory Tab
        filter_stock_category: "STOK KATEGORİSİNİ FİLTRELE",
        all_items: "Tüm Malzemeler",
        crates_only: "Kutulu",
        individual_only: "Kutusuz",
        vehicles: "Araçlar",
        structures: "Yapılar",
        search_item_placeholder: "Malzeme adıyla ara...",
        search_user_placeholder: "Kullanıcı adı ara...",
        select_depot: "Depo Seç",
        total_items: "Toplam Malzeme",
        increased_stock: "Artan Stok",
        decreased_stock: "Azalan Stok",
        new_items: "Yeni Malzemeler",
        unchanged: "Değişmeyenler",
        currently_in_stock: "Mevcut stok miktarı",
        items_higher_qty: "Miktarı artan malzemeler",
        items_lower_qty: "Miktarı azalan malzemeler",
        newly_added: "Depoya yeni eklenenler",
        item_name: "Malzeme Adı",
        category: "Kategori",
        previous_qty: "Önceki Miktar",
        current_qty: "Mevcut Miktar",
        difference: "Fark",
        no_items_match: "Aktif filtrelere uygun malzeme bulunamadı.",
        showing: "Gösterilen:",
        to: "-",
        of: "/",
        entries: "kayıt",
        previous: "Önceki",
        next: "Sonraki",
        search_logs_placeholder: "Log kaydı ara...",

        // Cross Search Tab
        global_search: "KÜRESEL ARAMA",
        global_search_desc: "Tüm kayıtlı depolarda bir malzemeyi arayın.",
        search_item_name: "Malzeme adını yazın...",
        depot_location: "Depo Konumu",
        quantity: "Miktar",
        status: "Durum",
        matches_found_in: "Toplam",
        depots_label: "depoda eşleşme bulundu.",
        no_matching_supplies: "Hiçbir depoda eşleşen malzeme bulunamadı.",
        search_across_all_depots: "Tüm Depolar Arası Arama Yapın",
        access_code: "Erişim Şifresi",
        access_code_placeholder: "6 haneli sayısal şifre girin",
        share_code_with_members: "Şifre üyelere de açılsın mı?",
        code_locked_for_members: "Sadece Yetkililer",
        click_to_reveal: "Erişim kodunu görmek için tıklayın",
        validation_6_digits: "Erişim şifresi tam olarak 6 haneli olmalıdır.",
        remove_code_help: "Şifreyi kaldırmak için boş bırakın",

        // Supply Requests Tab
        active_requests: "Aktif Talepler",
        completed: "Tamamlandı",
        request_item: "Talep Edilen Malzeme",
        progress: "İlerleme",
        actions: "İşlemler",
        deliver_cargo: "Kargo Teslim Et",
        mark_completed: "Tamamlandı Olarak İşaretle",
        undo_completion: "Geri Al",
        no_active_supply_requests: "Aktif üretim siparişi bulunmamaktadır.",
        open_request: "Sipariş Oluştur",

        // Create Request Modal
        open_supply_request: "ÜRETİM SİPARİŞİ AÇ",
        target_depot_port: "Hedef Depo / Liman",
        add_items_request: "Siparişe Malzeme Ekle",
        item_name_csv_match: "Malzeme Adı",
        type_search_stock: "Tüm oyun malzemelerinde aramak için yazın...",
        enter_item_name: "Malzeme adını girin...",
        required: "Gerekli",
        add: "Ekle",
        added_items_count: "Eklenen Malzemeler",
        no_items_added: "Henüz malzeme eklenmedi. Yukarıdan malzeme arayıp ekleyin.",
        cancel: "İptal",
        cat_item: "Malzeme",
        cat_crate: "Kasa",
        cat_vehicle: "Araç",
        cat_structure: "Yapı",
        enter_target_depot_name: "Hedef depo adını girin...",

        // Toast Messages & Dialog confirmation
        role_officer_required_csv: "Envanter verisi aktarmak için Lojistik Subayı rolü gereklidir.",
        paste_csv_first: "Lütfen önce CSV verisini yapıştırın.",
        invalid_csv_format: "Hata: Geçersiz CSV formatı.",
        csv_missing_items: "Hata: Aktarılan CSV dosyasında bazı standart malzemeler eksik.",
        csv_extra_items: "Hata: Aktarılan CSV dosyasında standart liste dışı malzemeler bulundu.",
        csv_malformed_line: "Hata: CSV dosyasında bozuk veya okunamayan satırlar mevcut.",
        invalid_depot_name: "Hata: CSV'de geçersiz depo konum adı.",
        invalid_username_format: "Geçersiz kullanıcı adı. Sadece İngilizce karakterler, rakamlar ve alt çizgi (_) kullanılabilir (Türkçe veya özel karakter kullanamazsınız).",
        import_success: "{location} envanteri başarıyla aktarıldı!",
        import_updated: "{location} envanteri başarıyla güncellendi!",
        authorized_access: "{role} olarak yetkilendirildi.",
        session_terminated: "Oturum sonlandırıldı.",
        role_officer_required_sample: "Örnek veri setlerini yüklemek için Lojistik Subayı rolü gereklidir.",
        sample_loaded: "10 bölgede 30 simüle depo başarıyla yüklendi!",
        clear_db_confirm_title: "VERİTABANINI TEMİZLE",
        clear_db_confirm_msg: "Tüm takip edilen depoları ve yerel depolama geçmişini kalıcı olarak silmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
        clear_db_success: "Takip edilen tüm depolar veritabanından silindi.",
        clear_logs_confirm_title: "DENETİM GÜNLÜĞÜNÜ TEMİZLE",
        clear_logs_confirm_msg: "Tüm denetim günlüğü geçmişini kalıcı olarak silmek istediğinize emin misiniz? Bu işlem geri alınamaz.",
        clear_logs_success: "Denetim günlüğü geçmişi temizlendi.",
        clear: "Temizle",
        delete_depot_confirm_title: "DEPOYU SİL",
        delete_depot_confirm_msg: "\"{displayName}\" deposunu ve tüm geçmiş tarama verilerini silmek istediğinize emin misiniz?",
        delete_depot_success: "{displayName} deposunun veritabanı kaydı silindi.",
        role_officer_required_delete: "Depoları silmek için Lojistik Subayı rolü gereklidir.",
        role_officer_required_settings: "Ayarları değiştirmek için Lojistik Subayı rolü gereklidir.",
        settings_updated: "Depo ayarları başarıyla güncellendi.",
        role_officer_required_create_req: "Talep oluşturmak için Lojistik Subayı rolü gereklidir.",
        role_officer_required_reopen: "Talepleri yeniden açmak için Lojistik Subayı rolü gereklidir.",
        request_created: "{count} malzemeli üretim siparişi başarıyla oluşturuldu.",
        cargo_delivered: "Kargo teslimatı kaydedildi.",
        item_status_toggled: "Malzeme durumu değiştirildi.",
        request_status_updated: "Üretim sipariş durumu güncellendi.",
        request_removed: "Üretim siparişi kaldırıldı.",
        delete_request_confirm_title: "SİPARİŞİ SİL",
        delete_request_confirm_msg: "Bu üretim siparişini kalıcı olarak silmek istediğinize emin misiniz?",
        back_to_dashboard: "Gösterge Paneline Dön",
        request_not_found: "Üretim siparişi bulunamadı.",
        item_must_match: "Malzeme adı oyundaki geçerli bir malzeme ile eşleşmelidir.",
        item_already_added: "Bu malzeme siparişe zaten eklenmiş.",
        qty_must_greater_zero: "Miktar sıfırdan büyük olmalıdır.",
        no_items_positive_qty: "Hata: Pozitif miktarlı malzeme bulunamadı. Depo aktarılmadı.",

        // Analytics Modal
        tactical_stock_analysis: "TAKTİK STOK ANALİZİ",
        analytics_desc: "Bütünleşik veritabanı envanter değişimleri ve lojistik istihbarat metrikleri.",
        analytics_maintenance_title: "ÜZERİNDE ÇALIŞILIYOR",
        analytics_maintenance_desc: "Taktiksel stok analiz motoru üzerinde çalışmalar devam etmektedir. Erişim kısa süre içinde sağlanacaktır.",
        analytics_wip_warning: "Bu kısım üzerinde hala çalışılmaktadır ve tam olarak doğru çalışmıyor olabilir. Lütfen gördüğünüz hataları geribildirim sekmesi üzerinden bildiriniz.",
        select_depot_scope: "Depo Kapsamını Seçin",
        all_depots_ports_aggregated: "Tüm Depolar / Limanlar (Birleştirilmiş)",
        active_depots: "Aktif Depolar",
        tactical_storage_nodes: "Taktiksel depolama düğümleri",
        total_supplies_stock: "Stoktaki toplam malzeme",
        net_change: "Net Değişim",
        overall_qty_shift: "Genel miktar değişimi",
        shift_dist_item_count: "Değişim Dağılımı (Malzeme Sayısı)",
        no_changes_detected_dist: "Dağılımı hesaplamak için herhangi bir değişim tespit edilmedi.",
        shifts_label: "DEĞİŞİM",
        new_entries: "Yeni Girişler",
        top_5_items_change_qty: "Miktar Değişimine Göre En İyi 5 Malzeme",
        no_changes_detected_logs: "Envanter günlüklerinde herhangi bir değişim tespit edilmedi.",
        top_depots_shift_volume: "Değişim Hacmine Göre En İyi Depolar",
        no_depot_data_found: "Depo verisi bulunamadı.",
        loading_war_status: "Savaş istihbaratı alınıyor...",
        shifts_lowercase: "değişim",
        chart_tab_depleting: "Eşya Tüketimi (X-Y Bar)",
        chart_tab_trends: "Bölgesel Stoklar (X-Y Çizgi)",
        search_item_analytics: "Eşya adına göre ara...",
        chart_title_depleting: "EŞYA TÜKETİM DAĞILIMI (X-Y BAR)",
        chart_desc_depleting: "Seçilen eşyanın depolardaki stok kaybı (tüketim) ve kalan miktar dağılımını gösterir.",
        no_data_for_item: "Aktif kapsamda \"{item}\" için tüketim veya stok verisi bulunamadı.",
        depletion_logs_desc: "Depolardan eksilen malzemelerin listesidir; hangi eşyanın ne kadar tüketildiğini/çekildiğini gösterir.",
        regional_breakdown_desc: "Coğrafi bölgelere göre gruplandırılmış toplam stok miktarlarını ve malzeme kategorilerini gösterir.",

        // Supply Requests Tab additional
        percent_full: "%{percent} Dolu",
        created_at: "Oluşturulma: {time}",
        request_order_num: "Üretim Siparişi #{id}",
        reopen_order: "Siparişi Yeniden Aç",
        complete_order: "Siparişi Tamamla",
        reopen_item: "Malzemeyi Yeniden Aç",
        mark_item_complete: "Malzemeyi Tamamlandı İşaretle",
        delete_request_order: "Üretim Siparişini Sil",
        status_open: "Açık",
        status_all: "Hepsi",
        all_depots: "Tüm Depolar",
        active_depot_only: "Sadece Aktif Depo",
        no_matching_requests: "Filtrelerinize uygun aktif üretim siparişi bulunamadı.",
        
        // Crypto & Login
        enter_password: "Erişim Parolasını Girin",
        login_btn: "Giriş Yap",
        invalid_password: "Kimlik Doğrulama Başarısız: Şifre çözülemedi. Geçersiz parola.",
        setup_title: "GÜVENLİK KURULUMU",
        setup_desc: "Bu tarayıcı için güvenli şifreleme parolalarını yapılandırın. Tüm veriler yerel olarak AES-256 ile şifrelenir.",
        officer_pwd_label: "Subay Parolası Belirle (Tam Okuma/Yazma Yetkisi)",
        member_pwd_label: "Üye Parolası Belirle (Salt Okunur Yetki)",
        confirm_pwd_label: "Parolayı Onayla",
        pwd_mismatch: "Parolalar eşleşmiyor.",
        setup_btn: "Güvenli Veritabanını Başlat",
        setup_success: "Güvenlik kurulumu başarılı. Veritabanı şifrelendi.",
        reset_data_btn: "Parolayı ve Verileri Sıfırla",
        reset_data_confirm: "UYARI: Bu işlem bu cihazdaki tüm yerel şifrelenmiş verileri (depolar ve talepler) kalıcı olarak silecektir. Devam etmek istiyor musunuz?",
        developer_access: "Geliştirici Yetkisi",
        notifications: "BİLDİRİMLER",
        no_notifications: "Bildirim bulunmuyor.",
        announcements: "Duyurular",
        audit_logs: "DENETİM GÜNLÜĞÜ",
        audit_logs_desc: "Lojistik işlemlerinin ve veritabanı durum değişikliklerinin kronolojik kaydı.",
        developer_portal: "GELİŞTİRİCİ PORTALI",
        developer_portal_desc: "Yeni üyelikleri onaylayın ve kullanıcı yetkilerini yönetin.",
        approve_as_member: "Üye Olarak Onayla",
        approve_as_officer: "Subay Olarak Onayla",
        post_announcement: "Duyuru Yayınla",
        announcement_content: "Duyuru İçeriği",
        announcement_placeholder: "Küresel duyuru mesajını buraya yazın...",
        publish: "Yayınla",
        critical_stock_warning: "KRİTİK STOK UYARISI: {depotName} deposunda {itemName} miktarı {count} adede düştü (< 50).",
        critical_stock_badge: "KRİTİK",
        critical_stock_alerts: "Kritik Stok Alarmları",
        claim_delivery: "Teslimatı Üstlen",
        claim_for_self: "Kendin Üstlen",
        release_claim: "Sahiplenmeyi Bırak",
        claimed_by: "Teslim Eden: {name}",
        claimed_by_you: "Teslim Eden: Siz",
        unclaimed: "Sahiplenilmedi",
        select_delivery_operator: "Teslimat Yapacak Operatörü Seçin",
        select_mock_operator_placeholder: "Bir operatör seçin veya özel ad girin...",
        custom_operator_name: "Özel Operatör Adı",
        claim_action: "Sahiplen",
        action: "İşlem",
        role: "Rol",
        username: "Kullanıcı Adı",
        approvals: "Onaylar",
        users: "Kullanıcılar",
        approve: "Onayla",
        reject: "Reddet",
        promote_to_officer: "Subay Yap",
        demote_to_member: "Üyeliğe Düşür",
        timestamp: "Tarih/Saat",
        no_audit_logs: "Denetim günlüğü kaydı bulunmamaktadır.",
        announcement_title: "Duyuru Başlığı",
        announcement_title_placeholder: "Duyuru başlığını girin...",
        severity: "Önem Derecesi",
        severity_normal: "Normal",
        severity_high: "Yüksek",
        severity_critical: "Kritik",
        seen_by: "Görenler",
        seen_by_tooltip: "Görenler: {users}",
        nobody_seen: "Henüz kimse görmedi",
        control_deck: "KONTROL PANELİ",
        discord_intel_hub: "Lojistik Birlikleri",
        system_security: "Sistem Güvenliği",
        security_role: "Yetki Rolü",
        db_encryption: "Veritabanı Koruması",
        theme: "Görünüm",
        language: "Dil",
        theme_dark: "Koyu",
        theme_light: "Açık",
        auth_panel_title: "YETKİLİ ERİŞİM PANELİ",
        auth_panel_desc: "Sisteme giriş yapın veya yeni bir yetki talebi oluşturun.",
        auth_login_tab: "Giriş Yap",
        auth_register_tab: "Kayıt Ol",
        auth_username_label: "Kullanıcı Adı",
        auth_password_label: "Şifre",
        auth_username_placeholder: "logislave",
        auth_connecting: "Bağlanıyor...",
        auth_send_request: "Kayıt Talebi Gönder",
        auth_decrypting: "Şifre Çözülüyor...",
        feedback_bug_report: "Hata Bildirimi",
        feedback_feature_idea: "Yeni Özellik / Fikir",
        feedback_category_label: "Kategori",
        feedback_status_label: "Durum",
        feedback_status_pending: "Beklemede",
        feedback_status_in_progress: "Üzerinde Çalışılıyor",
        feedback_status_completed: "Tamamlandı",
        feedback_delete_confirm: "Bu geri bildirimi silmek istediğinizden emin misiniz?",
        feedback_action_progress: "Çalışma Başlat",
        feedback_action_complete: "Tamamla",
        feedback_page_label: "Sayfa",
        crate_vehicles: "Kutulu Araçlar",
        cat_crate_vehicle: "Kutu Araç",
        csv_capturer: "CSV Yakalayıcı",
        click_to_view_content: "İçeriği görmek için tıklayın"
    },
    'pt-BR': {
        // App / Header
        logistics_intelligence: "Inteligência Logística",
        officer_access: "Autoridade de Oficial",
        member_access: "Autoridade Normal",
        disconnect: "Sair",
        tactical_logistics_dashboard: "feito por docka",

        // CSV Input Panel
        csv_input: "Entrada CSV",
        csv_input_desc_officer: "Cole a cópia do inventário CSV do Porto ou Depósito de Armazenamento.",
        csv_input_desc_member: "Função de colar restrita a Oficiais de Logística.",
        csv_input_placeholder_officer: "Cole os dados do CSV aqui...",
        csv_input_placeholder_member: "Credenciais de Oficial de Logística são necessárias para colar e importar dados de escaneamento.",
        import_stock: "Importar Estoque",
        load_sample: "Carregar Amostra",

        // Depot Database Panel
        depot_database: "BANCO DE DADOS DE DEPÓSITOS",
        depot_database_desc: "Acesse e navegue pelos depósitos e portos regionais registrados no banco de dados tático.",
        browse_depots: "Navegar Depósitos",
        detailed_analysis: "Análise Detalhada",
        clear_all_data: "Limpar Todos os Dados",
        select_active_depot: "Seletor de Depósito Ativo",
        no_depots_imported: "Nenhum depósito importado ainda.",

        // Main Display
        no_active_depot: "Nenhum depósito ativo. Por favor, importe um CSV para começar.",
        location: "Localização",
        last_updated: "Última Atualização",
        edit_settings: "Editar Configurações",
        delete_depot: "Excluir Depósito",
        supply_request_board: "PAINEL DE ORDENS DE PRODUÇÃO",
        supply_request_board_desc: "Coordene e rastreie ordens de produção entre as instalações regionais ativas.",

        // Tabs
        tab_inventory: "Inventário",
        tab_cross_search: "Busca Cruzada",
        tab_supply_requests: "Ordens de Produção",

        // Confirm Modal
        confirm_title: "CONFIRMAR AÇÃO",
        confirm_cancel: "Cancelar",
        confirm_yes: "Sim, Confirmar",

        // Depot Settings Modal
        depot_settings: "CONFIGURAÇÕES DO DEPÓSITO",
        depot_settings_desc: "Personalize o nome de identificação do depósito.",
        custom_identifier_name: "Nome do Identificador Personalizado",
        save_changes: "Salvar Alterações",
        close: "Fechar",

        // Discord Gate
        tactical_intel_gateway: "Sistema de Rastreamento Logístico",
        auth_required: "O rastreamento logístico requer autorização. Por favor, selecione sua função.",
        role_officer: "Autoridade de Oficial",
        role_member: "Autoridade Normal",
        role_developer: "Desenvolvedor",
        auth_pending_title: "APROVAÇÃO PENDENTE",
        auth_pending_desc: "Sua conta foi criada com sucesso. O acesso ao sistema requer aprovação do Desenvolvedor de Logística. Por favor, entre em contato com um gerente.",
        auth_rejected_title: "SOLICITAÇÃO REJEITADA",
        auth_rejected_desc: "Sua solicitação de adesão foi rejeitada pelos administradores. Acesso não autorizado bloqueado. Por favor, entre em contato com um gerente de logística.",
        auth_approved_title: "SOLICITAÇÃO APROVADA",
        auth_approved_desc: "Sua conta foi aprovada pelos administradores de logística! Agora você pode entrar no sistema.",
        auth_btn_go_back: "Sair / Voltar",
        auth_btn_enter_system: "Entrar no Sistema",
        secure_access: "Acesso Seguro",

        // Inventory Tab
        filter_stock_category: "FILTRAR CATEGORIA DE ESTOQUE",
        all_items: "Todos os Itens",
        crates_only: "Apenas Caixas",
        individual_only: "Apenas Soltos",
        vehicles: "Veículos",
        structures: "Estruturas",
        search_item_placeholder: "Buscar item por nome...",
        search_user_placeholder: "Buscar usuário por nome...",
        select_depot: "Selecionar Depósito",
        total_items: "Total de Itens",
        increased_stock: "Estoque Aumentado",
        decreased_stock: "Estoque Diminuído",
        new_items: "Novos Itens",
        unchanged: "Sem Alterações",
        currently_in_stock: "Atualmente em estoque",
        items_higher_qty: "Itens com maiores quantidades",
        items_lower_qty: "Itens com menores quantidades",
        newly_added: "Recém-adicionado ao depósito",
        item_name: "Nome do Item",
        category: "Categoria",
        previous_qty: "Qtd Anterior",
        current_qty: "Qtd Atual",
        difference: "Diferença",
        no_items_match: "Nenhum item corresponde aos filtros ativos.",
        showing: "Exibindo",
        to: "a",
        of: "de",
        entries: "entradas",
        previous: "Anterior",
        next: "Próximo",
        search_logs_placeholder: "Buscar logs...",

        // Cross Search Tab
        global_search: "BUSCA GLOBAL",
        global_search_desc: "Busque por um material em todos os depósitos registrados.",
        search_item_name: "Buscar nome do item...",
        depot_location: "Localização do Depósito",
        quantity: "Quantidade",
        status: "Status",
        matches_found_in: "Correspondências encontradas em",
        depots_label: "depósitos.",
        no_matching_supplies: "Nenhum suprimento correspondente encontrado em nenhum depósito.",
        search_across_all_depots: "Buscar em Todos os Depósitos",
        access_code: "Código de Acesso",
        access_code_placeholder: "Código de acesso numérico de 6 dígitos",
        share_code_with_members: "Compartilhar código de acesso com membros?",
        code_locked_for_members: "Restrito",
        click_to_reveal: "Clique para revelar o código de acesso",
        validation_6_digits: "O código de acesso deve ter exatamente 6 dígitos.",
        remove_code_help: "Deixe em branco para remover a senha",

        // Supply Requests Tab
        active_requests: "Solicitações Ativas",
        completed: "Concluído",
        request_item: "Item Solicitado",
        progress: "Progresso",
        actions: "Ações",
        deliver_cargo: "Entregar Carga",
        mark_completed: "Marcar como Concluído",
        undo_completion: "Desfazer Conclusão",
        no_active_supply_requests: "Nenhuma ordem de produção ativa.",
        open_request: "Criar Ordem",

        // Create Request Modal
        open_supply_request: "CRIAR ORDEM DE PRODUÇÃO",
        target_depot_port: "Depósito / Porto Alvo",
        add_items_request: "Adicionar Itens à Ordem",
        item_name_csv_match: "Nome do Item",
        type_search_stock: "Digite para buscar todos os itens do jogo...",
        enter_item_name: "Digite o nome do item...",
        required: "Obrigatório",
        add: "Adicionar",
        added_items_count: "Itens Adicionados",
        no_items_added: "Nenhum item adicionado ainda. Busque e adicione itens acima.",
        cancel: "Cancelar",
        cat_item: "Item",
        cat_crate: "Caixa",
        cat_vehicle: "Veículo",
        cat_structure: "Estrutura",
        enter_target_depot_name: "Digite o nome do depósito alvo...",

        // Toast Messages & Dialog confirmation
        role_officer_required_csv: "Função de Oficial de Logística necessária para importar escaneamentos de inventário.",
        paste_csv_first: "Por favor, cole os dados do CSV primeiro.",
        invalid_csv_format: "Erro: Formato de CSV inválido.",
        csv_missing_items: "Erro: O CSV importado não contém alguns itens padrão.",
        csv_extra_items: "Erro: O CSV importado contém nomes de itens fora da lista padrão.",
        csv_malformed_line: "Erro: O CSV contém linhas malformadas ou ilegíveis.",
        invalid_depot_name: "Erro: Nome do depósito inválido no CSV.",
        invalid_username_format: "Usuário inválido. Apenas letras em inglês, números e sublinhados são permitidos.",
        import_success: "Inventário de {location} importado com sucesso!",
        import_updated: "Inventário de {location} atualizado com sucesso!",
        authorized_access: "Acesso autorizado como {role}.",
        session_terminated: "Sessão encerrada.",
        role_officer_required_sample: "Função de Oficial de Logística necessária para carregar conjuntos de dados de amostra.",
        sample_loaded: "30 depósitos simulados carregados em 10 regiões!",
        clear_db_confirm_title: "LIMPAR BANCO DE DADOS",
        clear_db_confirm_msg: "Tem certeza de que deseja excluir permanentemente todos os depósitos rastreados e limpar o histórico de armazenamento local? Esta ação não pode ser desfeita.",
        clear_db_success: "Todos os depósitos rastreados foram excluídos do banco de dados.",
        clear_logs_confirm_title: "LIMPAR LOGS DE AUDITORIA",
        clear_logs_confirm_msg: "Tem certeza de que deseja excluir permanentemente todo o histórico de logs de auditoria? Esta ação não pode ser desfeita.",
        clear_logs_success: "Histórico de logs de auditoria limpo.",
        clear: "Limpar",
        delete_depot_confirm_title: "EXCLUIR DEPÓSITO",
        delete_depot_confirm_msg: "Tem certeza de que deseja excluir o depósito \"{displayName}\" e todos os seus dados históricos de escaneamento?",
        delete_depot_success: "Entrada do banco de dados do depósito {displayName} excluída.",
        role_officer_required_delete: "Função de Oficial de Logística necessária para excluir depósitos.",
        role_officer_required_settings: "Função de Oficial de Logística necessária para modificar configurações.",
        settings_updated: "Configurações do depósito atualizadas com sucesso.",
        role_officer_required_create_req: "Função de Oficial de Logística necessária para criar solicitações.",
        role_officer_required_reopen: "Função de Oficial de Logística necessária para reabrir solicitações.",
        request_created: "Ordem de produção com {count} itens criada com sucesso.",
        cargo_delivered: "Entrega de carga registrada.",
        item_status_toggled: "Status do item alterado.",
        request_status_updated: "Status da ordem de produção atualizado.",
        request_removed: "Ordem de produção removida.",
        delete_request_confirm_title: "EXCLUIR ORDEM",
        delete_request_confirm_msg: "Tem certeza de que deseja excluir permanentemente esta ordem de produção?",
        back_to_dashboard: "Voltar ao Painel",
        request_not_found: "Ordem não encontrada.",
        item_must_match: "O nome do item deve ser um item de jogo válido (presente no banco de dados do jogo).",
        item_already_added: "Este item já foi adicionado à ordem.",
        qty_must_greater_zero: "A quantidade deve ser maior que zero.",
        no_items_positive_qty: "Erro: Nenhum item com quantidade positiva encontrado. Depósito não importado.",

        // Analytics Modal
        tactical_stock_analysis: "ANÁLISE TÁTICA DE ESTOQUE",
        analytics_desc: "Mudanças de inventário agregadas do banco de dados e métricas de inteligência logística.",
        analytics_maintenance_title: "TRABALHO EM PROGRESSO",
        analytics_maintenance_desc: "O mecanismo de análise tática de estoque está atualmente em desenvolvimento. O acesso será restaurado em breve.",
        analytics_wip_warning: "Esta seção ainda está em desenvolvimento e pode não funcionar totalmente. Por favor, relate quaisquer problemas encontrados na guia de Feedback.",
        select_depot_scope: "Selecionar Escopo do Depósito",
        all_depots_ports_aggregated: "Todos os Depósitos / Portos (Agregados)",
        active_depots: "Depósitos Ativos",
        tactical_storage_nodes: "Nós de armazenamento tático",
        total_supplies_stock: "Total de suprimentos em estoque",
        net_change: "Mudança Líquida",
        overall_qty_shift: "Mudança geral de quantidade",
        shift_dist_item_count: "Distribuição de Mudança (Contagem de Itens)",
        no_changes_detected_dist: "Nenhuma alteração detectada para calcular a distribuição.",
        shifts_label: "MUDANÇAS",
        new_entries: "Novas Entradas",
        top_5_items_change_qty: "Top 5 Itens por Quantidade de Mudança",
        no_changes_detected_logs: "Nenhuma alteração detectada nos logs de inventário.",
        top_depots_shift_volume: "Principais Depósitos por Volume de Mudança",
        no_depot_data_found: "Nenhum dado de depósito encontrado.",
        loading_war_status: "Recuperando inteligência de conquista...",
        shifts_lowercase: "mudanças",
        chart_tab_depleting: "Consumo de Itens (Barra X-Y)",
        chart_tab_trends: "Estoques Regionais (Linha X-Y)",
        search_item_analytics: "Buscar item por nome...",
        chart_title_depleting: "DISTRIBUIÇÃO DE CONSUMO DE ITENS (BARRA X-Y)",
        chart_desc_depleting: "Mostra o esgotamento do estoque (perda) e a quantidade restante do item selecionado nos depósitos.",
        no_data_for_item: "Nenhum dado de esgotamento ou estoque encontrado para \"{item}\" no escopo ativo.",
        depletion_logs_desc: "Lista cronológica de diminuições de estoque, destacando o volume de itens consumidos/retirados.",
        regional_breakdown_desc: "Status do inventário agregado categorizado por região geográfica e classes de itens.",

        // Supply Requests Tab additional
        percent_full: "{percent}% Cheio",
        created_at: "Criado: {time}",
        request_order_num: "Ordem de Produção #{id}",
        reopen_order: "Reabrir Ordem",
        complete_order: "Concluir Ordem",
        reopen_item: "Reabrir Item",
        mark_item_complete: "Marcar Item como Concluído",
        delete_request_order: "Excluir Ordem de Produção",
        status_open: "Aberto",
        status_all: "Todos",
        all_depots: "Todos os Depósitos",
        active_depot_only: "Apenas Depósito Ativo",
        no_matching_requests: "Nenhuma ordem de produção activa encontrada correspondente aos seus filtros.",

        // Crypto & Login
        enter_password: "Digite a Senha de Acesso",
        login_btn: "Entrar",
        invalid_password: "Falha na Autenticação: Falha na descriptografia. Senha incorreta.",
        setup_title: "INICIALIZAÇÃO DE SEGURANÇA",
        setup_desc: "Configure senhas de criptografia seguras para este navegador. Os dados são criptografados localmente usando AES-256.",
        officer_pwd_label: "Definir Senha de Oficial (Acesso Total de Leitura/Gravação)",
        member_pwd_label: "Definir Senha de Membro (Acesso Apenas de Leitura)",
        confirm_pwd_label: "Confirmar Senha",
        pwd_mismatch: "As senhas não coincidem.",
        setup_btn: "Inicializar Banco de Dados Seguro",
        setup_success: "Configuração de segurança concluída. O banco de dados agora está criptografado.",
        reset_data_btn: "Redefinir Senha e Dados",
        reset_data_confirm: "AVISO: Isso excluirá permanentemente todos os dados locais criptografados (depósitos e solicitações) neste dispositivo. Deseja continuar?",
        developer_access: "Autoridade de Desenvolvedor",
        notifications: "NOTIFICAÇÕES",
        no_notifications: "Nenhuma notificação.",
        announcements: "Anúncios",
        audit_logs: "LOGS DE AUDITORIA",
        audit_logs_desc: "Registro cronológico de operações de logística e alterações de estado do banco de dados.",
        developer_portal: "PORTAL DO DESENVOLVEDOR",
        developer_portal_desc: "Aprove novos registros e gerencie as autoridades dos usuários.",
        approve_as_member: "Aprovar como Membro",
        approve_as_officer: "Aprovar como Oficial",
        post_announcement: "Publicar Anúncio",
        announcement_content: "Conteúdo do Anúncio",
        announcement_placeholder: "Digite a mensagem de anúncio global aqui...",
        publish: "Publicar",
        critical_stock_warning: "ALERTA DE ESTOQUE CRÍTICO: a contagem de {itemName} é de {count} unidades em {depotName} (< 50).",
        critical_stock_badge: "CRÍTICO",
        critical_stock_alerts: "Alertas de Estoque Crítico",
        claim_delivery: "Reivindicar Entrega",
        claim_for_self: "Reivindicar para Você Mesmo",
        release_claim: "Liberar Reivindicação",
        claimed_by: "Reivindicado por: {name}",
        claimed_by_you: "Reivindicado por: Você",
        unclaimed: "Não Reivindicado",
        select_delivery_operator: "Selecionar Operador de Entrega",
        select_mock_operator_placeholder: "Selecione um operador ou digite um nome...",
        custom_operator_name: "Nome do Operador Personalizado",
        claim_action: "Reivindicar",
        action: "Ação",
        role: "Função",
        username: "Usuário",
        approvals: "Aprovações",
        users: "Usuários",
        approve: "Aprovar",
        reject: "Rejeitar",
        promote_to_officer: "Promover a Oficial",
        demote_to_member: "Rebaixar a Membro",
        timestamp: "Data e Hora",
        no_audit_logs: "Nenhum log de auditoria disponível.",
        announcement_title: "Título do Anúncio",
        announcement_title_placeholder: "Digite o título do anúncio...",
        severity: "Gravidade",
        severity_normal: "Normal",
        severity_high: "Alta",
        severity_critical: "Crítica",
        seen_by: "Visto por",
        seen_by_tooltip: "Visto por: {users}",
        nobody_seen: "Ninguém viu isso ainda",
        control_deck: "PAINEL DE CONTROLE",
        discord_intel_hub: "Guildas de Logística",
        system_security: "Segurança e Função",
        security_role: "Função de Acesso",
        db_encryption: "Proteção do Banco de Dados",
        theme: "Aparência",
        language: "Idioma",
        theme_dark: "Escuro",
        theme_light: "Claro",
        auth_panel_title: "PAINEL DE ACESSO AUTORIZADO",
        auth_panel_desc: "Faça login no sistema ou crie uma nova solicitação de autorização.",
        auth_login_tab: "Entrar",
        auth_register_tab: "Cadastrar-se",
        auth_username_label: "Nome de Usuário",
        auth_password_label: "Senha",
        auth_username_placeholder: "logislave",
        auth_connecting: "Conectando...",
        auth_send_request: "Enviar Solicitação",
        auth_decrypting: "Descriptografando senha...",
        feedback_bug_report: "Relatório de Erro",
        feedback_feature_idea: "Nova Ideia / Recurso",
        feedback_category_label: "Categoria",
        feedback_status_label: "Status",
        feedback_status_pending: "Pendente",
        feedback_status_in_progress: "Em Progresso",
        feedback_status_completed: "Concluído",
        feedback_delete_confirm: "Tem certeza de que deseja excluir este feedback?",
        feedback_action_progress: "Iniciar Trabalho",
        feedback_action_complete: "Concluir",
        feedback_page_label: "Página",
        crate_vehicles: "Veículos em Caixa",
        cat_crate_vehicle: "Veículo em Caixa",
        csv_capturer: "Capturador CSV",
        click_to_view_content: "Clique para visualizar o conteúdo"
    },
    ru: {
        // App / Header
        logistics_intelligence: "Логистическая информация",
        officer_access: "Права офицера",
        member_access: "Обычные права",
        disconnect: "Выйти",
        tactical_logistics_dashboard: "разработчик docka",

        // CSV Input Panel
        csv_input: "Ввод CSV",
        csv_input_desc_officer: "Вставьте CSV-данные инвентаря Морского порта или Склада снабжения.",
        csv_input_desc_member: "Вставка данных разрешена только офицерам логистики.",
        csv_input_placeholder_officer: "Вставьте CSV-данные сюда...",
        csv_input_placeholder_member: "Для вставки и импорта данных сканирования требуются учетные данные офицера логистики.",
        import_stock: "Импортировать запасы",
        load_sample: "Загрузить пример",

        // Depot Database Panel
        depot_database: "БАЗА ДАННЫХ СКЛАДОВ",
        depot_database_desc: "Доступ и просмотр региональных складов и портов, зарегистрированных в тактической базе данных.",
        browse_depots: "Просмотр складов",
        detailed_analysis: "Детальный анализ",
        clear_all_data: "Очистить все данные",
        select_active_depot: "Выбор активного склада",
        no_depots_imported: "Склады еще не импортированы.",

        // Main Display
        no_active_depot: "Нет активного склада. Пожалуйста, импортируйте CSV для начала работы.",
        location: "Местоположение",
        last_updated: "Последнее обновление",
        edit_settings: "Изменить настройки",
        delete_depot: "Удалить склад",
        supply_request_board: "ТАБЛИЦА ЗАКАЗОВ НА ПРОИЗВОДСТВО",
        supply_request_board_desc: "Координация и отслеживание заказов на производство между активными региональными объектами.",

        // Tabs
        tab_inventory: "Инвентарь",
        tab_cross_search: "Перекрестный поиск",
        tab_supply_requests: "Заказы на производство",

        // Confirm Modal
        confirm_title: "ПОДТВЕРЖДЕНИЕ ДЕЙСТВИЯ",
        confirm_cancel: "Отмена",
        confirm_yes: "Да, подтвердить",

        // Depot Settings Modal
        depot_settings: "НАСТРОЙКИ СКЛАДА",
        depot_settings_desc: "Настройте идентификационное имя склада.",
        custom_identifier_name: "Пользовательское имя идентификатора",
        save_changes: "Сохранить изменения",
        close: "Закрыть",

        // Discord Gate
        tactical_intel_gateway: "Система отслеживания логистики",
        auth_required: "Для отслеживания логистики требуется авторизация. Пожалуйста, выберите вашу роль.",
        role_officer: "Права офицера",
        role_member: "Обычные права",
        role_developer: "Разработчик",
        auth_pending_title: "ОЖИДАНИЕ ОДОБРЕНИЯ",
        auth_pending_desc: "Ваша учетная запись успешно создана. Доступ к системе требует одобрения разработчика логистики. Пожалуйста, свяжитесь с менеджером.",
        auth_rejected_title: "ЗАЯВКА ОТКЛОНЕНА",
        auth_rejected_desc: "Ваш запрос на вход был отклонен администраторами. Несанкционированный доступ заблокирован. Пожалуйста, свяжитесь с менеджером логистики.",
        auth_approved_title: "ЗАЯВКА ОДОБРЕНА",
        auth_approved_desc: "Ваша учетная запись была одобрена администраторами логистики! Теперь вы можете войти в систему.",
        auth_btn_go_back: "Выйти / Назад",
        auth_btn_enter_system: "Войти в систему",
        secure_access: "Безопасный доступ",

        // Inventory Tab
        filter_stock_category: "ФИЛЬТР КАТЕГОРИИ ЗАПАСОВ",
        all_items: "Все предметы",
        crates_only: "Только ящики",
        individual_only: "Только поштучно",
        vehicles: "Техника",
        structures: "Постройки",
        search_item_placeholder: "Поиск предмета по названию...",
        search_user_placeholder: "Поиск пользователя по имени...",
        select_depot: "Выбрать склад",
        total_items: "Всего предметов",
        increased_stock: "Запасы увеличились",
        decreased_stock: "Запасы уменьшились",
        new_items: "Новые предметы",
        unchanged: "Без изменений",
        currently_in_stock: "Сейчас на складе",
        items_higher_qty: "Предметы с увеличением количества",
        items_lower_qty: "Предметы с уменьшением количества",
        newly_added: "Недавно добавлено на склад",
        item_name: "Название предмета",
        category: "Категория",
        previous_qty: "Предыдущее кол-во",
        current_qty: "Текущее кол-во",
        difference: "Разница",
        no_items_match: "Нет предметов, соответствующих активным фильтрам.",
        showing: "Показано с",
        to: "по",
        of: "из",
        entries: "записей",
        previous: "Предыдущий",
        next: "Следующий",
        search_logs_placeholder: "Поиск логов...",

        // Cross Search Tab
        global_search: "ГЛОБАЛЬНЫЙ ПОИСК",
        global_search_desc: "Поиск материала по всем зарегистрированным складам.",
        search_item_name: "Поиск предмета...",
        depot_location: "Местоположение склада",
        quantity: "Количество",
        status: "Статус",
        matches_found_in: "Совпадения найдены в",
        depots_label: "складах.",
        no_matching_supplies: "Совпадающих припасов не найдено ни на одном складе.",
        search_across_all_depots: "Искать по всем складам",
        access_code: "Код доступа",
        access_code_placeholder: "6-значный цифровой код доступа",
        share_code_with_members: "Поделиться кодом доступа с участниками?",
        code_locked_for_members: "Ограничено",
        click_to_reveal: "Нажмите, чтобы показать код доступа",
        validation_6_digits: "Код доступа должен состоять ровно из 6 цифр.",
        remove_code_help: "Оставьте пустым, чтобы удалить пароль",

        // Supply Requests Tab
        active_requests: "Активные запросы",
        completed: "Завершено",
        request_item: "Запрошенный предмет",
        progress: "Прогресс",
        actions: "Действия",
        deliver_cargo: "Доставить груз",
        mark_completed: "Отметить как завершенный",
        undo_completion: "Отменить завершение",
        no_active_supply_requests: "Нет активных заказов на производство.",
        open_request: "Создать заказ",

        // Create Request Modal
        open_supply_request: "СОЗДАТЬ ЗАКАЗ НА ПРОИЗВОДСТВО",
        target_depot_port: "Целевой склад / Порт",
        add_items_request: "Добавить предметы в заказ",
        item_name_csv_match: "Название предмета",
        type_search_stock: "Введите для поиска по всем игровым предметам...",
        enter_item_name: "Введите название предмета...",
        required: "Обязательно",
        add: "Добавить",
        added_items_count: "Добавленные предметы",
        no_items_added: "Предметы еще не добавлены. Найдите и добавьте предметы выше.",
        cancel: "Отмена",
        cat_item: "Предмет",
        cat_crate: "Ящик",
        cat_vehicle: "Техника",
        cat_structure: "Постройка",
        enter_target_depot_name: "Введите название целевого склада...",

        // Toast Messages & Dialog confirmation
        role_officer_required_csv: "Для импорта сканов инвентаря требуется роль офицера логистики.",
        paste_csv_first: "Пожалуйста, сначала вставьте CSV-данные.",
        invalid_csv_format: "Ошибка: Неверный формат CSV.",
        csv_missing_items: "Ошибка: В импортированном CSV отсутствуют некоторые стандартные предметы.",
        csv_extra_items: "Ошибка: В импортированном CSV содержатся предметы вне стандартного списка.",
        csv_malformed_line: "Ошибка: CSV содержит неверно сформированные или нечитаемые строки.",
        invalid_depot_name: "Ошибка: Неверное имя местоположения склада в CSV.",
        invalid_username_format: "Неверное имя пользователя. Разрешены только английские буквы, цифры и подчеркивания.",
        import_success: "Инвентарь {location} успешно импортирован!",
        import_updated: "Инвентарь {location} успешно обновлен!",
        authorized_access: "Авторизован доступ как {role}.",
        session_terminated: "Сессия завершена.",
        role_officer_required_sample: "Для загрузки тестовых наборов данных требуется роль офицера логистики.",
        sample_loaded: "Загружено 30 имитируемых складов в 10 регионах!",
        clear_db_confirm_title: "ОЧИСТИТЬ БАЗУ ДАННЫХ",
        clear_db_confirm_msg: "Вы уверены, что хотите навсегда удалить все отслеживаемые склады и очистить историю локального хранилища? Это действие нельзя отменить.",
        clear_db_success: "Все отслеживаемые склады удалены из базы данных.",
        clear_logs_confirm_title: "ОЧИСТИТЬ ЖУРНАЛЫ АУДИТА",
        clear_logs_confirm_msg: "Вы уверены, что хотите навсегда удалить всю историю журналов аудита? Это действие нельзя отменить.",
        clear_logs_success: "История журналов аудита очищена.",
        clear: "Очистить",
        delete_depot_confirm_title: "УДАЛИТЬ СКЛАД",
        delete_depot_confirm_msg: "Вы уверены, что хотите удалить склад \"{displayName}\" и все его исторические данные сканирования?",
        delete_depot_success: "Запись базы данных склада {displayName} удалена.",
        role_officer_required_delete: "Для удаления складов требуется роль офицера логистики.",
        role_officer_required_settings: "Для изменения настроек требуется роль офицера логистики.",
        settings_updated: "Настройки склада успешно обновлены.",
        role_officer_required_create_req: "Для создания запросов требуется роль офицера логистики.",
        role_officer_required_reopen: "Для повторного открытия запросов требуется роль офицера логистики.",
        request_created: "Заказ на производство с {count} предметами успешно создан.",
        cargo_delivered: "Доставка груза зарегистрирована.",
        item_status_toggled: "Статус предмета изменен.",
        request_status_updated: "Статус заказа на производство обновлен.",
        request_removed: "Заказ на производство удален.",
        delete_request_confirm_title: "УДАЛИТЬ ЗАКАЗ",
        delete_request_confirm_msg: "Вы уверены, что хотите навсегда удалить этот заказ на производство?",
        back_to_dashboard: "Назад к панели управления",
        request_not_found: "Заказ не найден.",
        item_must_match: "Название предмета должно быть допустимым игровым предметом (присутствовать в базе данных игры).",
        item_already_added: "Этот предмет уже добавлен в заказ.",
        qty_must_greater_zero: "Количество должно быть больше нуля.",
        no_items_positive_qty: "Ошибка: Предметы с положительным количеством не найдены. Склад не импортирован.",

        // Analytics Modal
        tactical_stock_analysis: "ТАКТИЧЕСКИЙ АНАЛИЗ ЗАПАСОВ",
        analytics_desc: "Сводные изменения запасов базы данных и метрики логистической информации.",
        analytics_maintenance_title: "В РАЗРАБОТКЕ",
        analytics_maintenance_desc: "Движок тактического анализа запасов в настоящее время находится в разработке. Доступ будет восстановлен в ближайшее время.",
        analytics_wip_warning: "Этот раздел все еще находится в разработке и может работать некорректно. Пожалуйста, сообщайте о любых ошибках через вкладку Обратной связи.",
        select_depot_scope: "Выбрать масштаб склада",
        all_depots_ports_aggregated: "Все склады / Порты (Сводно)",
        active_depots: "Активные склады",
        tactical_storage_nodes: "Тактические узлы хранения",
        total_supplies_stock: "Всего припасов на складе",
        net_change: "Чистое изменение",
        overall_qty_shift: "Общее изменение количества",
        shift_dist_item_count: "Распределение изменений (Кол-во предметов)",
        no_changes_detected_dist: "Изменений для расчета распределения не обнаружено.",
        shifts_label: "ИЗМЕНЕНИЯ",
        new_entries: "Новые записи",
        top_5_items_change_qty: "Топ-5 предметов по объему изменений",
        no_changes_detected_logs: "Изменений в логах инвентаря не обнаружено.",
        top_depots_shift_volume: "Основные склады по объему изменений",
        no_depot_data_found: "Данные о складе не найдены.",
        loading_war_status: "Получение информации о завоевании...",
        shifts_lowercase: "изменения",
        chart_tab_depleting: "Расход предметов (X-Y столбцы)",
        chart_tab_trends: "Региональные запасы (X-Y линия)",
        search_item_analytics: "Поиск предмета по названию...",
        chart_title_depleting: "РАСПРЕДЕЛЕНИЕ РАСХОДА ПРЕДМЕТОВ (X-Y СТОЛБЦЫ)",
        chart_desc_depleting: "Показывает истощение запасов (убыль) и оставшееся количество выбранного предмета на складах.",
        no_data_for_item: "Данных об истощении или запасах для \"{item}\" в активной области не найдено.",
        depletion_logs_desc: "Хронологический список уменьшений запасов, выделяющий объем потребленных/вывезенных предметов.",
        regional_breakdown_desc: "Сводный статус инвентаря, сгруппированный по географическим регионам и классам предметов.",

        // Supply Requests Tab additional
        percent_full: "{percent}% Заполнено",
        created_at: "Создано: {time}",
        request_order_num: "Заказ на производство #{id}",
        reopen_order: "Открыть заказ заново",
        complete_order: "Завершить заказ",
        reopen_item: "Открыть предмет заново",
        mark_item_complete: "Отметить предмет как завершенный",
        delete_request_order: "Удалить заказ на производство",
        status_open: "Открыт",
        status_all: "Все",
        all_depots: "Все склады",
        active_depot_only: "Только активный склад",
        no_matching_requests: "Не найдено активных заказов на производство, соответствующих вашим фильтрам.",

        // Crypto & Login
        enter_password: "Введите пароль доступа",
        login_btn: "Войти",
        invalid_password: "Сбой авторизации: Сбой расшифровки. Неверный пароль.",
        setup_title: "НАСТРОЙКА БЕЗОПАСНОСТИ",
        setup_desc: "Настройте безопасные пароли шифрования для этого браузера. Данные шифруются локально с использованием AES-256.",
        officer_pwd_label: "Установить пароль офицера (Полный доступ на чтение/запись)",
        member_pwd_label: "Установить пароль участника (Доступ только на чтение)",
        confirm_pwd_label: "Подтвердите пароль",
        pwd_mismatch: "Пароли не совпадают.",
        setup_btn: "Инициализировать безопасную БД",
        setup_success: "Настройка безопасности выполнена успешно. База данных теперь зашифрована.",
        reset_data_btn: "Сбросить пароль и данные",
        reset_data_confirm: "ПРЕДУПРЕЖДЕНИЕ: Это навсегда удалит все локальные зашифрованные данные (склады и запросы) на этом устройстве. Продолжить?",
        developer_access: "Права разработчика",
        notifications: "УВЕДОМЛЕНИЯ",
        no_notifications: "Нет уведомлений.",
        announcements: "Объявления",
        audit_logs: "ЖУРНАЛ АУДИТА",
        audit_logs_desc: "Хронологическая запись логистических операций и изменений состояния базы данных.",
        developer_portal: "ПОРТАЛ РАЗРАБОТЧИКА",
        developer_portal_desc: "Одобрение новых регистраций и управление правами пользователей.",
        approve_as_member: "Одобрить как участника",
        approve_as_officer: "Одобрить как офицера",
        post_announcement: "Опубликовать объявление",
        announcement_content: "Содержание объявления",
        announcement_placeholder: "Введите текст глобального объявления здесь...",
        publish: "Опубликовать",
        critical_stock_warning: "КРИТИЧЕСКИЙ УРОВЕНЬ ЗАПАСОВ: Количество {itemName} на складе {depotName} составляет {count} шт. (< 50).",
        critical_stock_badge: "КРИТИЧЕСКИ",
        critical_stock_alerts: "Предупреждения о критических запасах",
        claim_delivery: "Принять доставку",
        claim_for_self: "Принять на себя",
        release_claim: "Отказаться от принятия",
        claimed_by: "Принято: {name}",
        claimed_by_you: "Принято: Вы",
        unclaimed: "Не принято",
        select_delivery_operator: "Выбрать оператора доставки",
        select_mock_operator_placeholder: "Выберите оператора или введите другое имя...",
        custom_operator_name: "Пользовательское имя оператора",
        claim_action: "Принять",
        action: "Действие",
        role: "Роль",
        username: "Имя пользователя",
        approvals: "Одобрения",
        users: "Пользователи",
        approve: "Одобрить",
        reject: "Отклонить",
        promote_to_officer: "Повысить до офицера",
        demote_to_member: "Понизить до участника",
        timestamp: "Время",
        no_audit_logs: "Журналы аудита отсутствуют.",
        announcement_title: "Заголовок объявления",
        announcement_title_placeholder: "Введите заголовок объявления...",
        severity: "Важность",
        severity_normal: "Обычная",
        severity_high: "Высокая",
        severity_critical: "Критическая",
        seen_by: "Просмотрено",
        seen_by_tooltip: "Просмотрели: {users}",
        nobody_seen: "Еще никто не просмотрел",
        control_deck: "ПАНЕЛЬ УПРАВЛЕНИЯ",
        discord_intel_hub: "Логистические гильдии",
        system_security: "Безопасность и роли",
        security_role: "Роль доступа",
        db_encryption: "Защита БД",
        theme: "Внешний вид",
        language: "Язык",
        theme_dark: "Темная",
        theme_light: "Светлая",
        auth_panel_title: "ПАНЕЛЬ АВТОРИЗОВАННОГО ДОСТУПА",
        auth_panel_desc: "Войдите в систему или создайте новый запрос на авторизацию.",
        auth_login_tab: "Войти",
        auth_register_tab: "Регистрация",
        auth_username_label: "Имя пользователя",
        auth_password_label: "Пароль",
        auth_username_placeholder: "logislave",
        auth_connecting: "Подключение...",
        auth_send_request: "Отправить запрос",
        auth_decrypting: "Расшифровка пароля...",
        feedback_bug_report: "Отчет об ошибке",
        feedback_feature_idea: "Новая идея / Предложение",
        feedback_category_label: "Категория",
        feedback_status_label: "Статус",
        feedback_status_pending: "В ожидании",
        feedback_status_in_progress: "В процессе",
        feedback_status_completed: "Завершено",
        feedback_delete_confirm: "Вы уверены, что хотите удалить этот отзыв?",
        feedback_action_progress: "Начать работу",
        feedback_action_complete: "Завершить",
        feedback_page_label: "Страница",
        crate_vehicles: "Техника в ящиках",
        cat_crate_vehicle: "Техника в ящике",
        csv_capturer: "Захватчик CSV",
        click_to_view_content: "Нажмите для просмотра содержимого"
    },
    de: {
        // App / Header
        logistics_intelligence: "Logistik-Informationen",
        officer_access: "Offiziersberechtigung",
        member_access: "Normale Berechtigung",
        disconnect: "Abmelden",
        tactical_logistics_dashboard: "entwickelt von docka",

        // CSV Input Panel
        csv_input: "CSV-Eingabe",
        csv_input_desc_officer: "Fügen Sie die CSV-Inventarkopie des Seehafens oder Lagers ein.",
        csv_input_desc_member: "Einfügefunktion ist auf Logistikoffiziere beschränkt.",
        csv_input_placeholder_officer: "Fügen Sie CSV-Daten hier ein...",
        csv_input_placeholder_member: "Anmeldedaten für Logistikoffiziere erforderlich, um Scandaten einzufügen und zu importieren.",
        import_stock: "Bestand importieren",
        load_sample: "Beispiel laden",

        // Depot Database Panel
        depot_database: "DEPOT-DATENBANK",
        depot_database_desc: "Zugriff und Durchsuchen von regionalen Depots und Häfen, die in der taktischen Datenbank registriert sind.",
        browse_depots: "Depots durchsuchen",
        detailed_analysis: "Detaillierte Analyse",
        clear_all_data: "Alle Daten löschen",
        select_active_depot: "Aktive Depot-Auswahl",
        no_depots_imported: "Noch keine Depots importiert.",

        // Main Display
        no_active_depot: "Kein Depot aktiv. Bitte importieren Sie eine CSV-Datei, um zu beginnen.",
        location: "Standort",
        last_updated: "Zuletzt aktualisiert",
        edit_settings: "Einstellungen bearbeiten",
        delete_depot: "Depot löschen",
        supply_request_board: "PRODUKTIONSAUFTRAGSBOARD",
        supply_request_board_desc: "Koordinieren und verfolgen Sie Produktionsaufträge über die aktiven regionalen Einrichtungen.",

        // Tabs
        tab_inventory: "Inventar",
        tab_cross_search: "Kreuzsuche",
        tab_supply_requests: "Produktionsaufträge",

        // Confirm Modal
        confirm_title: "AKTION BESTÄTIGEN",
        confirm_cancel: "Abbrechen",
        confirm_yes: "Ja, bestätigen",

        // Depot Settings Modal
        depot_settings: "DEPOT-EINSTELLUNGEN",
        depot_settings_desc: "Passen Sie den Depot-Identifikationsnamen an.",
        custom_identifier_name: "Benutzerdefinierter Identifikationsname",
        save_changes: "Änderungen speichern",
        close: "Schließen",

        // Discord Gate
        tactical_intel_gateway: "Logistik-Verfolgungssystem",
        auth_required: "Die Logistik-Verfolgung erfordert eine Autorisierung. Bitte wählen Sie Ihre Rolle.",
        role_officer: "Offiziersberechtigung",
        role_member: "Normale Berechtigung",
        role_developer: "Entwickler",
        auth_pending_title: "GENEHMIGUNG AUSSTEHEND",
        auth_pending_desc: "Ihr Konto wurde erfolgreich erstellt. Der Zugriff auf das System erfordert die Genehmigung des Logistik-Entwicklers. Bitte kontaktieren Sie einen Manager.",
        auth_rejected_title: "ANFRAGE ABGELEHNT",
        auth_rejected_desc: "Ihre Beitrittsanfrage wurde von den Administratoren abgelehnt. Unbefugter Zugriff blockiert. Bitte kontaktieren Sie einen Logistikmanager.",
        auth_approved_title: "ANFRAGE GENEHMIGT",
        auth_approved_desc: "Ihr Konto wurde von den Logistikadministratoren genehmigt! Sie können sich jetzt im System anmelden.",
        auth_btn_go_back: "Abmelden / Zurück",
        auth_btn_enter_system: "Im System anmelden",
        secure_access: "Sicherer Zugriff",

        // Inventory Tab
        filter_stock_category: "BESTANDSKATEGORIE FILTERN",
        all_items: "Alle Gegenstände",
        crates_only: "Nur Kisten",
        individual_only: "Nur Einzelne",
        vehicles: "Fahrzeuge",
        structures: "Strukturen",
        search_item_placeholder: "Gegenstand nach Name suchen...",
        search_user_placeholder: "Benutzer nach Name suchen...",
        select_depot: "Depot auswählen",
        total_items: "Gegenstände insgesamt",
        increased_stock: "Erhöhter Bestand",
        decreased_stock: "Verringerter Bestand",
        new_items: "Neue Gegenstände",
        unchanged: "Unverändert",
        currently_in_stock: "Derzeit auf Lager",
        items_higher_qty: "Gegenstände mit größeren Mengen",
        items_lower_qty: "Gegenstände mit geringeren Mengen",
        newly_added: "Neu zum Depot hinzugefügt",
        item_name: "Gegenstandsname",
        category: "Kategorie",
        previous_qty: "Vorherige Menge",
        current_qty: "Aktuelle Menge",
        difference: "Differenz",
        no_items_match: "Keine Gegenstände entsprechen den aktiven Filtern.",
        showing: "Zeige",
        to: "bis",
        of: "von",
        entries: "Einträgen",
        previous: "Vorherige",
        next: "Nächste",
        search_logs_placeholder: "Protokolle suchen...",

        // Cross Search Tab
        global_search: "GLOBALE SUCHE",
        global_search_desc: "Suchen Sie in allen registrierten Depots nach einem Material.",
        search_item_name: "Gegenstandsname suchen...",
        depot_location: "Depot-Standort",
        quantity: "Menge",
        status: "Status",
        matches_found_in: "Treffer gefunden in",
        depots_label: "Depots.",
        no_matching_supplies: "Keine übereinstimmenden Vorräte in einem Depot gefunden.",
        search_across_all_depots: "In allen Depots suchen",
        access_code: "Zugangscode",
        access_code_placeholder: "6-stelliger numerischer Zugangscode",
        share_code_with_members: "Zugangscode für Mitglieder freigeben?",
        code_locked_for_members: "Eingeschränkt",
        click_to_reveal: "Klicken, um Zugangscode anzuzeigen",
        validation_6_digits: "Der Zugangscode muss genau 6-stellig sein.",
        remove_code_help: "Leer lassen, um Passwort zu entfernen",

        // Supply Requests Tab
        active_requests: "Aktive Anfragen",
        completed: "Abgeschlossen",
        request_item: "Angeforderter Gegenstand",
        progress: "Fortschritt",
        actions: "Aktionen",
        deliver_cargo: "Fracht liefern",
        mark_completed: "Als abgeschlossen markieren",
        undo_completion: "Abschluss rückgängig machen",
        no_active_supply_requests: "Keine aktiven Produktionsaufträge.",
        open_request: "Auftrag erstellen",

        // Create Request Modal
        open_supply_request: "PRODUKTIONSAUFTRAG ERSTELLEN",
        target_depot_port: "Ziel-Depot / Hafen",
        add_items_request: "Gegenstände zum Auftrag hinzufügen",
        item_name_csv_match: "Gegenstandsname",
        type_search_stock: "Tippen, um alle Spielgegenstände zu durchsuchen...",
        enter_item_name: "Gegenstandsname eingeben...",
        required: "Erforderlich",
        add: "Hinzufügen",
        added_items_count: "Hinzugefügte Gegenstände",
        no_items_added: "Noch keine Gegenstände hinzugefügt. Suchen und fügen Sie oben Gegenstände hinzu.",
        cancel: "Abbrechen",
        cat_item: "Gegenstand",
        cat_crate: "Kiste",
        cat_vehicle: "Fahrzeug",
        cat_structure: "Struktur",
        enter_target_depot_name: "Ziel-Depotname eingeben...",

        // Toast Messages & Dialog confirmation
        role_officer_required_csv: "Logistikoffiziersrolle erforderlich, um Inventarscans zu importieren.",
        paste_csv_first: "Bitte fügen Sie zuerst CSV-Daten ein.",
        invalid_csv_format: "Fehler: Ungültiges CSV-Format.",
        csv_missing_items: "Fehler: Importierter CSV fehlen einige Standardgegenstände.",
        csv_extra_items: "Fehler: Importierte CSV enthält Gegenstandsnamen außerhalb der Standardliste.",
        csv_malformed_line: "Fehler: CSV enthält fehlerhafte oder unleserliche Zeilen.",
        invalid_depot_name: "Fehler: Ungültiger Depot-Standortname in der CSV.",
        invalid_username_format: "Ungültiger Benutzername. Nur englische Buchstaben, Zahlen und Unterstriche sind erlaubt.",
        import_success: "Inventar von {location} erfolgreich importiert!",
        import_updated: "Inventar von {location} erfolgreich aktualisiert!",
        authorized_access: "Autorisierter Zugriff als {role}.",
        session_terminated: "Sitzung beendet.",
        role_officer_required_sample: "Logistikoffiziersrolle erforderlich, um Beispieldatensätze zu laden.",
        sample_loaded: "30 simulierte Depots in 10 Regionen geladen!",
        clear_db_confirm_title: "DATENBANK LÖSCHEN",
        clear_db_confirm_msg: "Sind Sie sicher, dass Sie alle verfolgten Depots dauerhaft löschen und den lokalen Speicherverlauf leeren möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
        clear_db_success: "Alle verfolgten Depots aus der Datenbank gelöscht.",
        clear_logs_confirm_title: "AUDIT-PROTOKOLLE LÖSCHEN",
        clear_logs_confirm_msg: "Sind Sie sicher, dass Sie alle Audit-Protokolle dauerhaft löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
        clear_logs_success: "Audit-Protokollverlauf gelöscht.",
        clear: "Löschen",
        delete_depot_confirm_title: "DEPOT LÖSCHEN",
        delete_depot_confirm_msg: "Sind Sie sicher, dass Sie das Depot \"{displayName}\" und alle seine historischen Scandaten löschen möchten?",
        delete_depot_success: "Datenbankeintrag für Depot {displayName} gelöscht.",
        role_officer_required_delete: "Logistikoffiziersrolle erforderlich, um Depots zu löschen.",
        role_officer_required_settings: "Logistikoffiziersrolle erforderlich, um Einstellungen zu ändern.",
        settings_updated: "Depot-Einstellungen erfolgreich aktualisiert.",
        role_officer_required_create_req: "Logistikoffiziersrolle erforderlich, um Anfragen zu erstellen.",
        role_officer_required_reopen: "Logistikoffiziersrolle erforderlich, um Anfragen wieder zu öffnen.",
        request_created: "Produktionsauftrag mit {count} Gegenständen erfolgreich erstellt.",
        cargo_delivered: "Frachtlieferung registriert.",
        item_status_toggled: "Gegenstandsstatus umgeschaltet.",
        request_status_updated: "Status des Produktionsauftrags aktualisiert.",
        request_removed: "Produktionsauftrag entfernt.",
        delete_request_confirm_title: "AUFTRAG LÖSCHEN",
        delete_request_confirm_msg: "Sind Sie sicher, dass Sie diesen Produktionsauftrag dauerhaft löschen möchten?",
        back_to_dashboard: "Zurück zum Dashboard",
        request_not_found: "Auftrag nicht gefunden.",
        item_must_match: "Der Gegenstandsname muss ein gültiger Spielgegenstand sein (in der Spieldatenbank vorhanden).",
        item_already_added: "Dieser Gegenstand wurde bereits zum Auftrag hinzugefügt.",
        qty_must_greater_zero: "Die Menge muss größer als Null sein.",
        no_items_positive_qty: "Fehler: Keine Gegenstände mit positiven Mengen gefunden. Depot nicht importiert.",

        // Analytics Modal
        tactical_stock_analysis: "TAKTIERENDE BESTANDSANALYSE",
        analytics_desc: "Aggregierte Verschiebungen des Datenbankinventars und Logistik-Informationen.",
        analytics_maintenance_title: "IN ARBEIT",
        analytics_maintenance_desc: "Die Engine für taktische Bestandsanalysen wird derzeit entwickelt. Der Zugriff wird in Kürze wiederhergestellt.",
        analytics_wip_warning: "Dieser Bereich befindet sich noch in der Entwicklung und funktioniert möglicherweise nicht vollständig. Bitte melden Sie eventuelle Fehler über die Registerkarte Feedback.",
        select_depot_scope: "Depot-Bereich auswählen",
        all_depots_ports_aggregated: "Alle Depots / Häfen (Aggregiert)",
        active_depots: "Aktive Depots",
        tactical_storage_nodes: "Taktische Lagerknoten",
        total_supplies_stock: "Gesamte Vorräte auf Lager",
        net_change: "Nettoänderung",
        overall_qty_shift: "Gesamte Mengenverschiebung",
        shift_dist_item_count: "Verschiebungsverteilung (Gegenstandsanzahl)",
        no_changes_detected_dist: "Keine Änderungen erkannt, um die Verteilung zu berechnen.",
        shifts_label: "VERSCHIEBUNGEN",
        new_entries: "Neue Einträge",
        top_5_items_change_qty: "Top 5 Gegenstände nach Mengenänderung",
        no_changes_detected_logs: "Keine Änderungen in den Inventarprotokollen erkannt.",
        top_depots_shift_volume: "Top-Depots nach Verschiebungsvolumen",
        no_depot_data_found: "Keine Depotdaten gefunden.",
        loading_war_status: "Eroberungs-Informationen werden abgerufen...",
        shifts_lowercase: "verschiebungen",
        chart_tab_depleting: "Gegenstandsverbrauch (X-Y Balken)",
        chart_tab_trends: "Regionale Bestände (X-Y Linie)",
        search_item_analytics: "Gegenstand nach Name suchen...",
        chart_title_depleting: "VERTEILUNG DES GEGENSTANDSVERBRAUCHS (X-Y BALKEN)",
        chart_desc_depleting: "Zeigt den Bestandsabbau (Verlust) und die verbleibende Menge des ausgewählten Gegenstands in den Depots.",
        no_data_for_item: "Keine Abbau- oder Bestandsdaten für \"{item}\" im aktiven Bereich gefunden.",
        depletion_logs_desc: "Chronologische Liste der Bestandsabnahmen, die das Volume der verbrauchten/entnommenen Gegenstände hervorhebt.",
        regional_breakdown_desc: "Aggregierter Inventarstatus, kategorisiert nach geografischer Region und Gegenstandsklassen.",

        // Supply Requests Tab additional
        percent_full: "{percent}% Voll",
        created_at: "Erstellt: {time}",
        request_order_num: "Produktionsauftrag #{id}",
        reopen_order: "Auftrag wieder öffnen",
        complete_order: "Auftrag abschließen",
        reopen_item: "Gegenstand wieder öffnen",
        mark_item_complete: "Gegenstand als abgeschlossen markieren",
        delete_request_order: "Produktionsauftrag löschen",
        status_open: "Offen",
        status_all: "Alle",
        all_depots: "Alle Depots",
        active_depot_only: "Nur aktives Depot",
        no_matching_requests: "Keine aktiven Produktionsaufträge gefunden, die Ihren Filtern entsprechen.",

        // Crypto & Login
        enter_password: "Zugangspasswort eingeben",
        login_btn: "Anmelden",
        invalid_password: "Authentifizierung fehlgeschlagen: Entschlüsselung fehlgeschlagen. Falsches Passwort.",
        setup_title: "SICHERHEITSINITIALISIERUNG",
        setup_desc: "Konfigurieren Sie sichere Verschlüsselungspasswörter für diesen Browser. Die Daten werden lokal mit AES-256 verschlüsselt.",
        officer_pwd_label: "Offizierspasswort festlegen (Vollständiger Lese-/Schreibzugriff)",
        member_pwd_label: "Mitgliedspasswort festlegen (Nur Lesezugriff)",
        confirm_pwd_label: "Passwort bestätigen",
        pwd_mismatch: "Passwörter stimmen nicht überein.",
        setup_btn: "Sichere Datenbank initialisieren",
        setup_success: "Sicherheitskonfiguration erfolgreich. Datenbank ist jetzt verschlüsselt.",
        reset_data_btn: "Passwort & Daten zurücksetzen",
        reset_data_confirm: "WARNUNG: Dadurch werden alle lokalen verschlüsselten Daten (Depots und Anfragen) auf diesem Gerät dauerhaft gelöscht. Möchten Sie fortfahren?",
        developer_access: "Entwicklerberechtigung",
        notifications: "BENACHRICHTIGUNGEN",
        no_notifications: "Keine Benachrichtigungen.",
        announcements: "Ankündigungen",
        audit_logs: "AUDIT-PROTOKOLLE",
        audit_logs_desc: "Chronologische Aufzeichnung von Logistikoperationen und Änderungen des Datenbankstatus.",
        developer_portal: "ENTWICKLERPORTAL",
        developer_portal_desc: "Genehmigen Sie neue Registrierungen und verwalten Sie Benutzerberechtigungen.",
        approve_as_member: "Als Mitglied genehmigen",
        approve_as_officer: "Als Offizier genehmigen",
        post_announcement: "Ankündigung veröffentlichen",
        announcement_content: "Ankündigunginhalt",
        announcement_placeholder: "Geben Sie hier die globale Ankündigungsnachricht ein...",
        publish: "Veröffentlichen",
        critical_stock_warning: "WARNUNG VOR KRITISCHEM BESTAND: Die Anzahl von {itemName} in {depotName} beträgt {count} Einheiten (< 50).",
        critical_stock_badge: "KRITISCH",
        critical_stock_alerts: "Warnungen vor kritischem Bestand",
        claim_delivery: "Lieferung beanspruchen",
        claim_for_self: "Für sich selbst beanspruchen",
        release_claim: "Anspruch freigeben",
        claimed_by: "Beansprucht von: {name}",
        claimed_by_you: "Beansprucht von: Ihnen",
        unclaimed: "Nicht beansprucht",
        select_delivery_operator: "Lieferant auswählen",
        select_mock_operator_placeholder: "Wählen Sie einen Lieferanten aus oder geben Sie einen Namen ein...",
        custom_operator_name: "Benutzerdefinierter Lieferantenname",
        claim_action: "Beanspruchen",
        action: "Aktion",
        role: "Rolle",
        username: "Benutzername",
        approvals: "Genehmigungen",
        users: "Benutzer",
        approve: "Genehmigen",
        reject: "Ablehnen",
        promote_to_officer: "Zum Offizier befördern",
        demote_to_member: "Zum Mitglied zurückstufen",
        timestamp: "Zeitstempel",
        no_audit_logs: "Keine Audit-Protokolle verfügbar.",
        announcement_title: "Ankündigungstitel",
        announcement_title_placeholder: "Geben Sie den Ankündigungstitel ein...",
        severity: "Dringlichkeit",
        severity_normal: "Normal",
        severity_high: "Hoch",
        severity_critical: "Kritisch",
        seen_by: "Gesehen von",
        seen_by_tooltip: "Gesehen von: {users}",
        nobody_seen: "Noch niemand hat dies gesehen",
        control_deck: "KONTROLLDECK",
        discord_intel_hub: "Logistikgilden",
        system_security: "Sicherheit & Rolle",
        security_role: "Zugriffsrolle",
        db_encryption: "Datenbankschutz",
        theme: "Aussehen",
        language: "Sprache",
        theme_dark: "Dunkel",
        theme_light: "Hell",
        auth_panel_title: "AUTORISIERTER ZUGRIFFSBEREICH",
        auth_panel_desc: "Melden Sie sich im System an oder erstellen Sie eine neue Autorisierungsanfrage.",
        auth_login_tab: "Anmelden",
        auth_register_tab: "Registrieren",
        auth_username_label: "Benutzername",
        auth_password_label: "Passwort",
        auth_username_placeholder: "logislave",
        auth_connecting: "Verbinde...",
        auth_send_request: "Anfrage senden",
        auth_decrypting: "Passwort entschlüsseln...",
        feedback_bug_report: "Fehlerbericht",
        feedback_feature_idea: "Neue Idee / Funktion",
        feedback_category_label: "Kategorie",
        feedback_status_label: "Status",
        feedback_status_pending: "Ausstehend",
        feedback_status_in_progress: "In Arbeit",
        feedback_status_completed: "Abgeschlossen",
        feedback_delete_confirm: "Sind Sie sicher, dass Sie dieses Feedback löschen möchten?",
        feedback_action_progress: "Arbeit beginnen",
        feedback_action_complete: "Abschließen",
        feedback_page_label: "Seite",
        crate_vehicles: "Kistenfahrzeuge",
        cat_crate_vehicle: "Kistenfahrzeug",
        csv_capturer: "CSV-Erfasser",
        click_to_view_content: "Klicken, um den Inhalt anzuzeigen"
    }
};
