// Auto-generated standard in-game display names & crate variants synced with catalog.json
export const STANDARD_ITEMS = new Set<string>([
  ".44",
  ".44 (Crate)",
  "00MS “Stinger”",
  "00MS “Stinger” (Crate)",
  "03MM “Caster”",
  "03MM “Caster” (Crate)",
  "12.7mm",
  "12.7mm (Crate)",
  "120-68 “Koronides” Field Gun",
  "120-68 “Koronides” Field Gun (Crate)",
  "120mm",
  "120mm (Crate)",
  "14.5mm",
  "14.5mm (Crate)",
  "150mm",
  "150mm (Crate)",
  "20mm",
  "20mm (Crate)",
  "228 Satterley Heavy Storm Rifle",
  "228 Satterley Heavy Storm Rifle (Crate)",
  "250mm \"Fury\" Shell",
  "250mm \"Fury\" Shell (Crate)",
  "250mm \"Purity\" Shell",
  "250mm \"Purity\" Shell (Crate)",
  "30-250 “Tisiphone” Field Cannon",
  "30-250 “Tisiphone” Field Cannon (Crate)",
  "300mm",
  "300mm (Crate)",
  "30mm",
  "30mm (Crate)",
  "3C-High Explosive Rocket",
  "3C-High Explosive Rocket (Crate)",
  "40-250 “Alekto” Heavy Cannon",
  "40-250 “Alekto” Heavy Cannon (Crate)",
  "40-45 “Smelter”",
  "40-45 “Smelter” (Crate)",
  "40mm",
  "40mm (Crate)",
  "4C-Fire Rocket",
  "4C-Fire Rocket (Crate)",
  "50-500 “Thunderbolt” Cannon",
  "50-500 “Thunderbolt” Cannon (Crate)",
  "68A-4 Ronan Fathomer",
  "68A-4 Ronan Fathomer (Crate)",
  "68mm",
  "68mm (Crate)",
  "7.62mm",
  "7.62mm (Crate)",
  "7.92mm",
  "7.92mm (Crate)",
  "74b-1 Ronan Gunship",
  "74b-1 Ronan Gunship (Crate)",
  "75mm",
  "75mm (Crate)",
  "81f-f Ronan Blackguard",
  "81f-f Ronan Blackguard (Crate)",
  "85K-a “Spatha”",
  "85K-a “Spatha” (Crate)",
  "85K-b “Falchion”",
  "85K-b “Falchion” (Crate)",
  "85V-g \"Talos\"",
  "85V-g \"Talos\" (Crate)",
  "86K-a “Bardiche”",
  "86K-a “Bardiche” (Crate)",
  "86K-c “Ranseur”",
  "86K-c “Ranseur” (Crate)",
  "8mm",
  "8mm (Crate)",
  "90T-v “Nemesis”",
  "90T-v “Nemesis” (Crate)",
  "912 Shrike Rounds",
  "912 Shrike Rounds (Crate)",
  "94.5mm",
  "94.5mm (Crate)",
  "945g “Stygian Bolt”",
  "945g “Stygian Bolt” (Crate)",
  "950-70b Anti-Aircraft Shell",
  "950-70b Anti-Aircraft Shell (Crate)",
  "9mm",
  "9mm (Crate)",
  "A0E-9 Rocket Body",
  "A0E-9 Rocket Body (Crate)",
  "A0E-9 Rocket Booster",
  "A0E-9 Rocket Booster (Crate)",
  "A0E-9 Rocket Warhead",
  "A0E-9 Rocket Warhead (Crate)",
  "A3 Harpa Fragmentation Grenade",
  "A3 Harpa Fragmentation Grenade (Crate)",
  "A51 Venti “Daedalus”",
  "A51 Venti “Daedalus” (Crate)",
  "AA-2 \"Battering Ram\"",
  "AA-2 \"Battering Ram\" (Crate)",
  "AB-11 “Doru”",
  "AB-11 “Doru” (Crate)",
  "AB-8 “Acheron”",
  "AB-8 “Acheron” (Crate)",
  "AP/RPG",
  "AP/RPG (Crate)",
  "ARC/RPG",
  "ARC/RPG (Crate)",
  "AU-A150 Taurine Rigger",
  "AU-A150 Taurine Rigger (Crate)",
  "Aalto Storm Rifle 24",
  "Aalto Storm Rifle 24 (Crate)",
  "Abisme AT-99 Mine",
  "Abisme AT-99 Mine (Crate)",
  "Ahti Model 2",
  "Ahti Model 2 (Crate)",
  "Air Raid Siren",
  "Aircraft Radar Parts",
  "Aircraft Radar Parts (Crate)",
  "Alligator Charge",
  "Alligator Charge (Crate)",
  "Aluminum",
  "Aluminum (Crate)",
  "Aluminum Alloy",
  "Aluminum Alloy (Crate)",
  "Anti-Tank Sticky Bomb",
  "Anti-Tank Sticky Bomb (Crate)",
  "Argenti r.II Rifle",
  "Argenti r.II Rifle (Crate)",
  "Assembly Materials I",
  "Assembly Materials I (Crate)",
  "Assembly Materials II",
  "Assembly Materials II (Crate)",
  "Assembly Materials III",
  "Assembly Materials III (Crate)",
  "Assembly Materials IV",
  "Assembly Materials IV (Crate)",
  "Assembly Materials V",
  "Assembly Materials V (Crate)",
  "Auster’s Harness",
  "Auster’s Harness (Crate)",
  "Aviator’s Raiment",
  "Aviator’s Raiment (Crate)",
  "B2 Varsi Anti-Tank Grenade",
  "B2 Varsi Anti-Tank Grenade (Crate)",
  "BF5 White Ash Flask Grenade",
  "BF5 White Ash Flask Grenade (Crate)",
  "BMS - Aquatipper",
  "BMS - Aquatipper (Crate)",
  "BMS - Class 2 Mobile Auto-Crane",
  "BMS - Class 2 Mobile Auto-Crane (Crate)",
  "BMS - Fabricator",
  "BMS - Fabricator (Crate)",
  "BMS - Ironship",
  "BMS - Ironship (Crate)",
  "BMS - Packmule Flatbed",
  "BMS - Packmule Flatbed (Crate)",
  "BMS - Scrap Hauler",
  "BMS - Scrap Hauler (Crate)",
  "BMS - Universal Assembly Rig",
  "BMS - Universal Assembly Rig (Crate)",
  "Balfour Falconer 250mm",
  "Balfour Falconer 250mm (Crate)",
  "Balfour Rampart 68mm",
  "Balfour Rampart 68mm (Crate)",
  "Balfour Stockade 75mm",
  "Balfour Stockade 75mm (Crate)",
  "Balfour Wolfhound 40mm",
  "Balfour Wolfhound 40mm (Crate)",
  "Bandages",
  "Bandages (Crate)",
  "Bane 45",
  "Bane 45 (Crate)",
  "Barbed Wire",
  "Barbed Wire (Crate)",
  "Basic Materials",
  "Basic Materials (Crate)",
  "Bellweather by VAC",
  "Bellweather by VAC (Crate)",
  "Binoculars",
  "Binoculars (Crate)",
  "Blakerow 871",
  "Blakerow 871 (Crate)",
  "Blood Plasma",
  "Blood Plasma (Crate)",
  "Bomastone Grenade",
  "Bomastone Grenade (Crate)",
  "Bonesaw MK.3",
  "Bonesaw MK.3 (Crate)",
  "Booker Greyhound Model 910",
  "Booker Greyhound Model 910 (Crate)",
  "Booker Storm Rifle Model 838",
  "Booker Storm Rifle Model 838 (Crate)",
  "Buckhorn CCQ-18",
  "Buckhorn CCQ-18 (Crate)",
  "Buckshot",
  "Buckshot (Crate)",
  "Caoivish Parka",
  "Caoivish Parka (Crate)",
  "Carnyx Anti-Tank Rocket Launcher",
  "Carnyx Anti-Tank Rocket Launcher (Crate)",
  "Cascadier 873",
  "Cascadier 873 (Crate)",
  "Catara mo.II",
  "Catara mo.II (Crate)",
  "Catena rt.IV Auto-Rifle",
  "Catena rt.IV Auto-Rifle (Crate)",
  "Clancy Cinder M3",
  "Clancy Cinder M3 (Crate)",
  "Clancy-Raca M4",
  "Clancy-Raca M4 (Crate)",
  "Cloudrunner’s Vesture",
  "Cloudrunner’s Vesture (Crate)",
  "Cnute Cliffwrest",
  "Cnute Cliffwrest (Crate)",
  "Coal",
  "Coal (Crate)",
  "Coke",
  "Coke (Crate)",
  "Collins Cannon 68mm",
  "Collins Cannon 68mm (Crate)",
  "Colonial Aircraft Engine (Large)",
  "Colonial Aircraft Engine (Large) (Crate)",
  "Colonial Aircraft Engine (Small)",
  "Colonial Aircraft Engine (Small) (Crate)",
  "Colonial Aircraft Mechanical Parts (Large)",
  "Colonial Aircraft Mechanical Parts (Large) (Crate)",
  "Colonial Aircraft Mechanical Parts (Small)",
  "Colonial Aircraft Mechanical Parts (Small) (Crate)",
  "Cometa T2-9",
  "Cometa T2-9 (Crate)",
  "Components",
  "Components (Crate)",
  "Concrete Materials",
  "Concrete Materials (Crate)",
  "Concrete Mixer",
  "Concrete Mixer (Crate)",
  "Construction Equipment",
  "Construction Equipment (Crate)",
  "Construction Materials",
  "Construction Materials (Crate)",
  "Construction Parts",
  "Construction Parts (Crate)",
  "Copper",
  "Copper (Crate)",
  "Copper Alloy",
  "Copper Alloy (Crate)",
  "Cremari Mortar",
  "Cremari Mortar (Crate)",
  "Critically Wounded Soldier",
  "Critically Wounded Soldier (Crate)",
  "Crow’s Foot Mine",
  "Crow’s Foot Mine (Crate)",
  "Cutler Foebreaker",
  "Cutler Foebreaker (Crate)",
  "Cutler Launcher 4",
  "Cutler Launcher 4 (Crate)",
  "DAE 1b-2 “Serra”",
  "DAE 1b-2 “Serra” (Crate)",
  "DAE 1o-3 “Polybolos”",
  "DAE 1o-3 “Polybolos” (Crate)",
  "DAE 2a-1 “Ruptura”",
  "DAE 2a-1 “Ruptura” (Crate)",
  "DAE 3b-2 “Hades’ Net”",
  "DAE 3b-2 “Hades’ Net” (Crate)",
  "DAE 5b “Zeal”",
  "DAE 5b “Zeal” (Crate)",
  "Damaged Colonial Aircraft Engine (Large)",
  "Damaged Colonial Aircraft Engine (Large) (Crate)",
  "Damaged Colonial Aircraft Engine (Small)",
  "Damaged Colonial Aircraft Engine (Small) (Crate)",
  "Damaged Colonial Aircraft Mechanical Parts (Large)",
  "Damaged Colonial Aircraft Mechanical Parts (Large) (Crate)",
  "Damaged Colonial Aircraft Mechanical Parts (Small)",
  "Damaged Colonial Aircraft Mechanical Parts (Small) (Crate)",
  "Damaged Components",
  "Damaged Components (Crate)",
  "Damaged Warden Aircraft Engine (Large)",
  "Damaged Warden Aircraft Engine (Large) (Crate)",
  "Damaged Warden Aircraft Engine (Small)",
  "Damaged Warden Aircraft Engine (Small) (Crate)",
  "Damaged Warden Aircraft Mechanical Parts (Large)",
  "Damaged Warden Aircraft Mechanical Parts (Large) (Crate)",
  "Damaged Warden Aircraft Mechanical Parts (Small)",
  "Damaged Warden Aircraft Mechanical Parts (Small) (Crate)",
  "Das Krokodil by VAC",
  "Das Krokodil by VAC (Crate)",
  "Daucus isg.III",
  "Daucus isg.III (Crate)",
  "Devitt Ironhide Mk. IV",
  "Devitt Ironhide Mk. IV (Crate)",
  "Devitt Mk. III",
  "Devitt Mk. III (Crate)",
  "Devitt-Caine Mk. IV MMR",
  "Devitt-Caine Mk. IV MMR (Crate)",
  "Diesel",
  "Diesel (Crate)",
  "Drummond 100a",
  "Drummond 100a (Crate)",
  "Drummond Loscann 55c",
  "Drummond Loscann 55c (Crate)",
  "Drummond Spitfire 100d",
  "Drummond Spitfire 100d (Crate)",
  "Duncan’s Coin 14.5mm",
  "Duncan’s Coin 14.5mm (Crate)",
  "Dunne Caravaner 2f",
  "Dunne Caravaner 2f (Crate)",
  "Dunne Dousing Engine 3r",
  "Dunne Dousing Engine 3r (Crate)",
  "Dunne Fuelrunner 2d",
  "Dunne Fuelrunner 2d (Crate)",
  "Dunne Landrunner 12c",
  "Dunne Landrunner 12c (Crate)",
  "Dunne Leatherback 2a",
  "Dunne Leatherback 2a (Crate)",
  "Dunne Loadlugger 3c",
  "Dunne Loadlugger 3c (Crate)",
  "Dunne Responder 3e",
  "Dunne Responder 3e (Crate)",
  "Dunne Transport",
  "Dunne Transport (Crate)",
  "E680-S Rudder Lock",
  "E680-S Rudder Lock (Crate)",
  "E681-B Hullbreaker Mine",
  "E681-B Hullbreaker Mine (Crate)",
  "Eleos Infantry Dagger",
  "Eleos Infantry Dagger (Crate)",
  "Enriched Oil",
  "Enriched Oil (Crate)",
  "Explosive Powder",
  "Explosive Powder (Crate)",
  "Fabri Rucksack",
  "Fabri Rucksack (Crate)",
  "Falias Raiding Club",
  "Falias Raiding Club (Crate)",
  "Ferro 879",
  "Ferro 879 (Crate)",
  "Fiddler Submachine Gun Model 868",
  "Fiddler Submachine Gun Model 868 (Crate)",
  "First Aid Kit",
  "First Aid Kit (Crate)",
  "Flame Ammo",
  "Flame Ammo (Crate)",
  "Flare Mortar Shell",
  "Flare Mortar Shell (Crate)",
  "Flight Mask",
  "Fuscina pi.I",
  "Fuscina pi.I (Crate)",
  "G40 “Sagittarii”",
  "G40 “Sagittarii” (Crate)",
  "GA6 “Cestus”",
  "GA6 “Cestus” (Crate)",
  "Gallagher Brigand Mk. I",
  "Gallagher Brigand Mk. I (Crate)",
  "Gallagher Highwayman Mk. III",
  "Gallagher Highwayman Mk. III (Crate)",
  "Gallagher Outlaw Mk. II",
  "Gallagher Outlaw Mk. II (Crate)",
  "Gallagher Thornfall Mk. VI",
  "Gallagher Thornfall Mk. VI (Crate)",
  "Gas Mask",
  "Gas Mask (Crate)",
  "Gas Mask Filter",
  "Gas Mask Filter (Crate)",
  "Gentleman’s Peacoat",
  "Gentleman’s Peacoat (Crate)",
  "Gravel",
  "Gravel (Crate)",
  "Green Ash Grenade",
  "Green Ash Grenade (Crate)",
  "Grenadier’s Baldric",
  "Grenadier’s Baldric (Crate)",
  "Gunner’s Breastplate",
  "Gunner’s Breastplate (Crate)",
  "H-10 “Pelekys”",
  "H-10 “Pelekys” (Crate)",
  "H-19 “Vulcan”",
  "H-19 “Vulcan” (Crate)",
  "H-5 \"Hatchet\"",
  "H-5 \"Hatchet\" (Crate)",
  "H-8 “Kranesca”",
  "H-8 “Kranesca” (Crate)",
  "HC-2 “Scorpion”",
  "HC-2 “Scorpion” (Crate)",
  "HC-7 \"Ballista\"",
  "HC-7 \"Ballista\" (Crate)",
  "HH-a “Javelin”",
  "HH-a “Javelin” (Crate)",
  "HH-b “Hoplite”",
  "HH-b “Hoplite” (Crate)",
  "HH-d “Peltast”",
  "HH-d “Peltast” (Crate)",
  "Hammer",
  "Hammer (Crate)",
  "Havoc Charge",
  "Havoc Charge (Crate)",
  "Havoc Charge Detonator",
  "Havoc Charge Detonator (Crate)",
  "Heavy Explosive Powder",
  "Heavy Explosive Powder (Crate)",
  "Heavy Oil",
  "Heavy Oil (Crate)",
  "Heavy Topcoat",
  "Heavy Topcoat (Crate)",
  "Huber Exalt 150mm",
  "Huber Exalt 150mm (Crate)",
  "Huber Lariat 120mm",
  "Huber Lariat 120mm (Crate)",
  "Huber Starbreaker 94.5mm",
  "Huber Starbreaker 94.5mm (Crate)",
  "Hydra’s Whisper",
  "Hydra’s Whisper (Crate)",
  "Ignifist 30",
  "Ignifist 30 (Crate)",
  "Incendiary Mortar Shell",
  "Incendiary Mortar Shell (Crate)",
  "Infantry Battledress",
  "Infantry Battledress (Crate)",
  "Intelligence Center Parts",
  "Intelligence Center Parts (Crate)",
  "Iron",
  "Iron (Crate)",
  "Iron Alloy",
  "Iron Alloy (Crate)",
  "K-81e “Sombre”",
  "K-81e “Sombre” (Crate)",
  "KLG901-2 Lunaire F",
  "KLG901-2 Lunaire F (Crate)",
  "KRF1-750 Dragonfly",
  "KRF1-750 Dragonfly (Crate)",
  "KRN886-127 Gast Machine Gun",
  "KRN886-127 Gast Machine Gun (Crate)",
  "KRR2-790 Omen",
  "KRR2-790 Omen (Crate)",
  "KRR3-792 Auger",
  "KRR3-792 Auger (Crate)",
  "King Gallant Mk. II",
  "King Gallant Mk. II (Crate)",
  "King Jester Mk. I-1",
  "King Jester Mk. I-1 (Crate)",
  "King Spire Mk. I",
  "King Spire Mk. I (Crate)",
  "Kivela Power Wheel 80-1",
  "Kivela Power Wheel 80-1 (Crate)",
  "Lamentum mm.IV",
  "Lamentum mm.IV (Crate)",
  "Leary AA-70 Bolas",
  "Leary AA-70 Bolas (Crate)",
  "Leary Shellbore 68mm",
  "Leary Shellbore 68mm (Crate)",
  "Leary Snare Trap 20",
  "Leary Snare Trap 20 (Crate)",
  "Legion Vexillum",
  "Legion Vexillum (Crate)",
  "Legionary Fatigues",
  "Legionary Fatigues (Crate)",
  "Legionary’s Oilcoat",
  "Legionary’s Oilcoat (Crate)",
  "Liaison Transmitter",
  "Liaison Transmitter (Crate)",
  "Liquid Container",
  "Liquid Container (Crate)",
  "Listening Kit",
  "Listening Kit (Crate)",
  "Lodesman’s Lorica",
  "Lodesman’s Lorica (Crate)",
  "Luminary Mk. II Harbinger",
  "Luminary Mk. II Harbinger (Crate)",
  "Luminary Mk. IV Herald",
  "Luminary Mk. IV Herald (Crate)",
  "M925 Austringer Man-O-War",
  "M925 Austringer Man-O-War (Crate)",
  "Maintenance Supplies",
  "Maintenance Supplies (Crate)",
  "Malone MK.2",
  "Malone MK.2 (Crate)",
  "Malone Ratcatcher MK.1",
  "Malone Ratcatcher MK.1 (Crate)",
  "Mammon 91-b",
  "Mammon 91-b (Crate)",
  "Mark II Raidbreaker",
  "Mark II Raidbreaker (Crate)",
  "Material Pallet",
  "Material Pallet (Crate)",
  "Medic Fatigues",
  "Medic Fatigues (Crate)",
  "Mergo-4 “Myrmidon”",
  "Mergo-4 “Myrmidon” (Crate)",
  "Metal Beam",
  "Metal Beam (Crate)",
  "Model-7 “Evie”",
  "Model-7 “Evie” (Crate)",
  "Moray Torpedo",
  "Moray Torpedo (Crate)",
  "Mortar Shell",
  "Mortar Shell (Crate)",
  "Mounted Bonesaw MK.3",
  "Mounted Bonesaw MK.3 (Crate)",
  "Mounted Fissura gd.I",
  "Mounted Fissura gd.I (Crate)",
  "Mulloy LPC",
  "Mulloy LPC (Crate)",
  "Naval Buoy",
  "Naval Hull Segments",
  "Naval Hull Segments (Crate)",
  "Naval Shell Plating",
  "Naval Shell Plating (Crate)",
  "Naval Turbine Components",
  "Naval Turbine Components (Crate)",
  "Neville Anti-Tank Rifle",
  "Neville Anti-Tank Rifle (Crate)",
  "Niska Mk. I Gun Motor Carriage",
  "Niska Mk. I Gun Motor Carriage (Crate)",
  "Niska Mk. II Blinder",
  "Niska Mk. II Blinder (Crate)",
  "Niska Mk. III Scar Twin",
  "Niska Mk. III Scar Twin (Crate)",
  "Niska-Rycker Mk. IX Skycaller",
  "Niska-Rycker Mk. IX Skycaller (Crate)",
  "No.1 “The Liar” Submachinegun",
  "No.1 “The Liar” Submachinegun (Crate)",
  "No.2 Loughcaster",
  "No.2 Loughcaster (Crate)",
  "No.2B Hawthorne",
  "No.2B Hawthorne (Crate)",
  "No.4 The Pillory Scattergun",
  "No.4 The Pillory Scattergun (Crate)",
  "Noble Firebrand Mk. XVII",
  "Noble Firebrand Mk. XVII (Crate)",
  "Noble Widow MK. XIV",
  "Noble Widow MK. XIV (Crate)",
  "Officer’s Regalia",
  "Officer’s Regalia (Crate)",
  "Officialis’ Attire",
  "Officialis’ Attire (Crate)",
  "Oil",
  "Oil (Crate)",
  "Outrider’s Mantle",
  "Outrider’s Mantle (Crate)",
  "O’Brien V.101 Freeman",
  "O’Brien V.101 Freeman (Crate)",
  "O’Brien V.110",
  "O’Brien V.110 (Crate)",
  "O’Brien V.113 Gravekeeper",
  "O’Brien V.113 Gravekeeper (Crate)",
  "O’Brien V.121 Highlander",
  "O’Brien V.121 Highlander (Crate)",
  "O’Brien V.130 Wild Jack",
  "O’Brien V.130 Wild Jack (Crate)",
  "O’Brien V.190 Knave",
  "O’Brien V.190 Knave (Crate)",
  "O’Brien v.200 Squire",
  "O’Brien v.200 Squire (Crate)",
  "PT-815 Smoke Grenade",
  "PT-815 Smoke Grenade (Crate)",
  "Padded Boiler Suit",
  "Padded Boiler Suit (Crate)",
  "Paratrooper’s Ruck",
  "Paratrooper’s Ruck (Crate)",
  "Petrol",
  "Petrol (Crate)",
  "Physician’s Jacket",
  "Physician’s Jacket (Crate)",
  "Pipe",
  "Pipe (Crate)",
  "Processed Construction Materials",
  "Processed Construction Materials (Crate)",
  "Quillback Torpedo",
  "Quillback Torpedo (Crate)",
  "R-1 Hauler",
  "R-1 Hauler (Crate)",
  "R-12 - “Salus” Ambulance",
  "R-12 - “Salus” Ambulance (Crate)",
  "R-12b - “Salva” Flame Truck",
  "R-12b - “Salva” Flame Truck (Crate)",
  "R-15 - “Chariot”",
  "R-15 - “Chariot” (Crate)",
  "R-17 “Retiarius” Skirmisher",
  "R-17 “Retiarius” Skirmisher (Crate)",
  "R-5 “Atlas” Hauler",
  "R-5 “Atlas” Hauler (Crate)",
  "R-5b “Sisyphus” Hauler",
  "R-5b “Sisyphus” Hauler (Crate)",
  "R-9 “Speartip” Escort",
  "R-9 “Speartip” Escort (Crate)",
  "RPG",
  "RPG (Crate)",
  "RR-3 “Stolon” Tanker",
  "RR-3 “Stolon” Tanker (Crate)",
  "Radio",
  "Radio (Crate)",
  "Radio Backpack",
  "Radio Backpack (Crate)",
  "Rare Alloys",
  "Rare Alloys (Crate)",
  "Rare Materials",
  "Rare Materials (Crate)",
  "Rare Metal",
  "Rare Metal (Crate)",
  "Recon Camo",
  "Recon Camo (Crate)",
  "Refined Materials",
  "Refined Materials (Crate)",
  "Relic Materials",
  "Relic Materials (Crate)",
  "Remex Garb",
  "Remex Garb (Crate)",
  "Reserve Power",
  "Reserve Power (Crate)",
  "Resource Container",
  "Resource Container (Crate)",
  "Rinnspeir Mk. I Zealot",
  "Rinnspeir Mk. I Zealot (Crate)",
  "Rinnspeir Ornitier-Class Gunship",
  "Rinnspeir Ornitier-Class Gunship (Crate)",
  "Rooster - Junkwagon",
  "Rooster - Junkwagon (Crate)",
  "Rooster - Lamploader",
  "Rooster - Lamploader (Crate)",
  "Rooster - Tumblebox",
  "Rooster - Tumblebox (Crate)",
  "Rycker 4/3-F Wasp Nest",
  "Rycker 4/3-F Wasp Nest (Crate)",
  "Salvage",
  "Salvage (Crate)",
  "Sampo Auto-Rifle 77",
  "Sampo Auto-Rifle 77 (Crate)",
  "Sandbag",
  "Sandbag (Crate)",
  "Sapper Gear",
  "Sapper Gear (Crate)",
  "Shatter Missile",
  "Shatter Missile (Crate)",
  "Shipping Container",
  "Shipping Container (Crate)",
  "Shovel",
  "Shovel (Crate)",
  "Shrapnel Mortar Shell",
  "Shrapnel Mortar Shell (Crate)",
  "Silverhand - Mk. IV",
  "Silverhand - Mk. IV (Crate)",
  "Silverhand Chieftain - Mk. VI",
  "Silverhand Chieftain - Mk. VI (Crate)",
  "Silverhand Lordscar - Mk. X",
  "Silverhand Lordscar - Mk. X (Crate)",
  "Sledge Hammer",
  "Sledge Hammer (Crate)",
  "Soldier Supplies",
  "Soldier Supplies (Crate)",
  "Specialist’s Overcoat",
  "Specialist’s Overcoat (Crate)",
  "Steel Construction Materials",
  "Steel Construction Materials (Crate)",
  "Storm Cannon Parts",
  "Storm Cannon Parts (Crate)",
  "Strider",
  "Strider (Crate)",
  "Structure Parts",
  "Structure Parts (Crate)",
  "Sulfur",
  "Sulfur (Crate)",
  "Swallowtail 988/127-2",
  "Swallowtail 988/127-2 (Crate)",
  "T12 “Actaeon” Tankette",
  "T12 “Actaeon” Tankette (Crate)",
  "T13 “Deioneus” Rocket Battery",
  "T13 “Deioneus” Rocket Battery (Crate)",
  "T14 “Vesta” Tankette",
  "T14 “Vesta” Tankette (Crate)",
  "T20 “Ixion” Tankette",
  "T20 “Ixion” Tankette (Crate)",
  "T3 “Xiphos”",
  "T3 “Xiphos” (Crate)",
  "T5 “Percutio”",
  "T5 “Percutio” (Crate)",
  "T8 “Gemini”",
  "T8 “Gemini” (Crate)",
  "Tankman’s Coveralls",
  "Tankman’s Coveralls (Crate)",
  "The Hangman 757",
  "The Hangman 757 (Crate)",
  "The Ospreay",
  "The Ospreay (Crate)",
  "Thermal Shielding",
  "Thermal Shielding (Crate)",
  "Toxot-902 “Blind Silver”",
  "Toxot-902 “Blind Silver” (Crate)",
  "Trauma Kit",
  "Trauma Kit (Crate)",
  "Tremola Grenade GPb-1",
  "Tremola Grenade GPb-1 (Crate)",
  "Tripod",
  "Tripod (Crate)",
  "Tulka I1.9 White Raven",
  "Tulka I1.9 White Raven (Crate)",
  "Tulka P4 Welkinrive",
  "Tulka P4 Welkinrive (Crate)",
  "Type B - “Lucian”",
  "Type B - “Lucian” (Crate)",
  "Type C - “Charon”",
  "Type C - “Charon” (Crate)",
  "UV-05a “Argonaut”",
  "UV-05a “Argonaut” (Crate)",
  "UV-24 “Icarus”",
  "UV-24 “Icarus” (Crate)",
  "UV-5c “Odyssey”",
  "UV-5c “Odyssey” (Crate)",
  "Underground Fortress Parts",
  "Underground Fortress Parts (Crate)",
  "Unexploded Ordnance",
  "Unexploded Ordnance (Crate)",
  "Unstable Substances",
  "Unstable Substances (Crate)",
  "V-1 Tzykalia",
  "V-1 Tzykalia (Crate)",
  "V-5b Pegasus",
  "V-5b Pegasus (Crate)",
  "Velian Flak Vest",
  "Velian Flak Vest (Crate)",
  "Venom c.II 35",
  "Venom c.II 35 (Crate)",
  "Volta r.I Repeater",
  "Volta r.I Repeater (Crate)",
  "War Ensign",
  "War Ensign (Crate)",
  "Warden Aircraft Engine (Large)",
  "Warden Aircraft Engine (Large) (Crate)",
  "Warden Aircraft Engine (Small)",
  "Warden Aircraft Engine (Small) (Crate)",
  "Warden Aircraft Mechanical Parts (Large)",
  "Warden Aircraft Mechanical Parts (Large) (Crate)",
  "Warden Aircraft Mechanical Parts (Small)",
  "Warden Aircraft Mechanical Parts (Small) (Crate)",
  "Water",
  "Water (Crate)",
  "Water Bucket",
  "Water Bucket (Crate)",
  "Weather Station Parts",
  "Weather Station Parts (Crate)",
  "Willow's Bane Ammo",
  "Willow's Bane Ammo (Crate)",
  "Willow’s Bane Model 845",
  "Willow’s Bane Model 845 (Crate)",
  "Wind Sock",
  "Wind Sock (Crate)",
  "Wreckage",
  "Wreckage (Crate)",
  "Wrench",
  "Wrench (Crate)",
  "“Dawn” Ve.II",
  "“Dawn” Ve.II (Crate)",
  "“Dusk” ce.III",
  "“Dusk” ce.III (Crate)",
  "“Lionclaw” mc.VIII",
  "“Lionclaw” mc.VIII (Crate)",
  "“Molten Wind” v.II Ammo",
  "“Molten Wind” v.II Ammo (Crate)",
  "“Molten Wind” v.II Flame Torch",
  "“Molten Wind” v.II Flame Torch (Crate)",
  "“Quickhatch” Rt.I",
  "“Quickhatch” Rt.I (Crate)",
  "“The Pitch Gun” mc.V",
  "“The Pitch Gun” mc.V (Crate)",
  "“Typhon” ra.XII",
  "“Typhon” ra.XII (Crate)"
]);

export const STANDARD_ITEMS_LIST: string[] = [
  ".44",
  ".44 (Crate)",
  "00MS “Stinger”",
  "00MS “Stinger” (Crate)",
  "03MM “Caster”",
  "03MM “Caster” (Crate)",
  "12.7mm",
  "12.7mm (Crate)",
  "120-68 “Koronides” Field Gun",
  "120-68 “Koronides” Field Gun (Crate)",
  "120mm",
  "120mm (Crate)",
  "14.5mm",
  "14.5mm (Crate)",
  "150mm",
  "150mm (Crate)",
  "20mm",
  "20mm (Crate)",
  "228 Satterley Heavy Storm Rifle",
  "228 Satterley Heavy Storm Rifle (Crate)",
  "250mm \"Fury\" Shell",
  "250mm \"Fury\" Shell (Crate)",
  "250mm \"Purity\" Shell",
  "250mm \"Purity\" Shell (Crate)",
  "30-250 “Tisiphone” Field Cannon",
  "30-250 “Tisiphone” Field Cannon (Crate)",
  "300mm",
  "300mm (Crate)",
  "30mm",
  "30mm (Crate)",
  "3C-High Explosive Rocket",
  "3C-High Explosive Rocket (Crate)",
  "40-250 “Alekto” Heavy Cannon",
  "40-250 “Alekto” Heavy Cannon (Crate)",
  "40-45 “Smelter”",
  "40-45 “Smelter” (Crate)",
  "40mm",
  "40mm (Crate)",
  "4C-Fire Rocket",
  "4C-Fire Rocket (Crate)",
  "50-500 “Thunderbolt” Cannon",
  "50-500 “Thunderbolt” Cannon (Crate)",
  "68A-4 Ronan Fathomer",
  "68A-4 Ronan Fathomer (Crate)",
  "68mm",
  "68mm (Crate)",
  "7.62mm",
  "7.62mm (Crate)",
  "7.92mm",
  "7.92mm (Crate)",
  "74b-1 Ronan Gunship",
  "74b-1 Ronan Gunship (Crate)",
  "75mm",
  "75mm (Crate)",
  "81f-f Ronan Blackguard",
  "81f-f Ronan Blackguard (Crate)",
  "85K-a “Spatha”",
  "85K-a “Spatha” (Crate)",
  "85K-b “Falchion”",
  "85K-b “Falchion” (Crate)",
  "85V-g \"Talos\"",
  "85V-g \"Talos\" (Crate)",
  "86K-a “Bardiche”",
  "86K-a “Bardiche” (Crate)",
  "86K-c “Ranseur”",
  "86K-c “Ranseur” (Crate)",
  "8mm",
  "8mm (Crate)",
  "90T-v “Nemesis”",
  "90T-v “Nemesis” (Crate)",
  "912 Shrike Rounds",
  "912 Shrike Rounds (Crate)",
  "94.5mm",
  "94.5mm (Crate)",
  "945g “Stygian Bolt”",
  "945g “Stygian Bolt” (Crate)",
  "950-70b Anti-Aircraft Shell",
  "950-70b Anti-Aircraft Shell (Crate)",
  "9mm",
  "9mm (Crate)",
  "A0E-9 Rocket Body",
  "A0E-9 Rocket Body (Crate)",
  "A0E-9 Rocket Booster",
  "A0E-9 Rocket Booster (Crate)",
  "A0E-9 Rocket Warhead",
  "A0E-9 Rocket Warhead (Crate)",
  "A3 Harpa Fragmentation Grenade",
  "A3 Harpa Fragmentation Grenade (Crate)",
  "A51 Venti “Daedalus”",
  "A51 Venti “Daedalus” (Crate)",
  "AA-2 \"Battering Ram\"",
  "AA-2 \"Battering Ram\" (Crate)",
  "AB-11 “Doru”",
  "AB-11 “Doru” (Crate)",
  "AB-8 “Acheron”",
  "AB-8 “Acheron” (Crate)",
  "AP/RPG",
  "AP/RPG (Crate)",
  "ARC/RPG",
  "ARC/RPG (Crate)",
  "AU-A150 Taurine Rigger",
  "AU-A150 Taurine Rigger (Crate)",
  "Aalto Storm Rifle 24",
  "Aalto Storm Rifle 24 (Crate)",
  "Abisme AT-99 Mine",
  "Abisme AT-99 Mine (Crate)",
  "Ahti Model 2",
  "Ahti Model 2 (Crate)",
  "Air Raid Siren",
  "Aircraft Radar Parts",
  "Aircraft Radar Parts (Crate)",
  "Alligator Charge",
  "Alligator Charge (Crate)",
  "Aluminum",
  "Aluminum (Crate)",
  "Aluminum Alloy",
  "Aluminum Alloy (Crate)",
  "Anti-Tank Sticky Bomb",
  "Anti-Tank Sticky Bomb (Crate)",
  "Argenti r.II Rifle",
  "Argenti r.II Rifle (Crate)",
  "Assembly Materials I",
  "Assembly Materials I (Crate)",
  "Assembly Materials II",
  "Assembly Materials II (Crate)",
  "Assembly Materials III",
  "Assembly Materials III (Crate)",
  "Assembly Materials IV",
  "Assembly Materials IV (Crate)",
  "Assembly Materials V",
  "Assembly Materials V (Crate)",
  "Auster’s Harness",
  "Auster’s Harness (Crate)",
  "Aviator’s Raiment",
  "Aviator’s Raiment (Crate)",
  "B2 Varsi Anti-Tank Grenade",
  "B2 Varsi Anti-Tank Grenade (Crate)",
  "BF5 White Ash Flask Grenade",
  "BF5 White Ash Flask Grenade (Crate)",
  "BMS - Aquatipper",
  "BMS - Aquatipper (Crate)",
  "BMS - Class 2 Mobile Auto-Crane",
  "BMS - Class 2 Mobile Auto-Crane (Crate)",
  "BMS - Fabricator",
  "BMS - Fabricator (Crate)",
  "BMS - Ironship",
  "BMS - Ironship (Crate)",
  "BMS - Packmule Flatbed",
  "BMS - Packmule Flatbed (Crate)",
  "BMS - Scrap Hauler",
  "BMS - Scrap Hauler (Crate)",
  "BMS - Universal Assembly Rig",
  "BMS - Universal Assembly Rig (Crate)",
  "Balfour Falconer 250mm",
  "Balfour Falconer 250mm (Crate)",
  "Balfour Rampart 68mm",
  "Balfour Rampart 68mm (Crate)",
  "Balfour Stockade 75mm",
  "Balfour Stockade 75mm (Crate)",
  "Balfour Wolfhound 40mm",
  "Balfour Wolfhound 40mm (Crate)",
  "Bandages",
  "Bandages (Crate)",
  "Bane 45",
  "Bane 45 (Crate)",
  "Barbed Wire",
  "Barbed Wire (Crate)",
  "Basic Materials",
  "Basic Materials (Crate)",
  "Bellweather by VAC",
  "Bellweather by VAC (Crate)",
  "Binoculars",
  "Binoculars (Crate)",
  "Blakerow 871",
  "Blakerow 871 (Crate)",
  "Blood Plasma",
  "Blood Plasma (Crate)",
  "Bomastone Grenade",
  "Bomastone Grenade (Crate)",
  "Bonesaw MK.3",
  "Bonesaw MK.3 (Crate)",
  "Booker Greyhound Model 910",
  "Booker Greyhound Model 910 (Crate)",
  "Booker Storm Rifle Model 838",
  "Booker Storm Rifle Model 838 (Crate)",
  "Buckhorn CCQ-18",
  "Buckhorn CCQ-18 (Crate)",
  "Buckshot",
  "Buckshot (Crate)",
  "Caoivish Parka",
  "Caoivish Parka (Crate)",
  "Carnyx Anti-Tank Rocket Launcher",
  "Carnyx Anti-Tank Rocket Launcher (Crate)",
  "Cascadier 873",
  "Cascadier 873 (Crate)",
  "Catara mo.II",
  "Catara mo.II (Crate)",
  "Catena rt.IV Auto-Rifle",
  "Catena rt.IV Auto-Rifle (Crate)",
  "Clancy Cinder M3",
  "Clancy Cinder M3 (Crate)",
  "Clancy-Raca M4",
  "Clancy-Raca M4 (Crate)",
  "Cloudrunner’s Vesture",
  "Cloudrunner’s Vesture (Crate)",
  "Cnute Cliffwrest",
  "Cnute Cliffwrest (Crate)",
  "Coal",
  "Coal (Crate)",
  "Coke",
  "Coke (Crate)",
  "Collins Cannon 68mm",
  "Collins Cannon 68mm (Crate)",
  "Colonial Aircraft Engine (Large)",
  "Colonial Aircraft Engine (Large) (Crate)",
  "Colonial Aircraft Engine (Small)",
  "Colonial Aircraft Engine (Small) (Crate)",
  "Colonial Aircraft Mechanical Parts (Large)",
  "Colonial Aircraft Mechanical Parts (Large) (Crate)",
  "Colonial Aircraft Mechanical Parts (Small)",
  "Colonial Aircraft Mechanical Parts (Small) (Crate)",
  "Cometa T2-9",
  "Cometa T2-9 (Crate)",
  "Components",
  "Components (Crate)",
  "Concrete Materials",
  "Concrete Materials (Crate)",
  "Concrete Mixer",
  "Concrete Mixer (Crate)",
  "Construction Equipment",
  "Construction Equipment (Crate)",
  "Construction Materials",
  "Construction Materials (Crate)",
  "Construction Parts",
  "Construction Parts (Crate)",
  "Copper",
  "Copper (Crate)",
  "Copper Alloy",
  "Copper Alloy (Crate)",
  "Cremari Mortar",
  "Cremari Mortar (Crate)",
  "Critically Wounded Soldier",
  "Critically Wounded Soldier (Crate)",
  "Crow’s Foot Mine",
  "Crow’s Foot Mine (Crate)",
  "Cutler Foebreaker",
  "Cutler Foebreaker (Crate)",
  "Cutler Launcher 4",
  "Cutler Launcher 4 (Crate)",
  "DAE 1b-2 “Serra”",
  "DAE 1b-2 “Serra” (Crate)",
  "DAE 1o-3 “Polybolos”",
  "DAE 1o-3 “Polybolos” (Crate)",
  "DAE 2a-1 “Ruptura”",
  "DAE 2a-1 “Ruptura” (Crate)",
  "DAE 3b-2 “Hades’ Net”",
  "DAE 3b-2 “Hades’ Net” (Crate)",
  "DAE 5b “Zeal”",
  "DAE 5b “Zeal” (Crate)",
  "Damaged Colonial Aircraft Engine (Large)",
  "Damaged Colonial Aircraft Engine (Large) (Crate)",
  "Damaged Colonial Aircraft Engine (Small)",
  "Damaged Colonial Aircraft Engine (Small) (Crate)",
  "Damaged Colonial Aircraft Mechanical Parts (Large)",
  "Damaged Colonial Aircraft Mechanical Parts (Large) (Crate)",
  "Damaged Colonial Aircraft Mechanical Parts (Small)",
  "Damaged Colonial Aircraft Mechanical Parts (Small) (Crate)",
  "Damaged Components",
  "Damaged Components (Crate)",
  "Damaged Warden Aircraft Engine (Large)",
  "Damaged Warden Aircraft Engine (Large) (Crate)",
  "Damaged Warden Aircraft Engine (Small)",
  "Damaged Warden Aircraft Engine (Small) (Crate)",
  "Damaged Warden Aircraft Mechanical Parts (Large)",
  "Damaged Warden Aircraft Mechanical Parts (Large) (Crate)",
  "Damaged Warden Aircraft Mechanical Parts (Small)",
  "Damaged Warden Aircraft Mechanical Parts (Small) (Crate)",
  "Das Krokodil by VAC",
  "Das Krokodil by VAC (Crate)",
  "Daucus isg.III",
  "Daucus isg.III (Crate)",
  "Devitt Ironhide Mk. IV",
  "Devitt Ironhide Mk. IV (Crate)",
  "Devitt Mk. III",
  "Devitt Mk. III (Crate)",
  "Devitt-Caine Mk. IV MMR",
  "Devitt-Caine Mk. IV MMR (Crate)",
  "Diesel",
  "Diesel (Crate)",
  "Drummond 100a",
  "Drummond 100a (Crate)",
  "Drummond Loscann 55c",
  "Drummond Loscann 55c (Crate)",
  "Drummond Spitfire 100d",
  "Drummond Spitfire 100d (Crate)",
  "Duncan’s Coin 14.5mm",
  "Duncan’s Coin 14.5mm (Crate)",
  "Dunne Caravaner 2f",
  "Dunne Caravaner 2f (Crate)",
  "Dunne Dousing Engine 3r",
  "Dunne Dousing Engine 3r (Crate)",
  "Dunne Fuelrunner 2d",
  "Dunne Fuelrunner 2d (Crate)",
  "Dunne Landrunner 12c",
  "Dunne Landrunner 12c (Crate)",
  "Dunne Leatherback 2a",
  "Dunne Leatherback 2a (Crate)",
  "Dunne Loadlugger 3c",
  "Dunne Loadlugger 3c (Crate)",
  "Dunne Responder 3e",
  "Dunne Responder 3e (Crate)",
  "Dunne Transport",
  "Dunne Transport (Crate)",
  "E680-S Rudder Lock",
  "E680-S Rudder Lock (Crate)",
  "E681-B Hullbreaker Mine",
  "E681-B Hullbreaker Mine (Crate)",
  "Eleos Infantry Dagger",
  "Eleos Infantry Dagger (Crate)",
  "Enriched Oil",
  "Enriched Oil (Crate)",
  "Explosive Powder",
  "Explosive Powder (Crate)",
  "Fabri Rucksack",
  "Fabri Rucksack (Crate)",
  "Falias Raiding Club",
  "Falias Raiding Club (Crate)",
  "Ferro 879",
  "Ferro 879 (Crate)",
  "Fiddler Submachine Gun Model 868",
  "Fiddler Submachine Gun Model 868 (Crate)",
  "First Aid Kit",
  "First Aid Kit (Crate)",
  "Flame Ammo",
  "Flame Ammo (Crate)",
  "Flare Mortar Shell",
  "Flare Mortar Shell (Crate)",
  "Flight Mask",
  "Fuscina pi.I",
  "Fuscina pi.I (Crate)",
  "G40 “Sagittarii”",
  "G40 “Sagittarii” (Crate)",
  "GA6 “Cestus”",
  "GA6 “Cestus” (Crate)",
  "Gallagher Brigand Mk. I",
  "Gallagher Brigand Mk. I (Crate)",
  "Gallagher Highwayman Mk. III",
  "Gallagher Highwayman Mk. III (Crate)",
  "Gallagher Outlaw Mk. II",
  "Gallagher Outlaw Mk. II (Crate)",
  "Gallagher Thornfall Mk. VI",
  "Gallagher Thornfall Mk. VI (Crate)",
  "Gas Mask",
  "Gas Mask (Crate)",
  "Gas Mask Filter",
  "Gas Mask Filter (Crate)",
  "Gentleman’s Peacoat",
  "Gentleman’s Peacoat (Crate)",
  "Gravel",
  "Gravel (Crate)",
  "Green Ash Grenade",
  "Green Ash Grenade (Crate)",
  "Grenadier’s Baldric",
  "Grenadier’s Baldric (Crate)",
  "Gunner’s Breastplate",
  "Gunner’s Breastplate (Crate)",
  "H-10 “Pelekys”",
  "H-10 “Pelekys” (Crate)",
  "H-19 “Vulcan”",
  "H-19 “Vulcan” (Crate)",
  "H-5 \"Hatchet\"",
  "H-5 \"Hatchet\" (Crate)",
  "H-8 “Kranesca”",
  "H-8 “Kranesca” (Crate)",
  "HC-2 “Scorpion”",
  "HC-2 “Scorpion” (Crate)",
  "HC-7 \"Ballista\"",
  "HC-7 \"Ballista\" (Crate)",
  "HH-a “Javelin”",
  "HH-a “Javelin” (Crate)",
  "HH-b “Hoplite”",
  "HH-b “Hoplite” (Crate)",
  "HH-d “Peltast”",
  "HH-d “Peltast” (Crate)",
  "Hammer",
  "Hammer (Crate)",
  "Havoc Charge",
  "Havoc Charge (Crate)",
  "Havoc Charge Detonator",
  "Havoc Charge Detonator (Crate)",
  "Heavy Explosive Powder",
  "Heavy Explosive Powder (Crate)",
  "Heavy Oil",
  "Heavy Oil (Crate)",
  "Heavy Topcoat",
  "Heavy Topcoat (Crate)",
  "Huber Exalt 150mm",
  "Huber Exalt 150mm (Crate)",
  "Huber Lariat 120mm",
  "Huber Lariat 120mm (Crate)",
  "Huber Starbreaker 94.5mm",
  "Huber Starbreaker 94.5mm (Crate)",
  "Hydra’s Whisper",
  "Hydra’s Whisper (Crate)",
  "Ignifist 30",
  "Ignifist 30 (Crate)",
  "Incendiary Mortar Shell",
  "Incendiary Mortar Shell (Crate)",
  "Infantry Battledress",
  "Infantry Battledress (Crate)",
  "Intelligence Center Parts",
  "Intelligence Center Parts (Crate)",
  "Iron",
  "Iron (Crate)",
  "Iron Alloy",
  "Iron Alloy (Crate)",
  "K-81e “Sombre”",
  "K-81e “Sombre” (Crate)",
  "KLG901-2 Lunaire F",
  "KLG901-2 Lunaire F (Crate)",
  "KRF1-750 Dragonfly",
  "KRF1-750 Dragonfly (Crate)",
  "KRN886-127 Gast Machine Gun",
  "KRN886-127 Gast Machine Gun (Crate)",
  "KRR2-790 Omen",
  "KRR2-790 Omen (Crate)",
  "KRR3-792 Auger",
  "KRR3-792 Auger (Crate)",
  "King Gallant Mk. II",
  "King Gallant Mk. II (Crate)",
  "King Jester Mk. I-1",
  "King Jester Mk. I-1 (Crate)",
  "King Spire Mk. I",
  "King Spire Mk. I (Crate)",
  "Kivela Power Wheel 80-1",
  "Kivela Power Wheel 80-1 (Crate)",
  "Lamentum mm.IV",
  "Lamentum mm.IV (Crate)",
  "Leary AA-70 Bolas",
  "Leary AA-70 Bolas (Crate)",
  "Leary Shellbore 68mm",
  "Leary Shellbore 68mm (Crate)",
  "Leary Snare Trap 20",
  "Leary Snare Trap 20 (Crate)",
  "Legion Vexillum",
  "Legion Vexillum (Crate)",
  "Legionary Fatigues",
  "Legionary Fatigues (Crate)",
  "Legionary’s Oilcoat",
  "Legionary’s Oilcoat (Crate)",
  "Liaison Transmitter",
  "Liaison Transmitter (Crate)",
  "Liquid Container",
  "Liquid Container (Crate)",
  "Listening Kit",
  "Listening Kit (Crate)",
  "Lodesman’s Lorica",
  "Lodesman’s Lorica (Crate)",
  "Luminary Mk. II Harbinger",
  "Luminary Mk. II Harbinger (Crate)",
  "Luminary Mk. IV Herald",
  "Luminary Mk. IV Herald (Crate)",
  "M925 Austringer Man-O-War",
  "M925 Austringer Man-O-War (Crate)",
  "Maintenance Supplies",
  "Maintenance Supplies (Crate)",
  "Malone MK.2",
  "Malone MK.2 (Crate)",
  "Malone Ratcatcher MK.1",
  "Malone Ratcatcher MK.1 (Crate)",
  "Mammon 91-b",
  "Mammon 91-b (Crate)",
  "Mark II Raidbreaker",
  "Mark II Raidbreaker (Crate)",
  "Material Pallet",
  "Material Pallet (Crate)",
  "Medic Fatigues",
  "Medic Fatigues (Crate)",
  "Mergo-4 “Myrmidon”",
  "Mergo-4 “Myrmidon” (Crate)",
  "Metal Beam",
  "Metal Beam (Crate)",
  "Model-7 “Evie”",
  "Model-7 “Evie” (Crate)",
  "Moray Torpedo",
  "Moray Torpedo (Crate)",
  "Mortar Shell",
  "Mortar Shell (Crate)",
  "Mounted Bonesaw MK.3",
  "Mounted Bonesaw MK.3 (Crate)",
  "Mounted Fissura gd.I",
  "Mounted Fissura gd.I (Crate)",
  "Mulloy LPC",
  "Mulloy LPC (Crate)",
  "Naval Buoy",
  "Naval Hull Segments",
  "Naval Hull Segments (Crate)",
  "Naval Shell Plating",
  "Naval Shell Plating (Crate)",
  "Naval Turbine Components",
  "Naval Turbine Components (Crate)",
  "Neville Anti-Tank Rifle",
  "Neville Anti-Tank Rifle (Crate)",
  "Niska Mk. I Gun Motor Carriage",
  "Niska Mk. I Gun Motor Carriage (Crate)",
  "Niska Mk. II Blinder",
  "Niska Mk. II Blinder (Crate)",
  "Niska Mk. III Scar Twin",
  "Niska Mk. III Scar Twin (Crate)",
  "Niska-Rycker Mk. IX Skycaller",
  "Niska-Rycker Mk. IX Skycaller (Crate)",
  "No.1 “The Liar” Submachinegun",
  "No.1 “The Liar” Submachinegun (Crate)",
  "No.2 Loughcaster",
  "No.2 Loughcaster (Crate)",
  "No.2B Hawthorne",
  "No.2B Hawthorne (Crate)",
  "No.4 The Pillory Scattergun",
  "No.4 The Pillory Scattergun (Crate)",
  "Noble Firebrand Mk. XVII",
  "Noble Firebrand Mk. XVII (Crate)",
  "Noble Widow MK. XIV",
  "Noble Widow MK. XIV (Crate)",
  "Officer’s Regalia",
  "Officer’s Regalia (Crate)",
  "Officialis’ Attire",
  "Officialis’ Attire (Crate)",
  "Oil",
  "Oil (Crate)",
  "Outrider’s Mantle",
  "Outrider’s Mantle (Crate)",
  "O’Brien V.101 Freeman",
  "O’Brien V.101 Freeman (Crate)",
  "O’Brien V.110",
  "O’Brien V.110 (Crate)",
  "O’Brien V.113 Gravekeeper",
  "O’Brien V.113 Gravekeeper (Crate)",
  "O’Brien V.121 Highlander",
  "O’Brien V.121 Highlander (Crate)",
  "O’Brien V.130 Wild Jack",
  "O’Brien V.130 Wild Jack (Crate)",
  "O’Brien V.190 Knave",
  "O’Brien V.190 Knave (Crate)",
  "O’Brien v.200 Squire",
  "O’Brien v.200 Squire (Crate)",
  "PT-815 Smoke Grenade",
  "PT-815 Smoke Grenade (Crate)",
  "Padded Boiler Suit",
  "Padded Boiler Suit (Crate)",
  "Paratrooper’s Ruck",
  "Paratrooper’s Ruck (Crate)",
  "Petrol",
  "Petrol (Crate)",
  "Physician’s Jacket",
  "Physician’s Jacket (Crate)",
  "Pipe",
  "Pipe (Crate)",
  "Processed Construction Materials",
  "Processed Construction Materials (Crate)",
  "Quillback Torpedo",
  "Quillback Torpedo (Crate)",
  "R-1 Hauler",
  "R-1 Hauler (Crate)",
  "R-12 - “Salus” Ambulance",
  "R-12 - “Salus” Ambulance (Crate)",
  "R-12b - “Salva” Flame Truck",
  "R-12b - “Salva” Flame Truck (Crate)",
  "R-15 - “Chariot”",
  "R-15 - “Chariot” (Crate)",
  "R-17 “Retiarius” Skirmisher",
  "R-17 “Retiarius” Skirmisher (Crate)",
  "R-5 “Atlas” Hauler",
  "R-5 “Atlas” Hauler (Crate)",
  "R-5b “Sisyphus” Hauler",
  "R-5b “Sisyphus” Hauler (Crate)",
  "R-9 “Speartip” Escort",
  "R-9 “Speartip” Escort (Crate)",
  "RPG",
  "RPG (Crate)",
  "RR-3 “Stolon” Tanker",
  "RR-3 “Stolon” Tanker (Crate)",
  "Radio",
  "Radio (Crate)",
  "Radio Backpack",
  "Radio Backpack (Crate)",
  "Rare Alloys",
  "Rare Alloys (Crate)",
  "Rare Materials",
  "Rare Materials (Crate)",
  "Rare Metal",
  "Rare Metal (Crate)",
  "Recon Camo",
  "Recon Camo (Crate)",
  "Refined Materials",
  "Refined Materials (Crate)",
  "Relic Materials",
  "Relic Materials (Crate)",
  "Remex Garb",
  "Remex Garb (Crate)",
  "Reserve Power",
  "Reserve Power (Crate)",
  "Resource Container",
  "Resource Container (Crate)",
  "Rinnspeir Mk. I Zealot",
  "Rinnspeir Mk. I Zealot (Crate)",
  "Rinnspeir Ornitier-Class Gunship",
  "Rinnspeir Ornitier-Class Gunship (Crate)",
  "Rooster - Junkwagon",
  "Rooster - Junkwagon (Crate)",
  "Rooster - Lamploader",
  "Rooster - Lamploader (Crate)",
  "Rooster - Tumblebox",
  "Rooster - Tumblebox (Crate)",
  "Rycker 4/3-F Wasp Nest",
  "Rycker 4/3-F Wasp Nest (Crate)",
  "Salvage",
  "Salvage (Crate)",
  "Sampo Auto-Rifle 77",
  "Sampo Auto-Rifle 77 (Crate)",
  "Sandbag",
  "Sandbag (Crate)",
  "Sapper Gear",
  "Sapper Gear (Crate)",
  "Shatter Missile",
  "Shatter Missile (Crate)",
  "Shipping Container",
  "Shipping Container (Crate)",
  "Shovel",
  "Shovel (Crate)",
  "Shrapnel Mortar Shell",
  "Shrapnel Mortar Shell (Crate)",
  "Silverhand - Mk. IV",
  "Silverhand - Mk. IV (Crate)",
  "Silverhand Chieftain - Mk. VI",
  "Silverhand Chieftain - Mk. VI (Crate)",
  "Silverhand Lordscar - Mk. X",
  "Silverhand Lordscar - Mk. X (Crate)",
  "Sledge Hammer",
  "Sledge Hammer (Crate)",
  "Soldier Supplies",
  "Soldier Supplies (Crate)",
  "Specialist’s Overcoat",
  "Specialist’s Overcoat (Crate)",
  "Steel Construction Materials",
  "Steel Construction Materials (Crate)",
  "Storm Cannon Parts",
  "Storm Cannon Parts (Crate)",
  "Strider",
  "Strider (Crate)",
  "Structure Parts",
  "Structure Parts (Crate)",
  "Sulfur",
  "Sulfur (Crate)",
  "Swallowtail 988/127-2",
  "Swallowtail 988/127-2 (Crate)",
  "T12 “Actaeon” Tankette",
  "T12 “Actaeon” Tankette (Crate)",
  "T13 “Deioneus” Rocket Battery",
  "T13 “Deioneus” Rocket Battery (Crate)",
  "T14 “Vesta” Tankette",
  "T14 “Vesta” Tankette (Crate)",
  "T20 “Ixion” Tankette",
  "T20 “Ixion” Tankette (Crate)",
  "T3 “Xiphos”",
  "T3 “Xiphos” (Crate)",
  "T5 “Percutio”",
  "T5 “Percutio” (Crate)",
  "T8 “Gemini”",
  "T8 “Gemini” (Crate)",
  "Tankman’s Coveralls",
  "Tankman’s Coveralls (Crate)",
  "The Hangman 757",
  "The Hangman 757 (Crate)",
  "The Ospreay",
  "The Ospreay (Crate)",
  "Thermal Shielding",
  "Thermal Shielding (Crate)",
  "Toxot-902 “Blind Silver”",
  "Toxot-902 “Blind Silver” (Crate)",
  "Trauma Kit",
  "Trauma Kit (Crate)",
  "Tremola Grenade GPb-1",
  "Tremola Grenade GPb-1 (Crate)",
  "Tripod",
  "Tripod (Crate)",
  "Tulka I1.9 White Raven",
  "Tulka I1.9 White Raven (Crate)",
  "Tulka P4 Welkinrive",
  "Tulka P4 Welkinrive (Crate)",
  "Type B - “Lucian”",
  "Type B - “Lucian” (Crate)",
  "Type C - “Charon”",
  "Type C - “Charon” (Crate)",
  "UV-05a “Argonaut”",
  "UV-05a “Argonaut” (Crate)",
  "UV-24 “Icarus”",
  "UV-24 “Icarus” (Crate)",
  "UV-5c “Odyssey”",
  "UV-5c “Odyssey” (Crate)",
  "Underground Fortress Parts",
  "Underground Fortress Parts (Crate)",
  "Unexploded Ordnance",
  "Unexploded Ordnance (Crate)",
  "Unstable Substances",
  "Unstable Substances (Crate)",
  "V-1 Tzykalia",
  "V-1 Tzykalia (Crate)",
  "V-5b Pegasus",
  "V-5b Pegasus (Crate)",
  "Velian Flak Vest",
  "Velian Flak Vest (Crate)",
  "Venom c.II 35",
  "Venom c.II 35 (Crate)",
  "Volta r.I Repeater",
  "Volta r.I Repeater (Crate)",
  "War Ensign",
  "War Ensign (Crate)",
  "Warden Aircraft Engine (Large)",
  "Warden Aircraft Engine (Large) (Crate)",
  "Warden Aircraft Engine (Small)",
  "Warden Aircraft Engine (Small) (Crate)",
  "Warden Aircraft Mechanical Parts (Large)",
  "Warden Aircraft Mechanical Parts (Large) (Crate)",
  "Warden Aircraft Mechanical Parts (Small)",
  "Warden Aircraft Mechanical Parts (Small) (Crate)",
  "Water",
  "Water (Crate)",
  "Water Bucket",
  "Water Bucket (Crate)",
  "Weather Station Parts",
  "Weather Station Parts (Crate)",
  "Willow's Bane Ammo",
  "Willow's Bane Ammo (Crate)",
  "Willow’s Bane Model 845",
  "Willow’s Bane Model 845 (Crate)",
  "Wind Sock",
  "Wind Sock (Crate)",
  "Wreckage",
  "Wreckage (Crate)",
  "Wrench",
  "Wrench (Crate)",
  "“Dawn” Ve.II",
  "“Dawn” Ve.II (Crate)",
  "“Dusk” ce.III",
  "“Dusk” ce.III (Crate)",
  "“Lionclaw” mc.VIII",
  "“Lionclaw” mc.VIII (Crate)",
  "“Molten Wind” v.II Ammo",
  "“Molten Wind” v.II Ammo (Crate)",
  "“Molten Wind” v.II Flame Torch",
  "“Molten Wind” v.II Flame Torch (Crate)",
  "“Quickhatch” Rt.I",
  "“Quickhatch” Rt.I (Crate)",
  "“The Pitch Gun” mc.V",
  "“The Pitch Gun” mc.V (Crate)",
  "“Typhon” ra.XII",
  "“Typhon” ra.XII (Crate)"
];
