// This file is auto-generated. Do not edit manually.
export const STANDARD_ITEMS = new Set([
    "“Dusk” ce.III (Crate)",
    "Booker Storm Rifle Model 838 (Crate)",
    "Aalto Storm Rifle 24 (Crate)",
    "7.92mm (Crate)",
    "Catara mo.II (Crate)",
    "KRN886-127 Gast Machine Gun (Crate)",
    "Malone MK.2 (Crate)",
    "Bomastone Grenade (Crate)",
    "A3 Harpa Fragmentation Grenade (Crate)",
    "Ferro 879 (Crate)",
    "Cascadier 873 (Crate)",
    "Ahti Model 2 (Crate)",
    "8mm (Crate)",
    "Cometa T2-9 (Crate)",
    "The Hangman 757 (Crate)",
    ".44 Mag (Crate)",
    "Catena rt.IV Auto-Rifle (Crate)",
    "Sampo Auto-Rifle 77 (Crate)",
    "Argenti r.II Rifle (Crate)",
    "Volta r.I Repeater (Crate)",
    "Fuscina pi.I (Crate)",
    "Blakerow 871 (Crate)",
    "KRR2-790 Omen (Crate)",
    "Clancy Cinder M3 (Crate)",
    "No.2B Hawthorne (Crate)",
    "No.2 Loughcaster (Crate)",
    "KRR3-792 Auger (Crate)",
    "Clancy-Raca M4 (Crate)",
    "7.62mm (Crate)",
    "KRF1-750 Dragonfly (Crate)",
    "No.4 The Pillory Scattergun (Crate)",
    "Buckshot (Crate)",
    "“The Pitch Gun” mc.V (Crate)",
    "“Lionclaw” mc.VIII (Crate)",
    "No.1 “The Liar” Submachinegun (Crate)",
    "Fiddler Submachine Gun Model 868 (Crate)",
    "9mm (Crate)",
    "228 Satterley Heavy Storm Rifle (Crate)",
    "Booker Greyhound Model 910 (Crate)",
    "“Dawn” Ve.II (Crate)",
    "“Quickhatch” Rt.I (Crate)",
    "“Typhon” ra.XII (Crate)",
    "Neville Anti-Tank Rifle (Crate)",
    "14.5mm (Crate)",
    "Venom c.II 35 (Crate)",
    "Bane 45 (Crate)",
    "Carnyx Anti-Tank Rocket Launcher (Crate)",
    "AP/RPG (Crate)",
    "Mounted Bonesaw MK.3 (Crate)",
    "Bonesaw MK.3 (Crate)",
    "ARC/RPG (Crate)",
    "“Molten Wind” v.II Flame Torch (Crate)",
    "Willow’s Bane Model 845 (Crate)",
    "KLG901-2 Lunaire F (Crate)",
    "Mounted Fissura gd.I (Crate)",
    "Tremola Grenade GPb-1 (Crate)",
    "PT-815 Smoke Grenade (Crate)",
    "Green Ash Grenade (Crate)",
    "Lamentum mm.IV (Crate)",
    "Malone Ratcatcher MK.1 (Crate)",
    "12.7mm (Crate)",
    "Daucus isg.III (Crate)",
    "30mm (Crate)",
    "Cremari Mortar (Crate)",
    "Incendiary Mortar Shell (Crate)",
    "Flare Mortar Shell (Crate)",
    "Shrapnel Mortar Shell (Crate)",
    "Mortar Shell (Crate)",
    "BF5 White Ash Flask Grenade (Crate)",
    "B2 Varsi Anti-Tank Grenade (Crate)",
    "Ignifist 30 (Crate)",
    "Mammon 91-b (Crate)",
    "Anti-Tank Sticky Bomb (Crate)",
    "Cutler Foebreaker (Crate)",
    "Cutler Launcher 4 (Crate)",
    "RPG (Crate)",
    "950-70b Anti-Aircraft Shell (Crate)",
    "20mm (Crate)",
    "94.5mm (Crate)",
    "75mm (Crate)",
    "Mark II Raidbreaker (Crate)",
    "Shatter Missile (Crate)",
    "Model-7 “Evie” (Crate)",
    "912 Shrike Rounds (Crate)",
    "4C-Fire Rocket (Crate)",
    "Flame Ammo (Crate)",
    "150mm (Crate)",
    "3C-High Explosive Rocket (Crate)",
    "Absol Anti-Aircraft Rounds (Crate)",
    "120mm (Crate)",
    "300mm (Crate)",
    "Quillback Torpedo (Crate)",
    "250mm \"Purity\" Shell (Crate)",
    "250mm \"Fury\" Shell (Crate)",
    "E681-B Hullbreaker Mine (Crate)",
    "Naval Buoy (Crate)",
    "68mm (Crate)",
    "40mm (Crate)",
    "Air Raid Siren (Crate)",
    "Legion Vexillum (Crate)",
    "War Ensign (Crate)",
    "Barbed Wire (Crate)",
    "Buckhorn CCQ-18 (Crate)",
    "Binoculars (Crate)",
    "Hydra’s Whisper (Crate)",
    "Havoc Charge (Crate)",
    "“Molten Wind” v.II Ammo (Crate)",
    "Willow's Bane Ammo (Crate)",
    "Crow’s Foot Mine (Crate)",
    "Listening Kit (Crate)",
    "Falias Raiding Club (Crate)",
    "Metal Beam (Crate)",
    "Paratrooper’s Ruck (Crate)",
    "Radio Backpack (Crate)",
    "Sandbag (Crate)",
    "Havoc Charge Detonator (Crate)",
    "Alligator Charge (Crate)",
    "Shovel (Crate)",
    "Sledge Hammer (Crate)",
    "Eleos Infantry Dagger (Crate)",
    "Abisme AT-99 Mine (Crate)",
    "Tripod (Crate)",
    "E680-S Rudder Lock (Crate)",
    "Wind Sock (Crate)",
    "Hammer (Crate)",
    "Wrench (Crate)",
    "Water Bucket (Crate)",
    "Water (Crate)",
    "Gas Mask (Crate)",
    "Gas Mask Filter (Crate)",
    "The Ospreay (Crate)",
    "Radio (Crate)",
    "Flight Mask (Crate)",
    "Bandages (Crate)",
    "First Aid Kit (Crate)",
    "Trauma Kit (Crate)",
    "Blood Plasma (Crate)",
    "Soldier Supplies (Crate)",
    "Diesel (Crate)",
    "Unstable Substances (Crate)",
    "Thermal Shielding (Crate)",
    "Processed Construction Materials (Crate)",
    "Steel Construction Materials (Crate)",
    "Assembly Materials I (Crate)",
    "Assembly Materials II (Crate)",
    "Assembly Materials III (Crate)",
    "Assembly Materials IV (Crate)",
    "Assembly Materials V (Crate)",
    "Rare Alloys (Crate)",
    "Heavy Oil (Crate)",
    "Enriched Oil (Crate)",
    "Oil (Crate)",
    "Petrol (Crate)",
    "Pipe (Crate)",
    "Aluminum Alloy (Crate)",
    "Basic Materials (Crate)",
    "Copper Alloy (Crate)",
    "Explosive Powder (Crate)",
    "Construction Materials (Crate)",
    "Rare Materials (Crate)",
    "Gravel (Crate)",
    "Heavy Explosive Powder (Crate)",
    "Iron Alloy (Crate)",
    "Maintenance Supplies (Crate)",
    "Rare Metal (Crate)",
    "Relic Materials (Crate)",
    "Refined Materials (Crate)",
    "Specialist’s Overcoat (Crate)",
    "Velian Flak Vest (Crate)",
    "Gunner’s Breastplate (Crate)",
    "Fabri Rucksack (Crate)",
    "Sapper Gear (Crate)",
    "Grenadier’s Baldric (Crate)",
    "Medic Fatigues (Crate)",
    "Physician’s Jacket (Crate)",
    "Remex Garb (Crate)",
    "Gentleman’s Peacoat (Crate)",
    "Officialis’ Attire (Crate)",
    "Officer’s Regalia (Crate)",
    "Auster’s Harness (Crate)",
    "Cloudrunner’s Vesture (Crate)",
    "Lodesman’s Lorica (Crate)",
    "Aviator’s Raiment (Crate)",
    "Legionary’s Oilcoat (Crate)",
    "Recon Camo (Crate)",
    "Outrider’s Mantle (Crate)",
    "Heavy Topcoat (Crate)",
    "Caoivish Parka (Crate)",
    "Legionary Fatigues (Crate)",
    "Infantry Battledress (Crate)",
    "Tankman’s Coveralls (Crate)",
    "Padded Boiler Suit (Crate)",
    "Colonial Aircraft Engine (Small) (Crate)",
    "Warden Aircraft Engine (Small) (Crate)",
    "Damaged Colonial Aircraft Engine (Small) (Crate)",
    "Damaged Warden Aircraft Engine (Small) (Crate)",
    "Colonial Aircraft Mechanical Parts (Small) (Crate)",
    "Warden Aircraft Mechanical Parts (Small) (Crate)",
    "Damaged Colonial Aircraft Mechanical Parts (Small) (Crate)",
    "Damaged Warden Aircraft Mechanical Parts (Small) (Crate)",
    "R-12 - “Salus” Ambulance",
    "R-12b - “Salva” Flame Truck",
    "Dunne Dousing Engine 3r",
    "Dunne Responder 3e",
    "O’Brien V.101 Freeman",
    "O’Brien v.200 Squire",
    "O’Brien V.190 Knave",
    "O’Brien V.113 Gravekeeper",
    "T3 “Xiphos”",
    "O’Brien V.130 Wild Jack",
    "O’Brien V.121 Highlander",
    "T5 “Percutio”",
    "T8 “Gemini”",
    "O’Brien V.110",
    "BMS - Aquatipper",
    "R-15 - “Chariot”",
    "Dunne Caravaner 2f",
    "BMS - Universal Assembly Rig",
    "BMS - Fabricator",
    "BMS - Class 2 Mobile Auto-Crane",
    "Noble Firebrand Mk. XVII",
    "Noble Widow MK. XIV",
    "GA6 “Cestus”",
    "Duncan’s Coin 14.5mm",
    "AA-2 \"Battering Ram\"",
    "Balfour Rampart 68mm",
    "Collins Cannon 68mm",
    "40-45 “Smelter”",
    "Balfour Wolfhound 40mm",
    "G40 “Sagittarii”",
    "Swallowtail 988/127-2",
    "30-250 “Tisiphone” Field Cannon",
    "Balfour Falconer 250mm",
    "BMS - Packmule Flatbed",
    "BMS - Ironship",
    "Das Krokodil by VAC",
    "Type B - “Lucian”",
    "81f-f Ronan Blackguard",
    "Type C - “Charon”",
    "74b-1 Ronan Gunship",
    "HH-d “Peltast”",
    "HH-a “Javelin”",
    "HH-b “Hoplite”",
    "Niska-Rycker Mk. IX Skycaller",
    "Niska Mk. II Blinder",
    "Niska Mk. III Scar Twin",
    "Niska Mk. I Gun Motor Carriage",
    "BMS - Scrap Hauler",
    "AU-A150 Taurine Rigger",
    "Cnute Cliffwrest",
    "AB-8 “Acheron”",
    "AB-11 “Doru”",
    "Mulloy LPC",
    "945g “Stygian Bolt”",
    "Balfour Stockade 75mm",
    "120-68 “Koronides” Field Gun",
    "40-250 “Alekto” Heavy Cannon",
    "Rycker 4/3-F Wasp Nest",
    "K-81e “Sombre”",
    "68A-4 Ronan Fathomer",
    "HC-2 “Scorpion”",
    "HA-1 “Sagaris”",
    "Sharkey-Devitt Birdeater Mk. I",
    "Devitt-Caine Mk. IV MMR",
    "H-5 \"Hatchet\"",
    "Devitt Ironhide Mk. IV",
    "H-19 “Vulcan”",
    "H-8 “Kranesca”",
    "H-10 “Pelekys”",
    "Devitt Mk. III",
    "Strider",
    "Rinnspeir Ornitier-Class Gunship",
    "86K-a “Bardiche”",
    "Gallagher Thornfall Mk. VI",
    "Gallagher Highwayman Mk. III",
    "Gallagher Outlaw Mk. II",
    "86K-c “Ranseur”",
    "Gallagher Brigand Mk. I",
    "90T-v “Nemesis”",
    "Silverhand Lordscar - Mk. X",
    "85K-b “Falchion”",
    "85V-g \"Talos\"",
    "85K-a “Spatha”",
    "Silverhand Chieftain - Mk. VI",
    "Silverhand - Mk. IV",
    "Bellweather by VAC",
    "HC-7 \"Ballista\"",
    "03MM “Caster”",
    "00MS “Stinger”",
    "Kivela Power Wheel 80-1",
    "King Jester Mk. I-1",
    "King Gallant Mk. II",
    "King Spire Mk. I",
    "UV-05a “Argonaut”",
    "UV-24 “Icarus”",
    "Drummond Spitfire 100d",
    "UV-5c “Odyssey”",
    "Drummond Loscann 55c",
    "Drummond 100a",
    "T12 “Actaeon” Tankette",
    "T14 “Vesta” Tankette",
    "T13 “Deioneus” Rocket Battery",
    "T20 “Ixion” Tankette",
    "Rooster - Lamploader",
    "Rooster - Tumblebox",
    "Rooster - Junkwagon",
    "R-1 Hauler",
    "Dunne Leatherback 2a",
    "RR-3 “Stolon” Tanker",
    "Dunne Fuelrunner 2d",
    "R-5b “Sisyphus” Hauler",
    "Dunne Landrunner 12c",
    "R-17 “Retiarius” Skirmisher",
    "R-9 “Speartip” Escort",
    "R-5 “Atlas” Hauler",
    "Dunne Loadlugger 3c",
    "Dunne Transport",
    "V-1 Tzykalia",
    "Tulka P4 Welkinrive",
    "Mergo-4 “Myrmidon”",
    "Toxot-902 “Blind Silver”",
    "Luminary Mk. II Harbinger",
    "V-5b Pegasus",
    "Rinnspeir Mk. I Zealot",
    "A59 Venti “Perdix”",
    "Luminary Mk. VI Emissary",
    "A51 Venti “Daedalus”",
    "Luminary Mk. IV Herald",
    "M925 Austringer Man-O-War",
    "Tulka I1.9 White Raven",
    "V-1 Tzykalia (Crate)",
    "Tulka P4 Welkinrive (Crate)",
    "Mergo-4 “Myrmidon” (Crate)",
    "Toxot-902 “Blind Silver” (Crate)",
    "Luminary Mk. II Harbinger (Crate)",
    "V-5b Pegasus (Crate)",
    "Rinnspeir Mk. I Zealot (Crate)",
    "A59 Venti “Perdix” (Crate)",
    "Luminary Mk. VI Emissary (Crate)",
    "A51 Venti “Daedalus” (Crate)",
    "Luminary Mk. IV Herald (Crate)",
    "M925 Austringer Man-O-War (Crate)",
    "Tulka I1.9 White Raven (Crate)",
    "R-12 - “Salus” Ambulance (Crate)",
    "Dunne Responder 3e (Crate)",
    "O’Brien V.190 Knave (Crate)",
    "T3 “Xiphos” (Crate)",
    "O’Brien V.110 (Crate)",
    "BMS - Aquatipper (Crate)",
    "R-15 - “Chariot” (Crate)",
    "Dunne Caravaner 2f (Crate)",
    "BMS - Universal Assembly Rig (Crate)",
    "BMS - Class 2 Mobile Auto-Crane (Crate)",
    "Noble Widow MK. XIV (Crate)",
    "AA-2 \"Battering Ram\" (Crate)",
    "Collins Cannon 68mm (Crate)",
    "Balfour Wolfhound 40mm (Crate)",
    "G40 “Sagittarii” (Crate)",
    "Swallowtail 988/127-2 (Crate)",
    "30-250 “Tisiphone” Field Cannon (Crate)",
    "Balfour Falconer 250mm (Crate)",
    "BMS - Packmule Flatbed (Crate)",
    "BMS - Ironship (Crate)",
    "Das Krokodil by VAC (Crate)",
    "Type B - “Lucian” (Crate)",
    "81f-f Ronan Blackguard (Crate)",
    "Type C - “Charon” (Crate)",
    "74b-1 Ronan Gunship (Crate)",
    "HH-a “Javelin” (Crate)",
    "Niska Mk. I Gun Motor Carriage (Crate)",
    "AB-8 “Acheron” (Crate)",
    "Mulloy LPC (Crate)",
    "120-68 “Koronides” Field Gun (Crate)",
    "K-81e “Sombre” (Crate)",
    "68A-4 Ronan Fathomer (Crate)",
    "HC-2 “Scorpion” (Crate)",
    "HA-1 “Sagaris” (Crate)",
    "Sharkey-Devitt Birdeater Mk. I (Crate)",
    "H-5 \"Hatchet\" (Crate)",
    "Devitt Mk. III (Crate)",
    "Strider (Crate)",
    "Rinnspeir Ornitier-Class Gunship (Crate)",
    "86K-a “Bardiche” (Crate)",
    "Gallagher Brigand Mk. I (Crate)",
    "90T-v “Nemesis” (Crate)",
    "85K-b “Falchion” (Crate)",
    "Silverhand - Mk. IV (Crate)",
    "Bellweather by VAC (Crate)",
    "03MM “Caster” (Crate)",
    "Kivela Power Wheel 80-1 (Crate)",
    "King Spire Mk. I (Crate)",
    "UV-05a “Argonaut” (Crate)",
    "Drummond 100a (Crate)",
    "T12 “Actaeon” Tankette (Crate)",
    "Rooster - Lamploader (Crate)",
    "Rooster - Tumblebox (Crate)",
    "Rooster - Junkwagon (Crate)",
    "R-1 Hauler (Crate)",
    "RR-3 “Stolon” Tanker (Crate)",
    "Dunne Fuelrunner 2d (Crate)",
    "R-5 “Atlas” Hauler (Crate)",
    "Dunne Loadlugger 3c (Crate)",
    "Dunne Transport (Crate)",
    "Concrete Mixer",
    "Construction Equipment",
    "DAE 5b “Zeal”",
    "Leary AA-70 Bolas",
    "Huber Starbreaker 94.5mm",
    "Leary Shellbore 68mm",
    "DAE 2a-1 “Ruptura”",
    "50-500 “Thunderbolt” Cannon",
    "Huber Exalt 150mm",
    "DAE 1o-3 “Polybolos”",
    "DAE 1b-2 “Serra”",
    "Leary Snare Trap 20",
    "Huber Lariat 120mm",
    "DAE 3b-2 “Hades’ Net”",
    "Construction Parts",
    "Underground Fortress Parts",
    "Intelligence Center Parts",
    "SC-3 Aerial Interceptor Array Parts",
    "Storm Cannon Parts",
    "Structure Parts",
    "Weather Station Parts",
    "Liquid Container",
    "Material Pallet",
    "Resource Container",
    "A0E-9 Rocket Booster",
    "A0E-9 Rocket Body",
    "A0E-9 Rocket Warhead",
    "Naval Hull Segments",
    "Naval Shell Plating",
    "Naval Turbine Components",
    "Shipping Container",
    "Concrete Mixer (Crate)",
    "Construction Equipment (Crate)",
    "DAE 5b “Zeal” (Crate)",
    "Leary AA-70 Bolas (Crate)",
    "Leary Shellbore 68mm (Crate)",
    "50-500 “Thunderbolt” Cannon (Crate)",
    "Huber Exalt 150mm (Crate)",
    "DAE 1o-3 “Polybolos” (Crate)",
    "DAE 1b-2 “Serra” (Crate)",
    "Leary Snare Trap 20 (Crate)",
    "Huber Lariat 120mm (Crate)",
    "Liquid Container (Crate)",
    "Material Pallet (Crate)",
    "Resource Container (Crate)",
    "Shipping Container (Crate)"
]);
